In [1]:
import json
import os.path
from collections.abc import Callable
from statistics import mean
from typing import Literal, NamedTuple

import numpy as np
import pandas as pd

from tiu_phi_3_5_mini.evaluation_utils import MetricsForDatasetProbes, ConfusionMetrics, TraditionalMetrics
from tiu_phi_3_5_mini.phi_3_5_constants import dsets_index_path, four_way_topics_index_path, misc_datasets_index_path, \
    directions_reconstruction_losses_path, separation_by_layer_analysis_path, train_split_classification_metrics_path, \
    validation_split_classification_metrics_path, test_classification_metrics_path

In [2]:
dsets_index_df = pd.read_csv(dsets_index_path, index_col="Idx")
num_dsets = dsets_index_df.shape[0]

In [3]:
# top-level key is the name of a topic that has pos/neg/conj/disj variants, second level key is one of those variant names
with four_way_topics_index_path.open("r") as f:
    dset_idxs_for_4way_topics: dict[str, dict[str, int]] = json.load(f)
with misc_datasets_index_path.open("r") as f:
    idxs_for_other_dsets: dict[str, int] = json.load(f)

In [4]:
for dset_idx, dset_dtls in dsets_index_df.iterrows():
    categ_nm = dset_dtls["Categ_Folder"]    
    if dset_dtls['in_german']:
        assert categ_nm in dset_idxs_for_4way_topics, f"{categ_nm} topic has german variant but wasn't captured in earlier tracking of standard ('4-way') topics"
        if dset_dtls['is_negated']:
            dset_idxs_for_4way_topics[categ_nm]["de_neg"] = dset_idx
        else:
            dset_idxs_for_4way_topics[categ_nm]["de_affirm"] = dset_idx

In [5]:
affirm_german_dset_idxs = dsets_index_df.loc[dsets_index_df.in_german & (~dsets_index_df.is_negated)].index.to_list()
negated_german_dset_idxs = dsets_index_df.loc[dsets_index_df.in_german & dsets_index_df.is_negated].index.to_list()

In [6]:
directions_reconstruction_losses = pd.read_csv(directions_reconstruction_losses_path)

dir_probe_scenarios_strs = directions_reconstruction_losses['scenario_identifier'].to_list()
dir_probe_scenarios_specs = [tuple(map(int, scenario_str.split(' '))) for scenario_str in dir_probe_scenarios_strs]

In [87]:
num_standard_topics = dsets_index_df[dsets_index_df["is_other"] == False]["Categ_Folder"].nunique()
assert num_standard_topics == len(dset_idxs_for_4way_topics)

In [7]:
#'scenarios' describe the different combinations of data that directions/probes were trained on 
other_categs: set[str] = set(dsets_index_df.loc[dsets_index_df.is_other].Categ_Folder.to_list())

scenario_standard_categs: dict[tuple[int,...], list[str]] = {}
scenario_other_dset_names: dict[tuple[int,...], list[str]] = {}
for scenario_id in dir_probe_scenarios_specs:
    scenario_standard_categs[scenario_id] = []
    scenario_other_dset_names[scenario_id] = []
    for dset_idx_in_scenario in scenario_id:
        if not dsets_index_df.loc[dset_idx_in_scenario, "is_other"]:
            curr_standard_categ = dsets_index_df.loc[dset_idx_in_scenario, "Categ_Folder"]
            if curr_standard_categ not in scenario_standard_categs[scenario_id]:
                scenario_standard_categs[scenario_id].append(curr_standard_categ)
        else:
            curr_other_dset_name = os.path.splitext(dsets_index_df.loc[dset_idx_in_scenario, "Dataset_File"])[0]
            assert curr_other_dset_name not in scenario_other_dset_names[scenario_id]
            scenario_other_dset_names[scenario_id].append(curr_other_dset_name)

scenario_data_variants: dict[tuple[int,...], set[Literal["affirm", "neg", "conj", "disj", "other"]]] = {}
for scenario_id in dir_probe_scenarios_specs:
    scenario_data_variants[scenario_id] = set()
    for dset_idx_in_scenario in scenario_id:
        assert not dsets_index_df.at[dset_idx_in_scenario, "in_german"]
        scenario_data_variants[scenario_id].add(
            "other" if dsets_index_df.at[dset_idx_in_scenario, "is_other"] else "neg" if dsets_index_df.at[dset_idx_in_scenario, "is_negated"] else "conj" if dsets_index_df.at[dset_idx_in_scenario, "is_conj"] else "disj" if dsets_index_df.at[dset_idx_in_scenario, "is_disj"] else "affirm")

scenario_labels: dict[tuple[int,...], str] = {}
for scenario_id in dir_probe_scenarios_specs:
    label = "+".join(scenario_standard_categs[scenario_id])
    was_earlier_variant_included=False
    if "affirm" in scenario_data_variants[scenario_id]:
        label += "__affirmative"
        was_earlier_variant_included = True
    if "neg" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "negated"
        was_earlier_variant_included = True
    if "conj" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "conjunction"
        was_earlier_variant_included = True
    if "disj" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "disjunction"
    # assuming no training scenarios include german
    if scenario_other_dset_names[scenario_id]:
        label += ("_and_" if label else "") + "+".join(scenario_other_dset_names[scenario_id])
    scenario_labels[scenario_id] = label

In [8]:
t_f_sep_by_layer_df = pd.read_csv(separation_by_layer_analysis_path, index_col="Idx")
t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_truthful_reply"], "Separation after 18"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_lie"], "Separation after 18"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_truthful_reply"], "Separation after 25"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_lie"], "Separation after 25"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_truthful_reply"], "Separation after 18"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_lie"], "Separation after 18"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_truthful_reply"], "Separation after 25"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_lie"], "Separation after 25"]

In [9]:
with train_split_classification_metrics_path.open("r") as f:
    serialized_train_metrics = json.load(f)
with validation_split_classification_metrics_path.open("r") as f:
    serialized_validation_metrics = json.load(f)
train_metrics: dict[tuple[int,...], MetricsForDatasetProbes] = {
    tuple(map(int, scenario_str.split(' '))): MetricsForDatasetProbes.from_dict(metrics_dict) for scenario_str, metrics_dict in serialized_train_metrics.items()
}
validation_metrics: dict[tuple[int,...], MetricsForDatasetProbes] = {
    tuple(map(int, scenario_str.split(' '))): MetricsForDatasetProbes.from_dict(metrics_dict) for scenario_str, metrics_dict in serialized_validation_metrics.items()
}

In [10]:
with test_classification_metrics_path.open("r") as f:
    serialized_probes_metrics_on_test_dsets = json.load(f)
# first level key identifies the scenario (of one or more datasets) which the probe was trained on;
# second level key identifies the previously-unseen dataset which the probe is tested on
probes_metrics_on_test_dsets: dict[tuple[int,...], dict[int, MetricsForDatasetProbes]] = {
    tuple(map(int, scenario_str.split(' '))): {
        int(test_dset_idx): MetricsForDatasetProbes.from_dict(serialized_test_dset_metrics) for test_dset_idx, serialized_test_dset_metrics in serialized_test_dsets_metrics.items()
    } for scenario_str, serialized_test_dsets_metrics in serialized_probes_metrics_on_test_dsets.items()
}

In [11]:
class TruthPolarityDirsEval(NamedTuple):
    rel_loss_reduct_on_train: float
    rel_loss_reduct_on_validation: float
    rel_loss_reduct_on_validation_using_validation_mean: float

lyr18_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}
lyr25_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}
lyrs18_and_25_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}

for _, recon_losses_row in directions_reconstruction_losses.iterrows():
    scenario_id = tuple(map(int, recon_losses_row["scenario_identifier"].split(' ')))
    lyr18_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyr18_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyr18_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyr18_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr18_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyr18_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr18_validation_mean_activ_loss_on_validation"]
    )
    lyr25_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyr25_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyr25_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyr25_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr25_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyr25_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr25_validation_mean_activ_loss_on_validation"]
    )
    lyrs18_and_25_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyrs18_and_25_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyrs18_and_25_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyrs18_and_25_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyrs18_and_25_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyrs18_and_25_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyrs18_and_25_validation_mean_activ_loss_on_validation"]
    )

In [12]:
class ProbeEvalOnData(NamedTuple):
    acc: float
    precision: float
    recall: float
    f1: float
    brier: float
    soft_precision: float
    soft_recall: float
    soft_f1: float

lyr18_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyr25_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyrs18_and_25_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

lyr18_baseline_linear_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

for scenario_id, probes_metrics_on_train in train_metrics.items():
    lyr18_train_metrics = probes_metrics_on_train.lyr18_probe_metrics
    lyr18_train_trad_metrics = lyr18_train_metrics.get_traditional_metrics()
    lyr18_train_soft_metrics = lyr18_train_metrics.get_soft_metrics()
    lyr25_train_metrics = probes_metrics_on_train.lyr25_probe_metrics
    lyr25_train_trad_metrics = lyr25_train_metrics.get_traditional_metrics()
    lyr25_train_soft_metrics = lyr25_train_metrics.get_soft_metrics()
    lyrs18_and_25_train_metrics = probes_metrics_on_train.lyrs18_and_25_probe_metrics
    lyrs18_and_25_train_trad_metrics = lyrs18_and_25_train_metrics.get_traditional_metrics()
    lyrs18_and_25_train_soft_metrics = lyrs18_and_25_train_metrics.get_soft_metrics()
    
    lyr18_baseline_linear_probes_train_metrics = probes_metrics_on_train.lyr18_baseline_linear_probe_metrics
    lyr18_baseline_linear_probes_train_trad_metrics = lyr18_baseline_linear_probes_train_metrics.get_traditional_metrics()
    lyr18_baseline_linear_probes_train_soft_metrics = lyr18_baseline_linear_probes_train_metrics.get_soft_metrics()
    
    lyr18_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_train_trad_metrics.accuracy, precision=lyr18_train_trad_metrics.precision, recall=lyr18_train_trad_metrics.recall,
        f1=lyr18_train_trad_metrics.f1, brier=lyr18_train_metrics.get_brier_score(), soft_precision=lyr18_train_soft_metrics.soft_precision,
        soft_recall=lyr18_train_soft_metrics.soft_recall, soft_f1=lyr18_train_soft_metrics.soft_f1)
    lyr25_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr25_train_trad_metrics.accuracy, precision=lyr25_train_trad_metrics.precision, recall=lyr25_train_trad_metrics.recall,
        f1=lyr25_train_trad_metrics.f1, brier=lyr25_train_metrics.get_brier_score(), soft_precision=lyr25_train_soft_metrics.soft_precision,
        soft_recall=lyr25_train_soft_metrics.soft_recall, soft_f1=lyr25_train_soft_metrics.soft_f1)
    lyrs18_and_25_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyrs18_and_25_train_trad_metrics.accuracy, precision=lyrs18_and_25_train_trad_metrics.precision, recall=lyrs18_and_25_train_trad_metrics.recall,
        f1=lyrs18_and_25_train_trad_metrics.f1, brier=lyrs18_and_25_train_metrics.get_brier_score(), soft_precision=lyrs18_and_25_train_soft_metrics.soft_precision,
        soft_recall=lyrs18_and_25_train_soft_metrics.soft_recall, soft_f1=lyrs18_and_25_train_soft_metrics.soft_f1)
    
    lyr18_baseline_linear_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_baseline_linear_probes_train_trad_metrics.accuracy, precision=lyr18_baseline_linear_probes_train_trad_metrics.precision,
        recall=lyr18_baseline_linear_probes_train_trad_metrics.recall, f1=lyr18_baseline_linear_probes_train_trad_metrics.f1,
        brier=lyr18_baseline_linear_probes_train_metrics.get_brier_score(), soft_precision=lyr18_baseline_linear_probes_train_soft_metrics.soft_precision,
        soft_recall=lyr18_baseline_linear_probes_train_soft_metrics.soft_recall, soft_f1=lyr18_baseline_linear_probes_train_soft_metrics.soft_f1
    )

lyr18_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyr25_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyrs18_and_25_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

lyr18_baseline_linear_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

for scenario_id, probes_metrics_on_validation in validation_metrics.items():
    lyr18_validation_metrics = probes_metrics_on_validation.lyr18_probe_metrics
    lyr18_validation_trad_metrics = lyr18_validation_metrics.get_traditional_metrics()
    lyr18_validation_soft_metrics = lyr18_validation_metrics.get_soft_metrics()
    lyr25_validation_metrics = probes_metrics_on_validation.lyr25_probe_metrics
    lyr25_validation_trad_metrics = lyr25_validation_metrics.get_traditional_metrics()
    lyr25_validation_soft_metrics = lyr25_validation_metrics.get_soft_metrics()
    lyrs18_and_25_validation_metrics = probes_metrics_on_validation.lyrs18_and_25_probe_metrics
    lyrs18_and_25_validation_trad_metrics = lyrs18_and_25_validation_metrics.get_traditional_metrics()
    lyrs18_and_25_validation_soft_metrics = lyrs18_and_25_validation_metrics.get_soft_metrics()
    
    lyr18_baseline_linear_probes_validation_metrics = probes_metrics_on_validation.lyr18_baseline_linear_probe_metrics
    lyr18_baseline_linear_probes_validation_trad_metrics = lyr18_baseline_linear_probes_validation_metrics.get_traditional_metrics()
    lyr18_baseline_linear_probes_validation_soft_metrics = lyr18_baseline_linear_probes_validation_metrics.get_soft_metrics()
    
    lyr18_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_validation_trad_metrics.accuracy, precision=lyr18_validation_trad_metrics.precision, recall=lyr18_validation_trad_metrics.recall,
        f1=lyr18_validation_trad_metrics.f1, brier=lyr18_validation_metrics.get_brier_score(), soft_precision=lyr18_validation_soft_metrics.soft_precision,
        soft_recall=lyr18_validation_soft_metrics.soft_recall, soft_f1=lyr18_validation_soft_metrics.soft_f1)
    lyr25_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr25_validation_trad_metrics.accuracy, precision=lyr25_validation_trad_metrics.precision, recall=lyr25_validation_trad_metrics.recall,
        f1=lyr25_validation_trad_metrics.f1, brier=lyr25_validation_metrics.get_brier_score(), soft_precision=lyr25_validation_soft_metrics.soft_precision,
        soft_recall=lyr25_validation_soft_metrics.soft_recall, soft_f1=lyr25_validation_soft_metrics.soft_f1)
    lyrs18_and_25_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyrs18_and_25_validation_trad_metrics.accuracy, precision=lyrs18_and_25_validation_trad_metrics.precision, recall=lyrs18_and_25_validation_trad_metrics.recall,
        f1=lyrs18_and_25_validation_trad_metrics.f1, brier=lyrs18_and_25_validation_metrics.get_brier_score(), soft_precision=lyrs18_and_25_validation_soft_metrics.soft_precision,
        soft_recall=lyrs18_and_25_validation_soft_metrics.soft_recall, soft_f1=lyrs18_and_25_validation_soft_metrics.soft_f1)
    
    lyr18_baseline_linear_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_baseline_linear_probes_validation_trad_metrics.accuracy, precision=lyr18_baseline_linear_probes_validation_trad_metrics.precision,
        recall=lyr18_baseline_linear_probes_validation_trad_metrics.recall, f1=lyr18_baseline_linear_probes_validation_trad_metrics.f1,
        brier=lyr18_baseline_linear_probes_validation_metrics.get_brier_score(), soft_precision=lyr18_baseline_linear_probes_validation_soft_metrics.soft_precision,
        soft_recall=lyr18_baseline_linear_probes_validation_soft_metrics.soft_recall, soft_f1=lyr18_baseline_linear_probes_validation_soft_metrics.soft_f1
    )

In [13]:
lyr18_probe_row_dicts: list[dict[str, str|float]] = []
lyr25_probe_row_dicts: list[dict[str, str|float]] = []
lyrs18_and_25_probe_row_dicts: list[dict[str, str|float]] = []

lyr18_baseline_linear_probe_row_dicts: list[dict[str, str|float]] = []

lyr25_rel_to_18_probe_row_dicts: list[dict[str, str|float]] = []
lyrs18_and_25_rel_to_just_18_probe_row_dicts: list[dict[str, str|float]] = []

lyr18_ttpd_probe_to_baseline_linear_probe_row_dicts: list[dict[str, str | float]] = []

for scenario_id in dir_probe_scenarios_specs:
    lyr18_t_f_sep = mean([t_f_sep_by_layer_df.at[dset_idx_in_scenario, "Separation after 18"] for dset_idx_in_scenario in scenario_id])
    lyr25_t_f_sep = mean([t_f_sep_by_layer_df.at[dset_idx_in_scenario, "Separation after 25"] for dset_idx_in_scenario in scenario_id])
    lyr18_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": lyr18_t_f_sep, "train_recon_improv": lyr18_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyr18_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyr18_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyr18_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyr18_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyr18_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyr18_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyr18_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyr18_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyr18_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyr18_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyr18_probe_row_dicts.append(lyr18_probe_row_dict)
    lyr25_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": lyr25_t_f_sep, "train_recon_improv": lyr25_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyr25_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyr25_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyr25_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyr25_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyr25_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyr25_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyr25_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyr25_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyr25_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyr25_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyr25_probe_row_dicts.append(lyr25_probe_row_dict)
    lyrs18_and_25_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": (lyr18_t_f_sep + lyr25_t_f_sep) / 2,
        "train_recon_improv": lyrs18_and_25_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyrs18_and_25_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyrs18_and_25_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyrs18_and_25_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyrs18_and_25_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyrs18_and_25_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyrs18_and_25_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyrs18_and_25_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyrs18_and_25_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyrs18_and_25_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyrs18_and_25_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyrs18_and_25_probe_row_dicts.append(lyrs18_and_25_probe_row_dict)
    
    lyr18_baseline_linear_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "val_acc": lyr18_baseline_linear_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyr18_baseline_linear_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyr18_baseline_linear_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyr18_baseline_linear_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyr18_baseline_linear_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyr18_baseline_linear_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyr18_baseline_linear_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyr18_baseline_linear_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyr18_baseline_linear_probe_row_dicts.append(lyr18_baseline_linear_probe_row_dict)
    
    lyr25_rel_to_18_probe_row_dicts.append({
        col_nm: (lyr18_probe_row_dict[col_nm] if col_nm == "scenario" else lyr25_probe_row_dict[col_nm]-lyr18_probe_row_dict[col_nm]) for col_nm in lyr18_probe_row_dict.keys()
    })
    lyrs18_and_25_rel_to_just_18_probe_row_dicts.append({
        col_nm: (lyr18_probe_row_dict[col_nm] if col_nm == "scenario" else lyrs18_and_25_probe_row_dict[col_nm]-lyr18_probe_row_dict[col_nm]) for col_nm in lyr18_probe_row_dict.keys()
    })
    
    lyr18_ttpd_probe_to_baseline_linear_probe_row_dicts.append({
        col_nm: (lyr18_probe_row_dict[col_nm] if col_nm == "scenario" else lyr18_probe_row_dict[col_nm]-lyr18_baseline_linear_probe_row_dict[col_nm]) for col_nm in lyr18_baseline_linear_probe_row_dict.keys()
    })
    

lyr18_eval_except_test_df = pd.DataFrame(lyr18_probe_row_dicts)
lyr25_eval_except_test_df = pd.DataFrame(lyr25_probe_row_dicts)
lyrs18_and_25_eval_except_test_df = pd.DataFrame(lyrs18_and_25_probe_row_dicts)

lyr18_baseline_linear_probes_eval_except_test_df = pd.DataFrame(lyr18_baseline_linear_probe_row_dicts)

lyr25_rel_to_18_eval_except_test_df = pd.DataFrame(lyr25_rel_to_18_probe_row_dicts)
lyrs18_and_25_rel_to_18_eval_except_test_df = pd.DataFrame(lyrs18_and_25_rel_to_just_18_probe_row_dicts)

lyr18_ttpd_probe_to_baseline_linear_probe_eval_except_test_df = pd.DataFrame(lyr18_ttpd_probe_to_baseline_linear_probe_row_dicts)

For the "tf_sep" aka "true-false separation" column, and the ambiguous/unambiguous truth/lie (plus "honest reply despite incentive to lie") datasets,  
the value in the "ambiguous lie" and "ambiguous truthful reply" rows represent the separation between ambiguous lies and truths,  
the value in the "unambiguous lie" and "unambiguous truthful reply" rows represent the separation between unambiguous lies and truths,
and the 0.0 values for the "honest reply despite incentive to lie" row should be ignored.

When evaluating the below numbers, please note that brier scores are better if they are lower (unlike all other metrics here, which are better if they are higher)

In [14]:
lyr18_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.873458,4.543415e-01,5.163863e-01,3.967561e-01,1.000000,1.000000,2.445273e-08,0.999943,0.992366,0.992908,8.771814e-03,0.989470
1,animal_class__conjunction,0.314961,2.398567e-01,2.314483e-01,2.357424e-01,0.890000,0.899083,6.859379e-02,0.876145,0.917500,0.920097,6.192252e-02,0.879679
2,animal_class__disjunction,0.029296,2.734168e-02,3.243016e-02,3.037365e-02,0.740000,0.697674,1.855859e-01,0.586721,0.717500,0.729017,1.874590e-01,0.632118
3,animal_class__negated,0.579465,3.598452e-01,4.085457e-01,3.995034e-01,1.000000,1.000000,6.577489e-04,0.995938,0.984733,0.984848,1.469421e-02,0.975943
4,cities__affirmative,1.690080,6.311205e-01,6.175942e-01,6.166543e-01,0.983333,0.982578,1.536337e-02,0.974531,0.983278,0.983526,1.203893e-02,0.978910
5,cities__conjunction,0.388754,2.749372e-01,2.993844e-01,2.982197e-01,0.960000,0.964286,3.396462e-02,0.934809,0.930718,0.933759,4.737542e-02,0.912977
6,cities__disjunction,0.058523,5.700467e-02,4.585128e-02,4.644103e-02,0.800000,0.795918,1.366856e-01,0.716584,0.855000,0.852041,1.151929e-01,0.742089
7,cities__negated,0.868476,4.610974e-01,4.793974e-01,4.679124e-01,0.990000,0.991150,8.395773e-03,0.984477,0.985786,0.985482,1.017570e-02,0.979065
8,element_symb__affirmative,0.577514,3.498783e-01,4.370834e-01,4.490662e-01,0.973684,0.975610,2.134477e-02,0.965086,0.905405,0.912500,6.313708e-02,0.913252
9,element_symb__conjunction,0.425471,3.073251e-01,2.748850e-01,2.742458e-01,0.880000,0.884615,7.882613e-02,0.853128,0.932500,0.940659,5.868069e-02,0.892681
10,element_symb__disjunction,0.066850,6.149318e-02,6.555922e-02,6.573485e-02,0.800000,0.818182,1.413988e-01,0.752431,0.790000,0.787879,1.353580e-01,0.737389
11,element_symb__negated,0.365157,2.844515e-01,2.087251e-01,2.134846e-01,1.000000,1.000000,9.240658e-19,1.000000,1.000000,1.000000,6.743369e-25,1.000000
12,facts__affirmative,0.093213,8.781164e-02,7.354002e-02,6.904972e-02,0.858407,0.885714,1.054875e-01,0.820781,0.850446,0.863544,1.072506e-01,0.803707
13,facts__conjunction,0.035627,3.673653e-02,2.145067e-02,2.171824e-02,0.720000,0.730769,1.866593e-01,0.650655,0.790000,0.814978,1.412838e-01,0.727692
14,facts__disjunction,0.017876,1.650338e-02,1.990205e-02,2.031295e-02,0.760000,0.727273,1.681977e-01,0.633569,0.712500,0.679666,1.881253e-01,0.617878
15,facts__negated,0.028115,2.862351e-02,2.065965e-02,2.092022e-02,0.823009,0.818182,1.239086e-01,0.773496,0.904018,0.903803,7.790436e-02,0.832414
16,inventors__affirmative,0.059885,5.634922e-02,5.107413e-02,5.130731e-02,0.841463,0.860215,1.071005e-01,0.804620,0.833333,0.844828,1.331661e-01,0.777379
17,inventors__conjunction,0.024496,2.481788e-02,1.691028e-02,1.747544e-02,0.720000,0.754386,1.596683e-01,0.733773,0.810000,0.829596,1.303819e-01,0.757822
18,inventors__disjunction,0.011326,1.231043e-02,5.683728e-03,5.092700e-03,0.700000,0.732143,2.037729e-01,0.636309,0.740000,0.754717,1.790653e-01,0.644249
19,inventors__negated,0.085275,8.420518e-02,4.965519e-02,4.958424e-02,0.658537,0.631579,1.951255e-01,0.606508,0.706790,0.686469,1.714797e-01,0.652882
20,ambiguous_lie,0.051308,5.361147e-08,3.629734e-07,6.957434e-08,0.500000,NaN,2.412132e-01,NaN,0.428571,NaN,2.524060e-01,NaN
21,ambiguous_truthful_reply,0.051308,-6.544491e-08,9.936519e-08,0.000000e+00,0.600000,0.750000,2.086981e-01,0.710639,0.555556,0.714286,2.632712e-01,0.667486
22,honest_reply_despite_incentive_to_lie,0.000000,-1.319963e-07,2.438925e-07,0.000000e+00,1.000000,1.000000,7.010247e-02,0.847460,0.250000,0.400000,2.680697e-01,0.664283
23,unambiguous_lie,0.107328,1.258997e-07,-2.674763e-07,0.000000e+00,0.600000,NaN,2.176609e-01,NaN,0.538462,NaN,2.550336e-01,NaN
24,unambiguous_truthful_reply,0.107328,6.411020e-08,-2.047305e-07,-7.574867e-08,0.727273,0.842105,2.202386e-01,0.697597,0.500000,0.666667,2.593466e-01,0.666987
25,larger_than,0.456852,3.142809e-01,3.110852e-01,3.111883e-01,0.972222,0.971867,2.691245e-02,0.946148,0.970960,0.972019,2.098595e-02,0.955345
26,smaller_than,0.347493,2.578911e-01,2.581460e-01,2.549792e-01,0.949495,0.955357,3.484066e-02,0.932294,0.945076,0.946919,3.824428e-02,0.920902
27,sp_en_trans__negated,0.679175,4.083760e-01,3.927502e-01,3.957529e-01,1.000000,1.000000,2.294588e-04,0.997626,0.996466,0.996466,2.715710e-03,0.995245
28,sp_en_trans__affirmative,0.763526,4.254077e-01,4.657559e-01,4.151790e-01,0.971831,0.977778,1.804558e-02,0.974164,0.968198,0.967273,1.792615e-02,0.966510
29,sp_en_trans__conjunction,0.360656,2.654025e-01,2.726139e-01,2.707033e-01,0.930000,0.930693,5.284401e-02,0.918356,0.967500,0.970787,2.128471e-02,0.955200
30,sp_en_trans__disjunction,0.055794,5.717739e-02,3.746276e-02,3.632303e-02,0.840000,0.818182,1.090786e-01,0.762275,0.832500,0.813370,1.089132e-01,0.770467
31,common_claim_true_false,0.016943,1.601768e-02,1.895602e-02,1.898451e-02,0.782022,0.786813,1.528305e-01,0.684293,0.747472,0.749093,1.691688e-01,0.665531
32,counterfact_true_false,0.012648,1.257900e-02,1.211249e-02,1.211160e-02,0.707962,0.729851,1.875083e-01,0.634437,0.710219,0.735300,1.858964e-01,0.638215
33,animal_class__affirmative+negated,0.726462,3.255649e-01,3.730479e-01,3.483443e-01,1.000000,1.000000,3.724002e-03,0.988765,0.984733,0.985294,9.318734e-03,0.984407
34,animal_class__affirmative+disjunction,0.451377,3.461717e-02,3.647969e-02,3.132026e-02,0.796992,0.761062,1.403436e-01,0.657099,0.779661,0.789189,1.506604e-01,0.710305
35,animal_class__negated+conjunction,0.447213,1.274588e-01,1.192823e-01,1.191230e-01,0.917293,0.925170,5.825581e-02,0.896909,0.930320,0.932849,5.293857e-02,0.895870
36,animal_class__affirmative+negated+conjunction+...,0.449295,5.486206e-02,5.498721e-02,5.459481e-02,0.748120,0.712446,1.358077e-01,0.718068,0.740113,0.714286,1.394676e-01,0.725212
37,cities__affirmative+negated,1.279278,3.803487e-01,3.786022e-01,3.774681e-01,0.983333,0.984076,1.378936e-02,0.976110,0.981605,0.981621,1.456238e-02,0.971601
38,cities__affirmative+disjunction,0.874302,2.039240e-01,2.019980e-01,2.012607e-01,0.920000,0.913043,6.200888e-02,0.864782,0.906015,0.901575,6.242136e-02,0.870892
39,cities__negated+conjunction,0.628615,1.256688e-01,1.276570e-01,1.258128e-01,0.930000,0.939828,4.939174e-02,0.909276,0.926065,0.929172,5.756781e-02,0.886600
40,cities__affirmative+negated+conjunction+disjun...,0.751458,1.131659e-01,1.183838e-01,1.180848e-01,0.891000,0.899724,7.653691e-02,0.863456,0.865163,0.870983,8.988929e-02,0.840710
41,element_symb__affirmative+negated,0.471336,1.768124e-01,1.959989e-01,1.974226e-01,0.986842,0.987342,1.476023e-02,0.972173,0.959459,0.960784,3.085962e-02,0.954207
42,element_symb__affirmative+disjunction,0.322182,2.541350e-02,3.067232e-02,3.052880e-02,0.840580,0.851351,1.039167e-01,0.806696,0.843066,0.848057,1.078788e-01,0.784090
43,element_symb__negated+conjunction,0.395314,1.584398e-01,1.283977e-01,1.277602e-01,0.891304,0.896552,8.803703e-02,0.847493,0.906934,0.918138,6.595096e-02,0.888005
44,element_symb__affirmative+negated+conjunction+...,0.358748,4.414859e-02,3.996578e-02,4.002296e-02,0.804348,0.812500,1.324841e-01,0.739445,0.814781,0.819556,1.243532e-01,0.755632
45,facts__affirmative+negated,0.060664,5.364384e-02,4.356713e-02,4.226291e-02,0.787611,0.811024,1.386779e-01,0.765212,0.844866,0.852285,1.077000e-01,0.782647
46,facts__affirmative+disjunction,0.055544,2.839450e-02,2.716368e-02,2.710478e-02,0.788732,0.798206,1.572402e-01,0.704486,0.768868,0.753769,1.613407e-01,0.679229
47,facts__negated+conjunction,0.031871,2.251311e-02,1.294852e-02,1.317613e-02,0.661972,0.669725,2.013792e-01,0.581925,0.742925,0.759382,1.715787e-01,0.629935
48,facts__affirmative+negated+conjunction+disjunc...,0.043708,2.225074e-02,1.678023e-02,1.706678e-02,0.708920,0.718182,1.832747e-01,0.649696,0.747052,0.751016,1.631878e-01,0.668476
49,inventors__affirmative+negated,0.072580,4.958832e-02,4.507503e-02,4.572443e-02,0.829268,0.829268,1.245958e-01,0.744966,0.830247,0.826498,1.359260e-01,0.731713
50,inventors__affirmative+disjunction,0.035606,1.016311e-02,8.969028e-03,8.869333e-03,0.736264,0.762376,1.608515e-01,0.695569,0.766575,0.771930,1.627316e-01,0.681231
51,inventors__negated+conjunction,0.054885,4.034714e-02,4.136835e-02,4.150045e-02,0.675824,0.725581,2.141323e-01,0.583113,0.647790,0.698225,2.191090e-01,0.569212
52,inventors__affirmative+negated+conjunction+dis...,0.045245,1.717407e-02,1.567208e-02,1.575162e-02,0.692308,0.738318,2.098124e-01,0.603974,0.652624,0.690080,2.149256e-01,0.583715
53,sp_en_trans__affirmative+negated,0.721350,2.160448e-01,2.094281e-01,2.005184e-01,0.971831,0.975309,2.340497e-02,0.960256,0.971731,0.971326,1.558442e-02,0.958855
54,sp_en_trans__affirmative+disjunction,0.409660,5.649454e-02,5.059661e-02,4.968711e-02,0.801170,0.817204,1.244469e-01,0.787459,0.828697,0.822995,1.080418e-01,0.785671
55,sp_en_trans__negated+conjunction,0.519915,1.346869e-01,1.178831e-01,1.173058e-01,0.953216,0.953488,3.660722e-02,0.930899,0.956076,0.959350,3.132679e-02,0.941975
56,sp_en_trans__affirmative+negated+conjunction+d...,0.464788,7.256485e-02,5.993876e-02,5.999693e-02,0.827485,0.822823,1.349240e-01,0.732068,0.841874,0.837349,1.220694e-01,0.752624
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.088655,8.594724e-02,4.916947e-02,6.062967e-02,0.807692,0.814815,1.229308e-01,0.829563,0.950495,0.958678,4.795936e-02,0.911356
58,animal_class+facts+inventors__affirmative+nega...,0.232722,2.317787e-02,2.236908e-02,2.232274e-02,0.750000,0.769231,1.661825e-01,0.687835,0.764471,0.779577,1.603947e-01,0.688521
59,animal_class+facts+inventors__affirmative+nega...,0.213619,1.702797e-02,1.806127e-02,1.802021e-02,0.805430,0.819517,1.450034e-01,0.711798,0.787832,0.797455,1.535762e-01,0.695825

In [15]:
lyr18_eval_except_test_df.describe()

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,6.000000e+01,6.000000e+01,6.000000e+01,60.000000,58.000000,6.000000e+01,58.000000,60.000000,58.000000,6.000000e+01,58.000000
mean,0.330176,1.372271e-01,1.364919e-01,1.329416e-01,0.836446,0.855520,1.083910e-01,0.803688,0.824882,0.848516,1.098008e-01,0.804177
std,0.345483,1.515392e-01,1.602267e-01,1.534566e-01,0.122719,0.104755,7.179553e-02,0.132683,0.151645,0.117282,7.665211e-02,0.129689
min,0.000000,-1.319963e-07,-2.674763e-07,-7.574867e-08,0.500000,0.631579,9.240658e-19,0.581925,0.250000,0.400000,6.743369e-25,0.569212
25%,0.053991,2.440788e-02,2.047025e-02,2.076840e-02,0.746090,0.764090,3.616558e-02,0.699319,0.747367,0.762519,4.509263e-02,0.683053
50%,0.273841,5.709103e-02,5.012590e-02,5.049721e-02,0.828377,0.835687,1.234197e-01,0.796039,0.842470,0.850049,1.084775e-01,0.783369
75%,0.466425,2.443653e-01,2.149331e-01,2.190491e-01,0.954912,0.962054,1.621842e-01,0.931945,0.946431,0.955738,1.628457e-01,0.918990
max,1.690080,6.311205e-01,6.175942e-01,6.166543e-01,1.000000,1.000000,2.412132e-01,1.000000,1.000000,1.000000,2.680697e-01,1.000000

In [82]:
lyr18_eval_except_test_affirmative_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__affirmative")]
lyr18_eval_except_test_negated_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__negated")]
lyr18_eval_except_test_conjunction_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__conjunction")]
lyr18_eval_except_test_disjunction_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__disjunction")]
lyr18_eval_except_test_affirmative_and_negated_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__affirmative+negated")]
lyr18_eval_except_test_affirmative_and_disjunction_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__affirmative+disjunction")]
lyr18_eval_except_test_negated_and_conjunction_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__negated+conjunction")]
lyr18_eval_except_test_all_4_variants_scenarios_df = lyr18_eval_except_test_df[lyr18_eval_except_test_df['scenario'].str.endswith("__affirmative+negated+conjunction+disjunction")]
# Using mathematically equivalent difference of means (rather than mean of differences) to get around pandas confusion around mismatched row indexes
affirm_baseline_avg_train_acc = lyr18_eval_except_test_affirmative_scenarios_df["train_acc"].mean()
affirm_baseline_avg_val_acc = lyr18_eval_except_test_affirmative_scenarios_df["val_acc"].mean()
lyr18_affirm_to_neg_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_negated_scenarios_df["train_acc"].mean()
lyr18_affirm_to_neg_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_negated_scenarios_df["val_acc"].mean()
lyr18_affirm_to_conj_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_conjunction_scenarios_df["train_acc"].mean()
lyr18_affirm_to_conj_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_conjunction_scenarios_df["val_acc"].mean()
lyr18_affirm_to_disj_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_disjunction_scenarios_df["train_acc"].mean()
lyr18_affirm_to_disj_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_disjunction_scenarios_df["val_acc"].mean()
lyr18_affirm_to_affirm_neg_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_affirmative_and_negated_scenarios_df["train_acc"].mean()
lyr18_affirm_to_affirm_neg_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_affirmative_and_negated_scenarios_df["val_acc"].mean()
lyr18_affirm_to_affirm_disj_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_affirmative_and_disjunction_scenarios_df["train_acc"].mean()
lyr18_affirm_to_affirm_disj_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_affirmative_and_disjunction_scenarios_df["val_acc"].mean()
lyr18_affirm_to_neg_conj_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_negated_and_conjunction_scenarios_df["train_acc"].mean()
lyr18_affirm_to_neg_conj_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_negated_and_conjunction_scenarios_df["val_acc"].mean()
lyr18_affirm_to_affirm_neg_conj_disj_train_acc_loss = affirm_baseline_avg_train_acc - lyr18_eval_except_test_all_4_variants_scenarios_df["train_acc"].mean()
lyr18_affirm_to_affirm_neg_conj_disj_val_acc_loss = affirm_baseline_avg_val_acc - lyr18_eval_except_test_all_4_variants_scenarios_df["val_acc"].mean()

pd.DataFrame({
    "scenario": ["negated", "conjunction", "disjunction", "affirmative+negated", "affirmative+disjunction", "negated+conjunction", "affirmative+negated+conjunction+disjunction"],
    "train_acc_loss": [lyr18_affirm_to_neg_train_acc_loss, lyr18_affirm_to_conj_train_acc_loss, lyr18_affirm_to_disj_train_acc_loss, lyr18_affirm_to_affirm_neg_train_acc_loss, lyr18_affirm_to_affirm_disj_train_acc_loss, lyr18_affirm_to_neg_conj_train_acc_loss, lyr18_affirm_to_affirm_neg_conj_disj_train_acc_loss],
    "val_acc_loss": [lyr18_affirm_to_neg_val_acc_loss, lyr18_affirm_to_conj_val_acc_loss, lyr18_affirm_to_disj_val_acc_loss, lyr18_affirm_to_affirm_neg_val_acc_loss, lyr18_affirm_to_affirm_disj_val_acc_loss, lyr18_affirm_to_neg_conj_val_acc_loss, lyr18_affirm_to_affirm_neg_conj_disj_val_acc_loss]
})

                                      scenario  train_acc_loss  val_acc_loss
0                                      negated       -0.007461      0.026196
1                                  conjunction        0.030802      0.088120
2                                  disjunction        0.147588      0.164787
3                          affirmative+negated       -0.006603      0.011639
4                      affirmative+disjunction        0.106691      0.124164
5                          negated+conjunction        0.070486      0.099852
6  affirmative+negated+conjunction+disjunction        0.145237      0.159423

In [101]:
lyr18_t_f_sep_and_t_p_dirs_correlations = lyr18_eval_except_test_df[['tf_sep', 'train_recon_improv', 'val_recon_improv', 'val_recon_improv_w_val_mean', "val_acc", "train_acc"]].corr()
# fig1, ax = plt.subplots(figsize=(10, 6))
# lyr18_t_f_sep_and_t_p_dirs_correlations_heatmap = ax.imshow(lyr18_t_f_sep_and_t_p_dirs_correlations, cmap="Greys")
# plt.show()
lyr18_t_f_sep_and_t_p_dirs_correlations

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,train_acc
tf_sep,1.000000,0.836358,0.828997,0.830357,0.682296,0.600867
train_recon_improv,0.836358,1.000000,0.990417,0.990186,0.764079,0.689926
val_recon_improv,0.828997,0.990417,1.000000,0.994927,0.758730,0.664601
val_recon_improv_w_val_mean,0.830357,0.990186,0.994927,1.000000,0.762526,0.670064
val_acc,0.682296,0.764079,0.758730,0.762526,1.000000,0.704551
train_acc,0.600867,0.689926,0.664601,0.670064,0.704551,1.000000

In [17]:
lyr25_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.588167,3.649412e-01,4.011835e-01,3.074009e-01,1.000000,1.000000,9.433798e-05,0.994576,0.977099,0.978723,1.966778e-02,0.971843
1,animal_class__conjunction,0.333727,2.480434e-01,2.561188e-01,2.589435e-01,0.910000,0.914286,7.965539e-02,0.828664,0.872500,0.874074,9.711317e-02,0.810543
2,animal_class__disjunction,0.030490,2.746382e-02,3.780474e-02,3.551936e-02,0.660000,0.613636,1.952025e-01,0.568776,0.695000,0.700980,2.004607e-01,0.609305
3,animal_class__negated,0.254506,1.976709e-01,2.269427e-01,2.214103e-01,1.000000,1.000000,6.929559e-03,0.978662,0.969466,0.970149,3.020680e-02,0.955813
4,cities__affirmative,1.406146,5.851733e-01,5.821817e-01,5.810651e-01,0.983333,0.982578,1.193676e-02,0.976074,0.986622,0.986864,1.085203e-02,0.978052
5,cities__conjunction,0.284483,2.180753e-01,2.351196e-01,2.340712e-01,0.930000,0.938416,5.544058e-02,0.897317,0.913189,0.917065,6.533412e-02,0.876005
6,cities__disjunction,0.077865,7.738798e-02,4.914201e-02,5.073094e-02,0.640000,0.632653,1.998048e-01,0.583376,0.747500,0.730667,1.817614e-01,0.610717
7,cities__negated,0.428149,2.984820e-01,3.051164e-01,2.961668e-01,0.953333,0.960000,2.757172e-02,0.944702,0.944816,0.945813,4.119287e-02,0.920867
8,element_symb__affirmative,0.385225,2.695421e-01,3.163138e-01,3.262626e-01,0.973684,0.975610,2.965148e-02,0.945144,0.912162,0.918239,6.299112e-02,0.904907
9,element_symb__conjunction,0.280702,2.247273e-01,2.039327e-01,2.055544e-01,0.850000,0.859813,9.269687e-02,0.821420,0.895000,0.910256,7.776561e-02,0.858750
10,element_symb__disjunction,0.101869,9.261090e-02,9.222718e-02,9.210908e-02,0.770000,0.785047,1.677429e-01,0.702310,0.757500,0.750643,1.686156e-01,0.671521
11,element_symb__negated,0.118579,1.107324e-01,8.482091e-02,8.756393e-02,1.000000,1.000000,3.790091e-27,1.000000,1.000000,1.000000,1.161833e-14,1.000000
12,facts__affirmative,0.060569,6.017013e-02,4.325887e-02,4.013136e-02,0.769912,0.816901,1.499897e-01,0.745699,0.783482,0.800000,1.458184e-01,0.728273
13,facts__conjunction,0.023507,2.421945e-02,1.565483e-02,1.487228e-02,0.780000,0.775510,1.641989e-01,0.644065,0.755000,0.775229,1.622277e-01,0.680633
14,facts__disjunction,0.015652,1.430321e-02,1.807144e-02,1.828032e-02,0.740000,0.704545,1.892708e-01,0.604824,0.665000,0.627778,2.108675e-01,0.585649
15,facts__negated,0.011196,1.173250e-02,6.702047e-03,6.779090e-03,0.743363,0.760331,1.692529e-01,0.680873,0.814732,0.819172,1.370104e-01,0.713910
16,inventors__affirmative,0.028233,2.957355e-02,1.377850e-02,1.454122e-02,0.634146,0.651163,2.100852e-01,0.636837,0.706790,0.704050,1.887885e-01,0.648495
17,inventors__conjunction,0.016118,1.717506e-02,7.984143e-03,8.650668e-03,0.650000,0.700855,2.187300e-01,0.626351,0.722500,0.753880,1.943163e-01,0.631793
18,inventors__disjunction,0.006412,6.618306e-03,4.956654e-03,4.401128e-03,0.640000,0.666667,2.176724e-01,0.608711,0.642500,0.653753,2.101950e-01,0.591201
19,inventors__negated,0.032806,3.594561e-02,9.481063e-03,1.112343e-02,0.621951,0.523077,2.440336e-01,0.493223,0.728395,0.685714,1.885650e-01,0.597611
20,ambiguous_lie,0.053311,6.500397e-08,5.883039e-07,-7.470586e-08,0.500000,NaN,2.003167e-01,NaN,0.571429,NaN,2.656892e-01,NaN
21,ambiguous_truthful_reply,0.053311,1.299436e-07,-2.124053e-07,0.000000e+00,0.800000,0.888889,2.169776e-01,0.697194,0.444444,0.615385,2.530501e-01,0.666735
22,honest_reply_despite_incentive_to_lie,0.000000,-8.239608e-08,0.000000e+00,1.181275e-07,0.500000,0.666667,2.486124e-01,0.669204,0.750000,0.857143,2.516316e-01,0.666752
23,unambiguous_lie,0.071157,7.875588e-08,-8.695793e-08,9.851908e-08,0.500000,NaN,2.471301e-01,NaN,0.435897,NaN,2.502127e-01,NaN
24,unambiguous_truthful_reply,0.071157,6.266302e-08,0.000000e+00,8.009028e-08,0.272727,0.428571,2.536726e-01,0.663523,0.431818,0.603175,2.503446e-01,0.666657
25,larger_than,0.274207,2.141040e-01,2.191870e-01,2.189815e-01,0.954545,0.954774,3.357989e-02,0.936795,0.958333,0.960337,2.941358e-02,0.944223
26,smaller_than,0.234721,1.929585e-01,1.784094e-01,1.752719e-01,0.921717,0.930337,6.197086e-02,0.885670,0.928030,0.930147,5.912147e-02,0.878934
27,sp_en_trans__negated,0.507973,3.407284e-01,3.245184e-01,3.271965e-01,1.000000,1.000000,9.884852e-06,0.999556,0.992933,0.992908,6.999399e-03,0.992816
28,sp_en_trans__affirmative,0.766253,4.286215e-01,4.563926e-01,4.038138e-01,0.985915,0.988764,1.151348e-02,0.977109,0.971731,0.970803,2.502351e-02,0.959947
29,sp_en_trans__conjunction,0.333990,2.493014e-01,2.580150e-01,2.558037e-01,0.920000,0.921569,5.175861e-02,0.904863,0.952500,0.957871,3.470141e-02,0.927288
30,sp_en_trans__disjunction,0.046375,4.974986e-02,2.281293e-02,2.155592e-02,0.680000,0.600000,2.031341e-01,0.575317,0.745000,0.719780,1.661407e-01,0.644891
31,common_claim_true_false,0.011256,1.066474e-02,1.269335e-02,1.271016e-02,0.738202,0.746464,1.733994e-01,0.647319,0.713764,0.715443,1.879453e-01,0.629726
32,counterfact_true_false,0.006431,6.421208e-03,6.243058e-03,6.242862e-03,0.648365,0.669315,2.159329e-01,0.575354,0.644285,0.666838,2.147054e-01,0.578437
33,animal_class__affirmative+negated,0.421336,2.310395e-01,2.937793e-01,2.763326e-01,0.984848,0.983051,1.678746e-02,0.967929,0.973282,0.974545,1.937401e-02,0.967774
34,animal_class__affirmative+disjunction,0.309329,3.112807e-02,2.122509e-02,1.699579e-02,0.751880,0.666667,1.711332e-01,0.573242,0.693032,0.674651,1.876073e-01,0.628148
35,animal_class__negated+conjunction,0.294116,1.182459e-01,1.149200e-01,1.151456e-01,0.894737,0.904110,7.056064e-02,0.876168,0.907721,0.910092,6.750447e-02,0.874659
36,animal_class__affirmative+negated+conjunction+...,0.301722,4.912116e-02,5.081535e-02,5.054644e-02,0.714286,0.672414,1.708738e-01,0.653357,0.700565,0.672840,1.814867e-01,0.658516
37,cities__affirmative+negated,0.917148,3.440835e-01,3.494877e-01,3.488409e-01,0.953333,0.956790,3.580836e-02,0.933273,0.935619,0.938449,4.553642e-02,0.916713
38,cities__affirmative+disjunction,0.742006,2.089672e-01,2.068474e-01,2.060909e-01,0.867500,0.852368,7.983817e-02,0.818254,0.879073,0.870383,8.107951e-02,0.829360
39,cities__negated+conjunction,0.356316,9.978609e-02,1.028655e-01,1.011307e-01,0.916667,0.925816,6.428952e-02,0.883391,0.903091,0.904918,7.278257e-02,0.857471
40,cities__affirmative+negated+conjunction+disjun...,0.549161,1.038561e-01,1.095188e-01,1.092212e-01,0.861000,0.871415,9.937463e-02,0.813847,0.838346,0.844691,1.135132e-01,0.788325
41,element_symb__affirmative+negated,0.251902,1.212654e-01,1.339535e-01,1.355060e-01,0.947368,0.951220,3.593871e-02,0.931580,0.945946,0.948387,4.882997e-02,0.915296
42,element_symb__affirmative+disjunction,0.243547,2.222870e-02,2.883926e-02,2.845934e-02,0.768116,0.786667,1.705870e-01,0.676340,0.704380,0.694340,1.927492e-01,0.627430
43,element_symb__negated+conjunction,0.199640,9.875703e-02,7.888846e-02,7.891204e-02,0.818841,0.832215,1.130328e-01,0.781397,0.872263,0.889590,8.977219e-02,0.831470
44,element_symb__affirmative+negated+conjunction+...,0.221594,2.692761e-02,2.134994e-02,2.142082e-02,0.760870,0.772414,1.655345e-01,0.676647,0.758212,0.764444,1.542000e-01,0.699045
45,facts__affirmative+negated,0.035883,3.404237e-02,2.308774e-02,2.182429e-02,0.747788,0.774704,1.733424e-01,0.676260,0.783482,0.792735,1.559641e-01,0.676748
46,facts__affirmative+disjunction,0.038110,2.066776e-02,2.068299e-02,2.064851e-02,0.685446,0.673171,2.044741e-01,0.604037,0.675708,0.640523,2.038644e-01,0.582256
47,facts__negated+conjunction,0.017352,1.202074e-02,8.362271e-03,8.483914e-03,0.741784,0.746544,1.909363e-01,0.619889,0.734670,0.746336,1.754862e-01,0.650354
48,facts__affirmative+negated+conjunction+disjunc...,0.027731,1.380154e-02,1.222099e-02,1.243512e-02,0.683099,0.685315,2.024529e-01,0.600473,0.702830,0.698925,1.939521e-01,0.604142
49,inventors__affirmative+negated,0.030519,2.606403e-02,1.239650e-02,1.383055e-02,0.731707,0.728395,1.826679e-01,0.631485,0.745370,0.725458,1.740212e-01,0.641401
50,inventors__affirmative+disjunction,0.017323,5.965794e-03,2.599023e-03,2.713365e-03,0.576923,0.620690,2.254370e-01,0.590835,0.643646,0.685366,2.130755e-01,0.589188
51,inventors__negated+conjunction,0.024462,2.622788e-02,2.300379e-02,2.344006e-02,0.681319,0.715686,2.271971e-01,0.561221,0.650552,0.684145,2.320744e-01,0.544183
52,inventors__affirmative+negated+conjunction+dis...,0.020892,1.014814e-02,6.477528e-03,6.785889e-03,0.607143,0.641604,2.346848e-01,0.562086,0.593923,0.617188,2.330289e-01,0.546984
53,sp_en_trans__affirmative+negated,0.637113,1.738590e-01,1.621996e-01,1.536014e-01,0.943662,0.950617,4.520201e-02,0.919443,0.946996,0.947368,4.428508e-02,0.908614
54,sp_en_trans__affirmative+disjunction,0.406314,4.894242e-02,3.840607e-02,3.760650e-02,0.795322,0.816754,1.320057e-01,0.767865,0.806735,0.807018,1.244082e-01,0.754493
55,sp_en_trans__negated+conjunction,0.420982,8.498504e-02,6.820703e-02,6.769840e-02,0.959064,0.958580,2.222867e-02,0.951210,0.975110,0.976356,1.856554e-02,0.962133
56,sp_en_trans__affirmative+negated+conjunction+d...,0.413648,5.025428e-02,3.367015e-02,3.370361e-02,0.736842,0.711538,1.616360e-01,0.673184,0.751098,0.731013,1.472147e-01,0.697281
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.065208,6.084656e-02,1.764589e-02,2.460461e-02,0.807692,0.814815,1.462860e-01,0.712942,0.861386,0.877193,1.149274e-01,0.779588
58,animal_class+facts+inventors__affirmative+nega...,0.149870,1.348219e-02,1.450066e-02,1.446919e-02,0.694444,0.719320,1.892812e-01,0.630639,0.699933,0.716352,1.911026e-01,0.622918
59,animal_class+facts+inventors__affirmative+nega...,0.128825,8.884766e-03,9.284597e-03,9.260300e-03,0.713801,0.733404,2.026228e-01,0.629952,0.709687,0.720622,2.093247e-01,0.616953

In [18]:
lyr25_eval_except_test_df.describe()

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,6.000000e+01,6.000000e+01,6.000000e+01,60.000000,58.000000,6.000000e+01,58.000000,60.000000,58.000000,6.000000e+01,58.000000
mean,0.235943,1.075456e-01,1.059050e-01,1.029477e-01,0.783611,0.802116,1.347030e-01,0.750525,0.790368,0.809428,1.345743e-01,0.752996
std,0.268247,1.271151e-01,1.345939e-01,1.288299e-01,0.155743,0.140303,8.139284e-02,0.152109,0.143905,0.123342,7.883947e-02,0.144177
min,0.000000,-8.239608e-08,-2.124053e-07,-7.470586e-08,0.272727,0.428571,3.790091e-27,0.493223,0.431818,0.603175,1.161833e-14,0.544183
25%,0.030512,1.417779e-02,1.235262e-02,1.264140e-02,0.682654,0.689200,5.452009e-02,0.627251,0.702264,0.701748,6.202370e-02,0.628542
50%,0.139348,4.943551e-02,3.573745e-02,3.461149e-02,0.769014,0.785857,1.666387e-01,0.689034,0.757856,0.796368,1.550820e-01,0.698163
75%,0.339572,1.941366e-01,1.847902e-01,1.828425e-01,0.923788,0.936397,2.024954e-01,0.902976,0.916899,0.927170,1.940431e-01,0.898414
max,1.406146,5.851733e-01,5.821817e-01,5.810651e-01,1.000000,1.000000,2.536726e-01,1.000000,1.000000,1.000000,2.656892e-01,1.000000

In [66]:
lyr25_t_f_sep_and_t_p_dirs_correlations = lyr25_eval_except_test_df[['tf_sep', 'train_recon_improv', 'val_recon_improv', 'val_recon_improv_w_val_mean']].corr()
lyr25_t_f_sep_and_t_p_dirs_correlations

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean
tf_sep,1.000000,0.851259,0.839678,0.842292
train_recon_improv,0.851259,1.000000,0.992763,0.991248
val_recon_improv,0.839678,0.992763,1.000000,0.995207
val_recon_improv_w_val_mean,0.842292,0.991248,0.995207,1.000000

In [20]:
lyrs18_and_25_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.730812,0.376432,4.167493e-01,3.190759e-01,1.000000,1.000000,1.048590e-05,0.999071,0.961832,0.965035,3.823655e-02,0.963365
1,animal_class__conjunction,0.324344,0.247242,2.536601e-01,2.566432e-01,0.890000,0.899083,7.981698e-02,0.856313,0.892500,0.896882,7.976444e-02,0.846770
2,animal_class__disjunction,0.029893,0.027450,3.721342e-02,3.495434e-02,0.690000,0.666667,2.067646e-01,0.549148,0.637500,0.650602,2.167152e-01,0.576844
3,animal_class__negated,0.416986,0.219127,2.507378e-01,2.446228e-01,0.969697,0.974359,1.444203e-02,0.974813,0.969466,0.970149,2.588530e-02,0.959980
4,cities__affirmative,1.548113,0.590800,5.865278e-01,5.854327e-01,0.980000,0.979167,1.512385e-02,0.970972,0.988294,0.988543,1.162213e-02,0.975314
5,cities__conjunction,0.336618,0.224548,2.425223e-01,2.414631e-01,0.940000,0.947059,5.112365e-02,0.910267,0.913189,0.917722,6.478866e-02,0.885512
6,cities__disjunction,0.068194,0.074966,4.874871e-02,5.021835e-02,0.740000,0.723404,1.693977e-01,0.655712,0.750000,0.740933,1.643413e-01,0.666838
7,cities__negated,0.648312,0.315151,3.227825e-01,3.135470e-01,0.976667,0.979592,1.335644e-02,0.972899,0.967391,0.967033,2.275182e-02,0.956171
8,element_symb__affirmative,0.481369,0.279506,3.310533e-01,3.412581e-01,0.973684,0.975610,2.586430e-02,0.950555,0.918919,0.924051,5.816379e-02,0.905209
9,element_symb__conjunction,0.353086,0.236666,2.145218e-01,2.158086e-01,0.870000,0.876190,8.621970e-02,0.839991,0.897500,0.911447,7.613172e-02,0.870363
10,element_symb__disjunction,0.084360,0.088819,8.905924e-02,8.895693e-02,0.780000,0.792453,1.731925e-01,0.661480,0.752500,0.750630,1.713014e-01,0.637860
11,element_symb__negated,0.241868,0.127870,9.768481e-02,1.007462e-01,1.000000,1.000000,3.631470e-22,1.000000,1.000000,1.000000,4.758516e-22,1.000000
12,facts__affirmative,0.076891,0.063410,4.671065e-02,4.342653e-02,0.814159,0.846715,1.204582e-01,0.775369,0.814732,0.827443,1.325435e-01,0.743538
13,facts__conjunction,0.029567,0.025842,1.640895e-02,1.576277e-02,0.710000,0.723810,1.850697e-01,0.611237,0.780000,0.804444,1.579917e-01,0.671479
14,facts__disjunction,0.016764,0.014617,1.832306e-02,1.855864e-02,0.720000,0.674419,1.893128e-01,0.594273,0.692500,0.645533,2.043912e-01,0.585283
15,facts__negated,0.019656,0.013732,8.300493e-03,8.401126e-03,0.752212,0.762712,1.481725e-01,0.729915,0.848214,0.851528,1.157284e-01,0.767327
16,inventors__affirmative,0.044059,0.032038,1.724613e-02,1.796282e-02,0.646341,0.666667,1.977272e-01,0.644556,0.679012,0.666667,1.850799e-01,0.649348
17,inventors__conjunction,0.020307,0.018100,9.087952e-03,9.740391e-03,0.670000,0.727273,2.217227e-01,0.637477,0.712500,0.742729,1.870549e-01,0.649201
18,inventors__disjunction,0.008869,0.007250,5.037946e-03,4.478343e-03,0.660000,0.696429,2.114068e-01,0.615934,0.675000,0.693396,2.074786e-01,0.594165
19,inventors__negated,0.059040,0.040392,1.316852e-02,1.465443e-02,0.560976,0.538462,2.276440e-01,0.523383,0.679012,0.653333,2.032593e-01,0.552610
20,ambiguous_lie,0.052309,0.000000,-3.878537e-07,6.746208e-08,0.500000,NaN,2.491555e-01,NaN,0.357143,NaN,2.500906e-01,NaN
21,ambiguous_truthful_reply,0.052309,0.000000,9.594764e-08,1.294894e-07,0.400000,0.571429,2.472415e-01,0.673252,0.444444,0.615385,2.513282e-01,0.666654
22,honest_reply_despite_incentive_to_lie,0.000000,0.000000,-8.140490e-08,1.066376e-07,1.000000,1.000000,1.027950e-01,0.817399,0.500000,0.666667,3.327580e-01,0.664517
23,unambiguous_lie,0.089243,0.000000,-3.078042e-07,0.000000e+00,0.800000,NaN,2.487790e-01,NaN,0.512821,NaN,2.500563e-01,NaN
24,unambiguous_truthful_reply,0.089243,0.000000,6.545556e-08,0.000000e+00,0.636364,0.777778,2.480648e-01,0.668427,0.522727,0.686567,2.500595e-01,0.666667
25,larger_than,0.365530,0.227083,2.309441e-01,2.307898e-01,0.967172,0.966921,2.803952e-02,0.944715,0.960859,0.962696,3.030396e-02,0.944751
26,smaller_than,0.291107,0.201326,1.889082e-01,1.857684e-01,0.944444,0.951111,4.447663e-02,0.920616,0.946338,0.948076,3.711441e-02,0.921277
27,sp_en_trans__negated,0.593574,0.352762,3.367341e-01,3.394803e-01,1.000000,1.000000,0.000000e+00,1.000000,0.992933,0.992908,7.067138e-03,0.992908
28,sp_en_trans__affirmative,0.764889,0.428075,4.579815e-01,4.057482e-01,0.985915,0.988764,8.304221e-03,0.983670,0.975265,0.974170,1.586142e-02,0.967787
29,sp_en_trans__conjunction,0.347323,0.252539,2.609013e-01,2.587486e-01,0.910000,0.912621,5.324913e-02,0.908213,0.950000,0.955752,3.266276e-02,0.933669
30,sp_en_trans__disjunction,0.051085,0.050818,2.492399e-02,2.368459e-02,0.720000,0.681818,1.853800e-01,0.620151,0.765000,0.744565,1.523729e-01,0.676091
31,common_claim_true_false,0.014099,0.011225,1.334179e-02,1.335970e-02,0.746067,0.753813,1.705093e-01,0.647091,0.716573,0.719020,1.849938e-01,0.630260
32,counterfact_true_false,0.009540,0.007145,6.934422e-03,6.933936e-03,0.667449,0.677879,2.070386e-01,0.589363,0.664777,0.677210,2.067304e-01,0.591837
33,animal_class__affirmative+negated,0.573899,0.243376,3.042069e-01,2.857524e-01,0.984848,0.983051,1.641124e-02,0.973967,0.977099,0.978102,1.733593e-02,0.975200
34,animal_class__affirmative+disjunction,0.380353,0.031573,2.324250e-02,1.888703e-02,0.676692,0.505747,1.928114e-01,0.527331,0.651601,0.570766,1.996672e-01,0.601834
35,animal_class__negated+conjunction,0.370665,0.119292,1.154142e-01,1.155958e-01,0.909774,0.918919,6.692390e-02,0.881437,0.903955,0.907104,6.366233e-02,0.879970
36,animal_class__affirmative+negated+conjunction+...,0.375509,0.049828,5.133375e-02,5.104955e-02,0.721805,0.678261,1.653051e-01,0.662606,0.701507,0.673532,1.749482e-01,0.667494
37,cities__affirmative+negated,1.098213,0.348623,3.530811e-01,3.523741e-01,0.963333,0.965625,3.053823e-02,0.943546,0.948579,0.950263,3.909004e-02,0.928093
38,cities__affirmative+disjunction,0.808154,0.208314,2.062135e-01,2.054593e-01,0.857500,0.840336,8.387524e-02,0.817318,0.879699,0.871658,7.819608e-02,0.831894
39,cities__negated+conjunction,0.492465,0.102916,1.058432e-01,1.040960e-01,0.926667,0.935860,5.163525e-02,0.909466,0.918129,0.920776,6.175595e-02,0.885123
40,cities__affirmative+negated+conjunction+disjun...,0.650309,0.105041,1.106453e-01,1.103473e-01,0.871000,0.879552,9.344633e-02,0.825923,0.846867,0.852165,1.069703e-01,0.801253
41,element_symb__affirmative+negated,0.361619,0.128200,1.417082e-01,1.432608e-01,0.947368,0.951220,3.112758e-02,0.941691,0.952703,0.954545,4.448311e-02,0.926113
42,element_symb__affirmative+disjunction,0.282865,0.022589,2.904992e-02,2.869749e-02,0.753623,0.753623,1.749970e-01,0.671189,0.757299,0.747628,1.621564e-01,0.680277
43,element_symb__negated+conjunction,0.297477,0.106490,8.543135e-02,8.536934e-02,0.833333,0.845638,1.084417e-01,0.797521,0.879562,0.895899,8.495046e-02,0.845944
44,element_symb__affirmative+negated+conjunction+...,0.290171,0.028869,2.349190e-02,2.356160e-02,0.742754,0.743682,1.682252e-01,0.677976,0.746350,0.743068,1.567635e-01,0.700789
45,facts__affirmative+negated,0.048273,0.036374,2.546617e-02,2.419861e-02,0.694690,0.711297,2.078405e-01,0.636289,0.674107,0.680525,2.165161e-01,0.627211
46,facts__affirmative+disjunction,0.046827,0.021649,2.148968e-02,2.145191e-02,0.690141,0.670000,1.980803e-01,0.618786,0.683962,0.642667,1.971686e-01,0.597043
47,facts__negated+conjunction,0.024611,0.013329,8.919930e-03,9.054577e-03,0.723005,0.725581,1.838209e-01,0.633874,0.773585,0.786192,1.634185e-01,0.670525
48,facts__affirmative+negated+conjunction+disjunc...,0.035719,0.014869,1.278493e-02,1.300787e-02,0.706573,0.708625,1.954480e-01,0.618070,0.719929,0.717430,1.850207e-01,0.624169
49,inventors__affirmative+negated,0.051550,0.028507,1.579594e-02,1.715225e-02,0.756098,0.753086,1.698943e-01,0.656334,0.765432,0.745819,1.655079e-01,0.662123
50,inventors__affirmative+disjunction,0.026464,0.006453,3.337304e-03,3.427257e-03,0.637363,0.685714,2.101495e-01,0.621952,0.696133,0.738095,1.957986e-01,0.623715
51,inventors__negated+conjunction,0.039674,0.027966,2.529709e-02,2.569605e-02,0.664835,0.693467,2.251347e-01,0.566759,0.629834,0.658163,2.314752e-01,0.548751
52,inventors__affirmative+negated+conjunction+dis...,0.033069,0.011005,7.604439e-03,7.885243e-03,0.609890,0.646766,2.317923e-01,0.567178,0.596685,0.621762,2.306985e-01,0.551868
53,sp_en_trans__affirmative+negated,0.679232,0.180261,1.693949e-01,1.607487e-01,0.943662,0.950617,3.961941e-02,0.930347,0.950530,0.950704,3.741187e-02,0.921340
54,sp_en_trans__affirmative+disjunction,0.407987,0.050064,4.018475e-02,3.936839e-02,0.742690,0.752809,1.502128e-01,0.731752,0.802343,0.791345,1.260725e-01,0.734614
55,sp_en_trans__negated+conjunction,0.470449,0.091876,7.510325e-02,7.457987e-02,0.964912,0.964286,2.174961e-02,0.954880,0.973646,0.974930,1.923370e-02,0.965082
56,sp_en_trans__affirmative+negated+conjunction+d...,0.439218,0.053440,3.738981e-02,3.742623e-02,0.754386,0.732484,1.590001e-01,0.685282,0.762079,0.745497,1.441755e-01,0.710124
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.076932,0.063350,2.100165e-02,2.843561e-02,0.846154,0.857143,1.347483e-01,0.762924,0.900990,0.915254,8.372632e-02,0.843558
58,animal_class+facts+inventors__affirmative+nega...,0.191296,0.014626,1.542448e-02,1.539118e-02,0.720899,0.746089,1.812848e-01,0.648037,0.717232,0.736679,1.832371e-01,0.640655
59,animal_class+facts+inventors__affirmative+nega...,0.171222,0.009766,1.022900e-02,1.020268e-02,0.657805,0.697046,2.217134e-01,0.648042,0.660190,0.693528,2.297797e-01,0.634425

In [21]:
lyrs18_and_25_eval_except_test_df.describe()

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,60.000000,6.000000e+01,60.000000,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000,6.000000e+01,58.000000
mean,0.283060,0.111226,1.097550e-01,0.106712,0.798716,0.810840,0.130735,0.761323,0.788483,0.809917,1.320642e-01,0.761945
std,0.304332,0.129781,1.374956e-01,0.131577,0.143433,0.135400,0.081962,0.152587,0.153608,0.127705,8.283937e-02,0.146435
min,0.000000,0.000000,-3.878537e-07,0.000000,0.400000,0.505747,0.000000,0.523383,0.357143,0.570766,4.758516e-22,0.548751
25%,0.046135,0.014808,1.329847e-02,0.014331,0.693553,0.699940,0.049462,0.636586,0.682725,0.693429,5.474362e-02,0.638559
50%,0.216582,0.050441,3.730162e-02,0.036190,0.755242,0.770245,0.162153,0.707598,0.769509,0.788768,1.545682e-01,0.705456
75%,0.410237,0.203073,1.932345e-01,0.190691,0.943858,0.950988,0.197815,0.918028,0.925774,0.942069,1.977933e-01,0.917260
max,1.548113,0.590800,5.865278e-01,0.585433,1.000000,1.000000,0.249156,1.000000,1.000000,1.000000,3.327580e-01,1.000000

In [67]:
lyrs18_and_25_t_f_sep_and_t_p_dirs_correlations = lyrs18_and_25_eval_except_test_df[['tf_sep', 'train_recon_improv', 'val_recon_improv', 'val_recon_improv_w_val_mean']].corr()
lyrs18_and_25_t_f_sep_and_t_p_dirs_correlations

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean
tf_sep,1.000000,0.857080,0.848689,0.851512
train_recon_improv,0.857080,1.000000,0.992773,0.991497
val_recon_improv,0.848689,0.992773,1.000000,0.995109
val_recon_improv_w_val_mean,0.851512,0.991497,0.995109,1.000000

In [23]:
# lyr25_rel_to_18_eval_except_test_df

In [60]:
numeric_cols_in_25_rel_to_18_df = lyr25_rel_to_18_eval_except_test_df.columns[1:]
numeric_higher_better_cols_in_25_rel_to_18_df = numeric_cols_in_25_rel_to_18_df[~numeric_cols_in_25_rel_to_18_df.str.contains("brier")]
numeric_lower_better_cols_in_25_rel_to_18_df = numeric_cols_in_25_rel_to_18_df[numeric_cols_in_25_rel_to_18_df.str.contains("brier")]
noteworthy_rows_mask_25_rel_to_18_df = pd.concat([(lyr25_rel_to_18_eval_except_test_df[numeric_higher_better_cols_in_25_rel_to_18_df] > 0.05), (lyr25_rel_to_18_eval_except_test_df[numeric_lower_better_cols_in_25_rel_to_18_df] < -0.05)], axis=1).any(axis=1)
lyr25_rel_to_18_eval_except_test_df[noteworthy_rows_mask_25_rel_to_18_df]

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
13,facts__conjunction,-0.012120,-1.251708e-02,-5.795836e-03,-6.845959e-03,0.060000,0.044741,-0.022460,-0.006590,-0.035000,-0.039749,0.020944,-0.047058
20,ambiguous_lie,0.002003,1.139251e-08,2.253305e-07,-1.442802e-07,0.000000,NaN,-0.040896,NaN,0.142857,NaN,0.013283,NaN
21,ambiguous_truthful_reply,0.002003,1.953885e-07,-3.117704e-07,0.000000e+00,0.200000,0.138889,0.008279,-0.013446,-0.111111,-0.098901,-0.010221,-0.000752
22,honest_reply_despite_incentive_to_lie,0.000000,4.960024e-08,-2.438925e-07,1.181275e-07,-0.500000,-0.333333,0.178510,-0.178256,0.500000,0.457143,-0.016438,0.002470
47,facts__negated+conjunction,-0.014520,-1.049237e-02,-4.586252e-03,-4.692217e-03,0.079812,0.076819,-0.010443,0.037964,-0.008255,-0.013046,0.003908,0.020419

In [25]:
lyr25_rel_to_18_eval_except_test_df.describe()

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,60.000000,60.000000,60.000000,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000
mean,-0.094233,-0.029681,-0.030587,-0.029994,-0.052835,-0.053404,0.026312,-0.053163,-0.034514,-0.039088,0.024774,-0.051182
std,0.110259,0.042556,0.043171,0.042016,0.099461,0.085328,0.032261,0.047940,0.083837,0.077403,0.021355,0.041399
min,-0.440327,-0.173719,-0.181603,-0.178093,-0.500000,-0.413534,-0.040896,-0.186958,-0.138686,-0.153717,-0.016438,-0.156660
25%,-0.148954,-0.046525,-0.041938,-0.040575,-0.074259,-0.067979,0.009289,-0.080155,-0.079828,-0.075010,0.012993,-0.068526
50%,-0.039116,-0.011505,-0.014278,-0.014233,-0.031917,-0.033001,0.021637,-0.042362,-0.036250,-0.038453,0.020911,-0.048650
75%,-0.011445,-0.005064,-0.004510,-0.004486,-0.004386,-0.009317,0.033742,-0.020141,-0.015200,-0.014313,0.035630,-0.021611
max,0.035019,0.031118,0.026668,0.026374,0.200000,0.138889,0.178510,0.037964,0.500000,0.457143,0.084870,0.020419

In [59]:
numeric_cols_in_18_and_25_rel_to_just_18_df = lyrs18_and_25_rel_to_18_eval_except_test_df.columns[1:]
numeric_higher_better_cols_in_18_and_25_rel_to_just_18_df = numeric_cols_in_18_and_25_rel_to_just_18_df[~numeric_cols_in_18_and_25_rel_to_just_18_df.str.contains("brier")]
numeric_lower_better_cols_in_18_and_25_rel_to_just_18_df = numeric_cols_in_18_and_25_rel_to_just_18_df[numeric_cols_in_18_and_25_rel_to_just_18_df.str.contains("brier")]
noteworthy_rows_mask_18_and_25_rel_to_just_18_df = pd.concat([(lyrs18_and_25_rel_to_18_eval_except_test_df[numeric_higher_better_cols_in_18_and_25_rel_to_just_18_df] > 0.05), (lyrs18_and_25_rel_to_18_eval_except_test_df[numeric_lower_better_cols_in_18_and_25_rel_to_just_18_df] < -0.05)], axis=1).any(axis=1)
lyrs18_and_25_rel_to_18_eval_except_test_df[noteworthy_rows_mask_18_and_25_rel_to_just_18_df]

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
22,honest_reply_despite_incentive_to_lie,0.000000,1.319963e-07,-3.252974e-07,1.066376e-07,0.000000,0.000000,0.032692,-0.030060,0.250000,0.266667,0.064688,0.000234
23,unambiguous_lie,-0.018086,-1.258997e-07,-4.032789e-08,0.000000e+00,0.200000,NaN,0.031118,NaN,-0.025641,NaN,-0.004977,NaN
47,facts__negated+conjunction,-0.007260,-9.184187e-03,-4.028593e-03,-4.121554e-03,0.061033,0.055857,-0.017558,0.051949,0.030660,0.026810,-0.008160,0.040590

In [28]:
lyrs18_and_25_rel_to_18_eval_except_test_df.describe()

,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,60.000000,60.000000,60.000000,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000
mean,-0.047116,-0.026001,-0.026737,-0.026230,-0.037730,-0.044680,0.022344,-0.042365,-0.036399,-0.038598,0.022263,-0.042233
std,0.055130,0.037530,0.037942,0.036970,0.058757,0.055994,0.022806,0.041406,0.056553,0.063225,0.022227,0.038076
min,-0.220163,-0.156582,-0.157808,-0.154881,-0.200000,-0.255315,-0.017558,-0.160064,-0.170759,-0.218424,-0.012093,-0.155436
25%,-0.074477,-0.040943,-0.037373,-0.036140,-0.064574,-0.071590,0.007865,-0.059580,-0.065625,-0.066569,0.010372,-0.059556
50%,-0.019558,-0.010039,-0.012036,-0.012194,-0.028635,-0.029060,0.017034,-0.037295,-0.027575,-0.031504,0.017936,-0.039227
75%,-0.005722,-0.004522,-0.003963,-0.003930,-0.004621,-0.006428,0.031975,-0.014967,-0.013976,-0.011575,0.032574,-0.015916
max,0.017509,0.027326,0.023500,0.023222,0.200000,0.055857,0.090627,0.051949,0.250000,0.266667,0.108816,0.040590

For layer 25 relative to layer 18: with 3 scenarios out of 60 showing a 5+ percentage-point-improvement in validation accuracy while most scenarios show large negative effects on validation accuracy and most statistics, it seems likely that those 3 cases are probably just a result of noise/randomness. This seems especially likely because in those cases the layer25 probe did worse than the layer18 probe on the training set (and in 2 of the 3 cases did worse on the confidence-adjusted f1-like metric).  
For layers 18 & 25 relative to just layer 18: with just 2 scenarios out of 60 showing a positive change in validation accuracy at all while most scenarios show large negative effects on validation accuracy and most statistics, it seems likely that those 2 cases are probably just a result of noise/randomness.  

Incidentally, it's interesting that, for the "layers 18 and 25" probe, gradient descent didn't find the solution of "recover most or all of the performance of the only-layer-18 probe by setting the weights for layer 25 activations to ~0".

Going forward, the layer25 and layers18&25 directions/probes will be largely ignored.

In [29]:
lyr18_baseline_linear_probes_eval_except_test_df

,scenario,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,1.000000,1.000000,4.737931e-15,1.000000,1.000000,1.000000,2.171720e-16,1.000000
1,animal_class__conjunction,0.980000,0.980000,1.438196e-02,0.974614,1.000000,1.000000,4.181327e-04,0.994526
2,animal_class__disjunction,0.790000,0.778947,1.331134e-01,0.719436,0.860000,0.876106,8.851917e-02,0.811538
3,animal_class__negated,1.000000,1.000000,4.370021e-10,0.999997,1.000000,1.000000,7.619170e-16,1.000000
4,cities__affirmative,0.986667,0.986014,1.022535e-02,0.983910,0.992475,0.992605,4.630021e-03,0.988487
5,cities__conjunction,0.986667,0.987730,1.043765e-02,0.982741,1.000000,1.000000,6.578032e-04,0.994488
6,cities__disjunction,0.870000,0.868687,1.144866e-01,0.742273,0.930000,0.930000,6.681901e-02,0.806922
7,cities__negated,0.986667,0.988095,9.586872e-03,0.985873,0.994983,0.994819,3.803460e-03,0.989490
8,element_symb__affirmative,1.000000,1.000000,1.891266e-11,0.999999,1.000000,1.000000,1.771124e-17,1.000000
9,element_symb__conjunction,1.000000,1.000000,8.702983e-10,0.999995,1.000000,1.000000,1.617376e-16,1.000000
10,element_symb__disjunction,0.980000,0.980769,2.572177e-02,0.948162,1.000000,1.000000,1.200666e-03,0.986966
11,element_symb__negated,1.000000,1.000000,3.210423e-04,0.995895,1.000000,1.000000,1.460392e-17,1.000000
12,facts__affirmative,0.955752,0.960000,2.697033e-02,0.955003,0.997768,0.997691,1.257249e-03,0.993596
13,facts__conjunction,0.820000,0.790698,1.233484e-01,0.746431,0.977500,0.977444,3.169205e-02,0.885599
14,facts__disjunction,0.820000,0.812500,1.180682e-01,0.742128,0.952500,0.948509,5.228021e-02,0.825039
15,facts__negated,0.858407,0.859649,1.030634e-01,0.813018,0.968750,0.968889,3.144237e-02,0.899969
16,inventors__affirmative,0.914634,0.929293,6.569698e-02,0.898393,0.938272,0.944444,4.398387e-02,0.899879
17,inventors__conjunction,0.890000,0.910569,7.758649e-02,0.871089,0.985000,0.986784,2.356241e-02,0.924587
18,inventors__disjunction,0.800000,0.843750,1.551561e-01,0.754390,0.907500,0.919740,9.533650e-02,0.792131
19,inventors__negated,0.853659,0.812500,9.715707e-02,0.772859,0.919753,0.909091,5.893136e-02,0.846446
20,ambiguous_lie,1.000000,NaN,1.050118e-24,NaN,1.000000,NaN,1.446902e-24,NaN
21,ambiguous_truthful_reply,1.000000,1.000000,0.000000e+00,1.000000,1.000000,1.000000,0.000000e+00,1.000000
22,honest_reply_despite_incentive_to_lie,1.000000,1.000000,1.421085e-14,1.000000,1.000000,1.000000,7.105427e-15,1.000000
23,unambiguous_lie,1.000000,NaN,1.518638e-24,NaN,1.000000,NaN,1.157558e-24,NaN
24,unambiguous_truthful_reply,1.000000,1.000000,0.000000e+00,1.000000,1.000000,1.000000,0.000000e+00,1.000000
25,larger_than,1.000000,1.000000,1.426665e-05,0.999800,1.000000,1.000000,1.502934e-15,1.000000
26,smaller_than,1.000000,1.000000,3.349663e-05,0.999626,1.000000,1.000000,8.750799e-15,1.000000
27,sp_en_trans__negated,1.000000,1.000000,2.562758e-12,1.000000,1.000000,1.000000,2.515887e-16,1.000000
28,sp_en_trans__affirmative,1.000000,1.000000,8.378279e-08,0.999972,1.000000,1.000000,2.523146e-16,1.000000
29,sp_en_trans__conjunction,1.000000,1.000000,2.664824e-04,0.997272,1.000000,1.000000,3.091911e-17,1.000000
30,sp_en_trans__disjunction,0.990000,0.989011,3.743603e-03,0.993305,1.000000,1.000000,2.741257e-15,1.000000
31,common_claim_true_false,0.811236,0.814159,1.324474e-01,0.732995,0.838764,0.839306,1.165958e-01,0.743862
32,counterfact_true_false,0.826216,0.826920,1.185529e-01,0.766909,0.842400,0.844281,1.073910e-01,0.778638
33,animal_class__affirmative+negated,1.000000,1.000000,3.641339e-07,0.999915,1.000000,1.000000,6.039329e-16,1.000000
34,animal_class__affirmative+disjunction,0.842105,0.803738,1.066825e-01,0.748289,0.890772,0.898246,7.368915e-02,0.839471
35,animal_class__negated+conjunction,0.977444,0.978417,1.068789e-02,0.981544,1.000000,1.000000,2.953050e-04,0.996060
36,animal_class__affirmative+negated+conjunction+...,0.909774,0.904000,6.324344e-02,0.875548,0.944444,0.945822,3.911059e-02,0.914783
37,cities__affirmative+negated,0.985000,0.985554,9.284142e-03,0.985693,0.992893,0.992830,4.429694e-03,0.988979
38,cities__affirmative+disjunction,0.955000,0.953125,3.823327e-02,0.921924,0.974937,0.975217,2.049703e-02,0.944502
39,cities__negated+conjunction,0.986667,0.987952,1.243303e-02,0.981832,0.997076,0.997005,2.545326e-03,0.990748
40,cities__affirmative+negated+conjunction+disjun...,0.971000,0.972302,2.320118e-02,0.957636,0.980451,0.980233,1.428717e-02,0.963197
41,element_symb__affirmative+negated,1.000000,1.000000,1.849128e-03,0.995199,1.000000,1.000000,1.763436e-15,1.000000
42,element_symb__affirmative+disjunction,0.978261,0.979310,1.921232e-02,0.960651,1.000000,1.000000,1.620967e-03,0.986654
43,element_symb__negated+conjunction,0.992754,0.992366,8.176259e-03,0.975870,1.000000,1.000000,1.753441e-03,0.988917
44,element_symb__affirmative+negated+conjunction+...,0.978261,0.978417,1.467793e-02,0.969567,1.000000,1.000000,9.719951e-04,0.991544
45,facts__affirmative+negated,0.871681,0.876596,1.043555e-01,0.811190,0.944196,0.943946,4.724095e-02,0.872309
46,facts__affirmative+disjunction,0.887324,0.891892,7.251821e-02,0.857505,0.987028,0.986233,1.909521e-02,0.918500
47,facts__negated+conjunction,0.830986,0.820000,1.242275e-01,0.755510,0.932783,0.933020,5.948954e-02,0.838461
48,facts__affirmative+negated+conjunction+disjunc...,0.861502,0.858513,1.085148e-01,0.778201,0.920991,0.919082,6.407186e-02,0.831850
49,inventors__affirmative+negated,0.871951,0.871166,8.386829e-02,0.834489,0.899691,0.898911,6.930428e-02,0.848420
50,inventors__affirmative+disjunction,0.846154,0.878261,1.095920e-01,0.826457,0.915746,0.926061,6.958865e-02,0.847062
51,inventors__negated+conjunction,0.873626,0.877005,8.702927e-02,0.826027,0.955801,0.956757,4.640511e-02,0.877578
52,inventors__affirmative+negated+conjunction+dis...,0.857143,0.875598,1.007724e-01,0.822551,0.912293,0.918953,6.555394e-02,0.850173
53,sp_en_trans__affirmative+negated,1.000000,1.000000,1.670350e-07,0.999967,1.000000,1.000000,3.035009e-16,1.000000
54,sp_en_trans__affirmative+disjunction,0.994152,0.994413,2.782293e-03,0.994445,1.000000,1.000000,3.170199e-06,0.999439
55,sp_en_trans__negated+conjunction,1.000000,1.000000,1.023078e-04,0.998664,1.000000,1.000000,7.771587e-16,1.000000
56,sp_en_trans__affirmative+negated+conjunction+d...,0.997076,0.997085,2.586771e-03,0.994640,1.000000,1.000000,7.300621e-06,0.999334
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.923077,0.933333,4.773707e-02,0.927686,1.000000,1.000000,1.206968e-04,0.995401
58,animal_class+facts+inventors__affirmative+nega...,0.896825,0.897906,8.068992e-02,0.848357,0.942448,0.942885,4.567364e-02,0.887364
59,animal_class+facts+inventors__affirmative+nega...,0.867081,0.872074,9.542867e-02,0.820643,0.895192,0.896047,7.606133e-02,0.831885

In [30]:
lyr18_ttpd_probe_to_baseline_linear_probe_eval_except_test_df

,scenario,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.000000,0.000000,2.445273e-08,-0.000057,-0.007634,-0.007092,8.771814e-03,-1.052990e-02
1,animal_class__conjunction,-0.090000,-0.080917,5.421183e-02,-0.098470,-0.082500,-0.079903,6.150439e-02,-1.148468e-01
2,animal_class__disjunction,-0.050000,-0.081273,5.247253e-02,-0.132715,-0.142500,-0.147089,9.893978e-02,-1.794198e-01
3,animal_class__negated,0.000000,0.000000,6.577484e-04,-0.004059,-0.015267,-0.015152,1.469421e-02,-2.405677e-02
4,cities__affirmative,-0.003333,-0.003436,5.138021e-03,-0.009379,-0.009197,-0.009079,7.408913e-03,-9.576901e-03
5,cities__conjunction,-0.026667,-0.023444,2.352697e-02,-0.047931,-0.069282,-0.066241,4.671761e-02,-8.151176e-02
6,cities__disjunction,-0.070000,-0.072769,2.219895e-02,-0.025689,-0.075000,-0.077959,4.837384e-02,-6.483336e-02
7,cities__negated,0.003333,0.003055,-1.191099e-03,-0.001395,-0.009197,-0.009336,6.372243e-03,-1.042434e-02
8,element_symb__affirmative,-0.026316,-0.024390,2.134477e-02,-0.034914,-0.094595,-0.087500,6.313708e-02,-8.674779e-02
9,element_symb__conjunction,-0.120000,-0.115385,7.882613e-02,-0.146866,-0.067500,-0.059341,5.868069e-02,-1.073186e-01
10,element_symb__disjunction,-0.180000,-0.162587,1.156770e-01,-0.195731,-0.210000,-0.212121,1.341573e-01,-2.495769e-01
11,element_symb__negated,0.000000,0.000000,-3.210423e-04,0.004105,0.000000,0.000000,-1.460392e-17,8.294688e-10
12,facts__affirmative,-0.097345,-0.074286,7.851715e-02,-0.134223,-0.147321,-0.134147,1.059934e-01,-1.898896e-01
13,facts__conjunction,-0.100000,-0.059928,6.331087e-02,-0.095777,-0.187500,-0.162466,1.095918e-01,-1.579075e-01
14,facts__disjunction,-0.060000,-0.085227,5.012951e-02,-0.108559,-0.240000,-0.268844,1.358451e-01,-2.071611e-01
15,facts__negated,-0.035398,-0.041467,2.084527e-02,-0.039522,-0.064732,-0.065086,4.646199e-02,-6.755548e-02
16,inventors__affirmative,-0.073171,-0.069078,4.140351e-02,-0.093774,-0.104938,-0.099617,8.918222e-02,-1.224995e-01
17,inventors__conjunction,-0.170000,-0.156183,8.208182e-02,-0.137317,-0.175000,-0.157188,1.068195e-01,-1.667652e-01
18,inventors__disjunction,-0.100000,-0.111607,4.861680e-02,-0.118081,-0.167500,-0.165023,8.372878e-02,-1.478823e-01
19,inventors__negated,-0.195122,-0.180921,9.796846e-02,-0.166351,-0.212963,-0.222622,1.125483e-01,-1.935640e-01
20,ambiguous_lie,-0.500000,NaN,2.412132e-01,NaN,-0.571429,NaN,2.524060e-01,NaN
21,ambiguous_truthful_reply,-0.400000,-0.250000,2.086981e-01,-0.289361,-0.444444,-0.285714,2.632712e-01,-3.325137e-01
22,honest_reply_despite_incentive_to_lie,0.000000,0.000000,7.010247e-02,-0.152540,-0.750000,-0.600000,2.680697e-01,-3.357172e-01
23,unambiguous_lie,-0.400000,NaN,2.176609e-01,NaN,-0.461538,NaN,2.550336e-01,NaN
24,unambiguous_truthful_reply,-0.272727,-0.157895,2.202386e-01,-0.302403,-0.500000,-0.333333,2.593466e-01,-3.330134e-01
25,larger_than,-0.027778,-0.028133,2.689818e-02,-0.053652,-0.029040,-0.027981,2.098595e-02,-4.465499e-02
26,smaller_than,-0.050505,-0.044643,3.480716e-02,-0.067332,-0.054924,-0.053081,3.824428e-02,-7.909786e-02
27,sp_en_trans__negated,0.000000,0.000000,2.294588e-04,-0.002374,-0.003534,-0.003534,2.715710e-03,-4.754704e-03
28,sp_en_trans__affirmative,-0.028169,-0.022222,1.804549e-02,-0.025808,-0.031802,-0.032727,1.792615e-02,-3.349019e-02
29,sp_en_trans__conjunction,-0.070000,-0.069307,5.257753e-02,-0.078916,-0.032500,-0.029213,2.128471e-02,-4.480009e-02
30,sp_en_trans__disjunction,-0.150000,-0.170829,1.053350e-01,-0.231029,-0.167500,-0.186630,1.089132e-01,-2.295333e-01
31,common_claim_true_false,-0.029213,-0.027346,2.038309e-02,-0.048703,-0.091292,-0.090213,5.257300e-02,-7.833020e-02
32,counterfact_true_false,-0.118254,-0.097069,6.895546e-02,-0.132472,-0.132181,-0.108981,7.850540e-02,-1.404222e-01
33,animal_class__affirmative+negated,0.000000,0.000000,3.723638e-03,-0.011150,-0.015267,-0.014706,9.318734e-03,-1.559329e-02
34,animal_class__affirmative+disjunction,-0.045113,-0.042676,3.366106e-02,-0.091190,-0.111111,-0.109056,7.697122e-02,-1.291663e-01
35,animal_class__negated+conjunction,-0.060150,-0.053247,4.756792e-02,-0.084634,-0.069680,-0.067151,5.264326e-02,-1.001897e-01
36,animal_class__affirmative+negated+conjunction+...,-0.161654,-0.191554,7.256425e-02,-0.157480,-0.204331,-0.231536,1.003570e-01,-1.895712e-01
37,cities__affirmative+negated,-0.001667,-0.001477,4.505215e-03,-0.009584,-0.011288,-0.011209,1.013268e-02,-1.737827e-02
38,cities__affirmative+disjunction,-0.035000,-0.040082,2.377561e-02,-0.057143,-0.068922,-0.073642,4.192433e-02,-7.360984e-02
39,cities__negated+conjunction,-0.056667,-0.048124,3.695871e-02,-0.072555,-0.071011,-0.067833,5.502248e-02,-1.041479e-01
40,cities__affirmative+negated+conjunction+disjun...,-0.080000,-0.072578,5.333573e-02,-0.094180,-0.115288,-0.109250,7.560212e-02,-1.224877e-01
41,element_symb__affirmative+negated,-0.013158,-0.012658,1.291110e-02,-0.023026,-0.040541,-0.039216,3.085962e-02,-4.579331e-02
42,element_symb__affirmative+disjunction,-0.137681,-0.127959,8.470442e-02,-0.153955,-0.156934,-0.151943,1.062579e-01,-2.025634e-01
43,element_symb__negated+conjunction,-0.101449,-0.095815,7.986078e-02,-0.128377,-0.093066,-0.081862,6.419752e-02,-1.009118e-01
44,element_symb__affirmative+negated+conjunction+...,-0.173913,-0.165917,1.178062e-01,-0.230123,-0.185219,-0.180444,1.233812e-01,-2.359114e-01
45,facts__affirmative+negated,-0.084071,-0.065572,3.432238e-02,-0.045978,-0.099330,-0.091661,6.045906e-02,-8.966229e-02
46,facts__affirmative+disjunction,-0.098592,-0.093686,8.472200e-02,-0.153020,-0.218160,-0.232464,1.422455e-01,-2.392702e-01
47,facts__negated+conjunction,-0.169014,-0.150275,7.715170e-02,-0.173585,-0.189858,-0.173638,1.120891e-01,-2.085259e-01
48,facts__affirmative+negated+conjunction+disjunc...,-0.152582,-0.140331,7.475991e-02,-0.128504,-0.173939,-0.168066,9.911590e-02,-1.633740e-01
49,inventors__affirmative+negated,-0.042683,-0.041897,4.072750e-02,-0.089523,-0.069444,-0.072413,6.662170e-02,-1.167077e-01
50,inventors__affirmative+disjunction,-0.109890,-0.115885,5.125949e-02,-0.130888,-0.149171,-0.154131,9.314296e-02,-1.658311e-01
51,inventors__negated+conjunction,-0.197802,-0.151424,1.271030e-01,-0.242914,-0.308011,-0.258532,1.727039e-01,-3.083661e-01
52,inventors__affirmative+negated+conjunction+dis...,-0.164835,-0.137280,1.090399e-01,-0.218577,-0.259669,-0.228873,1.493716e-01,-2.664578e-01
53,sp_en_trans__affirmative+negated,-0.028169,-0.024691,2.340480e-02,-0.039710,-0.028269,-0.028674,1.558442e-02,-4.114472e-02
54,sp_en_trans__affirmative+disjunction,-0.192982,-0.177209,1.216646e-01,-0.206986,-0.171303,-0.177005,1.080387e-01,-2.137683e-01
55,sp_en_trans__negated+conjunction,-0.046784,-0.046512,3.650491e-02,-0.067766,-0.043924,-0.040650,3.132679e-02,-5.802527e-02
56,sp_en_trans__affirmative+negated+conjunction+d...,-0.169591,-0.174262,1.323373e-01,-0.262572,-0.158126,-0.162651,1.220621e-01,-2.467094e-01
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,-0.115385,-0.118519,7.519370e-02,-0.098123,-0.049505,-0.041322,4.783866e-02,-8.404473e-02
58,animal_class+facts+inventors__affirmative+nega...,-0.146825,-0.128675,8.549259e-02,-0.160522,-0.177977,-0.163309,1.147210e-01,-1.988424e-01
59,animal_class+facts+inventors__affirmative+nega...,-0.061652,-0.052557,4.957473e-02,-0.108845,-0.107361,-0.098593,7.751492e-02,-1.360602e-01

In [31]:
lyr18_ttpd_probe_to_baseline_linear_probe_eval_except_test_df.describe()

,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
count,60.000000,58.000000,60.000000,58.000000,60.000000,58.000000,6.000000e+01,5.800000e+01
mean,-0.101466,-0.080658,0.063920,-0.107107,-0.144992,-0.121156,8.562848e-02,-1.331467e-01
std,0.101026,0.062597,0.055532,0.077555,0.145254,0.103688,6.756823e-02,9.059338e-02
min,-0.500000,-0.250000,-0.001191,-0.302403,-0.750000,-0.600000,-1.460392e-17,-3.357172e-01
25%,-0.150646,-0.128496,0.023496,-0.152900,-0.179788,-0.167306,4.100432e-02,-1.975228e-01
50%,-0.076585,-0.070942,0.051866,-0.096950,-0.106149,-0.095127,7.628667e-02,-1.195977e-01
75%,-0.028952,-0.027543,0.082737,-0.046466,-0.053569,-0.044262,1.102161e-01,-6.551389e-02
max,0.003333,0.003055,0.241213,0.004105,0.000000,0.000000,2.680697e-01,8.294688e-10

It is slightly interesting that the simple linear probes seem to be doing markedly better within topic and data variant than the TTPD probes, given that Bürger et al found them generalizing similarly well.

In [32]:
lyr18_probe_metrics_on_test_dsets: dict[tuple[int,...], dict[int, ConfusionMetrics]] = {
    scenario_id: {
        dset_idx_in_scenario: test_dset_metrics.lyr18_probe_metrics for dset_idx_in_scenario, test_dset_metrics in test_dsets_metrics.items()
    } 
    for scenario_id, test_dsets_metrics in probes_metrics_on_test_dsets.items()
}

In [95]:
# Just using accuracy because there are going to be _so_ many columns in this analysis's dataframe and examination of validation accuracy vs f1 vs soft-f1 for layer 18 probes showed that they were generally very similar for the standard topics' datasets (because those datasets were specifically constructed to be balanced between true and false statements) 
class GeneralizationAccuracyWithinVsAcrossTopics(NamedTuple):
    affirm_within_topics: float
    affirm_across_topics: float
    neg_within_topics: float
    neg_across_topics: float
    conj_within_topics: float
    conj_across_topics: float
    disj_within_topics: float
    disj_across_topics: float
    de_affirm_within_topics: float
    de_affirm_across_topics: float
    de_neg_within_topics: float
    de_neg_across_topics: float

class TopicGeneralizationSummary(NamedTuple):
    avg_across_topic_penalty: float
    affirm_across_topic_penalty: float
    neg_across_topic_penalty: float
    conj_across_topic_penalty: float
    disj_across_topic_penalty: float
    de_affirm_across_topic_penalty: float
    de_neg_across_topic_penalty: float

lyr18_probe_generalization_within_vs_across_topics: dict[tuple[int,...], GeneralizationAccuracyWithinVsAcrossTopics] = {}
lyr18_probe_topic_generalization_summary: dict[tuple[int,...], TopicGeneralizationSummary] = {}

avg_cross_topic_acc_by_source_and_target_data_variants = pd.DataFrame({
    "source_data_variants": ["affirm", "neg", "conj", "disj", "affirm+neg", "affirm+disj", "neg+conj", "affirm+neg+conj+disj", "multitopic_affirm+neg+conj"],
    "affirm": [0.0]*9, "neg": [0.0]*9, "conj": [0.0]*9, "disj": [0.0]*9
})

for scenario_id, test_dsets_metrics in lyr18_probe_metrics_on_test_dsets.items():
    curr_standard_categs = scenario_standard_categs[scenario_id]
    curr_data_variants = scenario_data_variants[scenario_id]
    if not curr_standard_categs:
        continue
    unseen_standard_categs = list(set(dset_idxs_for_4way_topics.keys()) - set(curr_standard_categs))
    metrics_on_test_dsets = lyr18_probe_metrics_on_test_dsets[scenario_id]
    
    affirm_within_topics_acc = np.nan
    if "affirm" not in curr_data_variants:
        same_topics_affirm_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["affirm"]] for topic_nm in curr_standard_categs
        ])
        affirm_within_topics_acc = same_topics_affirm_test_metrics.get_traditional_metrics().accuracy
    across_topics_affirm_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["affirm"]] for topic_nm in unseen_standard_categs
    ])
    affirm_across_topics_acc = across_topics_affirm_test_metrics.get_traditional_metrics().accuracy
    neg_within_topics_acc = np.nan
    if "neg" not in curr_data_variants:
        same_topics_neg_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["neg"]] for topic_nm in curr_standard_categs
        ])
        neg_within_topics_acc = same_topics_neg_test_metrics.get_traditional_metrics().accuracy
    across_topics_neg_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["neg"]] for topic_nm in unseen_standard_categs
    ])
    neg_across_topics_acc = across_topics_neg_test_metrics.get_traditional_metrics().accuracy
    conj_within_topics_acc = np.nan
    if "conj" not in curr_data_variants:
        same_topics_conj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["conj"]] for topic_nm in curr_standard_categs
        ])
        conj_within_topics_acc = same_topics_conj_test_metrics.get_traditional_metrics().accuracy
    across_topics_conj_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["conj"]] for topic_nm in unseen_standard_categs
    ])
    conj_across_topics_acc = across_topics_conj_test_metrics.get_traditional_metrics().accuracy
    disj_within_topics_acc = np.nan
    if "disj" not in curr_data_variants:
        same_topics_disj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["disj"]] for topic_nm in curr_standard_categs
        ])
        disj_within_topics_acc = same_topics_disj_test_metrics.get_traditional_metrics().accuracy
    across_topics_disj_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["disj"]] for topic_nm in unseen_standard_categs
    ])
    disj_across_topics_acc = across_topics_disj_test_metrics.get_traditional_metrics().accuracy
    assert "de_affirm" not in curr_data_variants
    same_topics_de_affirm_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_affirm"]] for topic_nm in curr_standard_categs
    ])
    de_affirm_within_topics_acc = same_topics_de_affirm_test_metrics.get_traditional_metrics().accuracy
    across_topics_de_affirm_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_affirm"]] for topic_nm in unseen_standard_categs
    ])
    de_affirm_across_topics_acc = across_topics_de_affirm_test_metrics.get_traditional_metrics().accuracy
    assert "de_neg" not in curr_data_variants
    same_topics_de_neg_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_neg"]] for topic_nm in curr_standard_categs
    ])
    de_neg_within_topics_acc = same_topics_de_neg_test_metrics.get_traditional_metrics().accuracy
    across_topics_de_neg_test_metrics = ConfusionMetrics.combine(*[
        metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_neg"]] for topic_nm in unseen_standard_categs
    ])
    de_neg_across_topics_acc = across_topics_de_neg_test_metrics.get_traditional_metrics().accuracy
    
    if "other" not in curr_data_variants:
        avg_cross_topic_acc_source_row_selector: pd.Series
        match curr_data_variants:
            case _ if curr_data_variants in [{"affirm"}, {"neg"}, {"conj"}, {"disj"}]:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == str(list(curr_data_variants)[0])
            case _ if curr_data_variants == {"affirm", "neg"}:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == "affirm+neg"
            case _ if curr_data_variants == {"affirm", "disj"}:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == "affirm+disj"
            case _ if curr_data_variants == {"neg", "conj"}:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == "neg+conj"
            case _ if curr_data_variants == {"affirm", "neg", "conj", "disj"}:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == "affirm+neg+conj+disj"
            case _ if curr_data_variants == {"affirm", "neg", "conj"}:
                avg_cross_topic_acc_source_row_selector = avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"] == "multitopic_affirm+neg+conj"
            case _:
                raise ValueError(f"invalid value {curr_data_variants} for curr_data_variants for scenario {scenario_id}")
        avg_cross_topic_acc_by_source_and_target_data_variants.loc[avg_cross_topic_acc_source_row_selector, "affirm"] += affirm_across_topics_acc
        avg_cross_topic_acc_by_source_and_target_data_variants.loc[avg_cross_topic_acc_source_row_selector, "neg"] += neg_across_topics_acc
        avg_cross_topic_acc_by_source_and_target_data_variants.loc[avg_cross_topic_acc_source_row_selector, "conj"] += conj_across_topics_acc
        avg_cross_topic_acc_by_source_and_target_data_variants.loc[avg_cross_topic_acc_source_row_selector, "disj"] += disj_across_topics_acc
    
    lyr18_probe_generalization_within_vs_across_topics[scenario_id] = GeneralizationAccuracyWithinVsAcrossTopics(
        affirm_within_topics=affirm_within_topics_acc, affirm_across_topics=affirm_across_topics_acc, neg_within_topics=neg_within_topics_acc,
        neg_across_topics=neg_across_topics_acc, conj_within_topics=conj_within_topics_acc, conj_across_topics=conj_across_topics_acc,
        disj_within_topics=disj_within_topics_acc, disj_across_topics=disj_across_topics_acc, de_affirm_within_topics=de_affirm_within_topics_acc,
        de_affirm_across_topics=de_affirm_across_topics_acc, de_neg_within_topics=de_neg_within_topics_acc, de_neg_across_topics=de_neg_across_topics_acc
    )
    
    affirm_across_topic_acc_penalty = affirm_within_topics_acc-affirm_across_topics_acc
    neg_across_topic_acc_penalty = neg_within_topics_acc-neg_across_topics_acc
    conj_across_topic_acc_penalty = conj_within_topics_acc-conj_across_topics_acc
    disj_across_topic_acc_penalty = disj_within_topics_acc-disj_across_topics_acc
    de_affirm_across_topic_acc_penalty = de_affirm_within_topics_acc-de_affirm_across_topics_acc
    de_neg_across_topic_acc_penalty = de_neg_within_topics_acc-de_neg_across_topics_acc
    avg_across_topic_acc_penalty = float(np.nanmean([affirm_across_topic_acc_penalty, neg_across_topic_acc_penalty, conj_across_topic_acc_penalty, disj_across_topic_acc_penalty, de_affirm_across_topic_acc_penalty, de_neg_across_topic_acc_penalty]))
    
    lyr18_probe_topic_generalization_summary[scenario_id] = TopicGeneralizationSummary(
        avg_across_topic_penalty=avg_across_topic_acc_penalty, affirm_across_topic_penalty=affirm_across_topic_acc_penalty, 
        neg_across_topic_penalty=neg_across_topic_acc_penalty, conj_across_topic_penalty=conj_across_topic_acc_penalty,
        disj_across_topic_penalty=disj_across_topic_acc_penalty, de_affirm_across_topic_penalty=de_affirm_across_topic_acc_penalty,
        de_neg_across_topic_penalty=de_neg_across_topic_acc_penalty
    )

avg_cross_topic_acc_by_source_and_target_data_variants.loc[~avg_cross_topic_acc_by_source_and_target_data_variants["source_data_variants"].str.startswith("multitopic_"), ["affirm", "neg", "conj", "disj"]] /= num_standard_topics


generalization_within_vs_across_topics_df = pd.DataFrame([
    { "scenario": scenario_labels[scenario_id], **generalization_info._asdict()  } for scenario_id, generalization_info in lyr18_probe_generalization_within_vs_across_topics.items()
])
topic_generalization_summary_df = pd.DataFrame([
    { "scenario": scenario_labels[scenario_id], **generalization_summary._asdict()  } for scenario_id, generalization_summary in lyr18_probe_topic_generalization_summary.items()
])

In [96]:
generalization_within_vs_across_topics_df

,scenario,affirm_within_topics,affirm_across_topics,neg_within_topics,neg_across_topics,conj_within_topics,conj_across_topics,disj_within_topics,disj_across_topics,de_affirm_within_topics,de_affirm_across_topics,de_neg_within_topics,de_neg_across_topics
0,animal_class__affirmative,NaN,0.840160,0.835366,0.629704,0.596000,0.648942,0.522000,0.592400,0.900000,0.688000,0.520000,0.473896
1,animal_class__conjunction,0.993902,0.829504,0.932927,0.645688,NaN,0.749285,0.502000,0.612400,0.880000,0.656000,0.540000,0.489960
2,animal_class__disjunction,0.829268,0.857476,0.487805,0.511156,0.882000,0.692396,NaN,0.598400,0.500000,0.664000,0.540000,0.550201
3,animal_class__negated,0.859756,0.877456,NaN,0.837829,0.560000,0.644940,0.498000,0.513600,0.760000,0.696000,0.860000,0.638554
4,cities__affirmative,NaN,0.683423,0.804813,0.511670,0.618825,0.578400,0.476000,0.492400,0.940000,0.600000,0.500000,0.481928
5,cities__conjunction,0.982620,0.792340,0.969251,0.551765,NaN,0.782400,0.518000,0.555200,0.980000,0.704000,0.840000,0.526104
6,cities__disjunction,0.951203,0.667265,0.514037,0.471574,0.640854,0.695200,NaN,0.668800,0.660000,0.568000,0.580000,0.497992
7,cities__negated,0.691845,0.597247,NaN,0.779174,0.502003,0.545600,0.484000,0.489200,0.640000,0.552000,1.000000,0.650602
8,element_symb__affirmative,NaN,0.903388,0.500000,0.527340,0.960000,0.802173,0.482000,0.506800,0.660000,0.852000,0.520000,0.546185
9,element_symb__conjunction,0.715054,0.693391,0.500000,0.525663,NaN,0.817896,0.696000,0.585600,0.740000,0.792000,0.520000,0.514056
10,element_symb__disjunction,0.645161,0.621603,0.360215,0.577994,0.642000,0.576901,NaN,0.609200,0.640000,0.672000,0.240000,0.481928
11,element_symb__negated,0.392473,0.286146,NaN,0.875210,0.272000,0.506861,0.448000,0.506800,0.300000,0.488000,0.920000,0.730924
12,facts__affirmative,NaN,0.924021,0.552585,0.513047,0.680000,0.869354,0.596000,0.527600,0.640000,0.820000,0.489796,0.428000
13,facts__conjunction,0.775401,0.589025,0.504456,0.509210,NaN,0.830475,0.574000,0.494800,0.620000,0.656000,0.489796,0.524000
14,facts__disjunction,0.648841,0.776285,0.506239,0.508442,0.524000,0.681246,NaN,0.569600,0.540000,0.620000,0.510204,0.480000
15,facts__negated,0.713012,0.727168,NaN,0.869148,0.474000,0.518296,0.462000,0.505200,0.540000,0.576000,0.714286,0.664000
16,inventors__affirmative,NaN,0.830858,0.576355,0.729084,0.756000,0.744140,0.652000,0.619200,0.820000,0.804000,0.600000,0.534137
17,inventors__conjunction,0.605911,0.594712,0.610837,0.500181,NaN,0.713265,0.446000,0.514400,0.480000,0.672000,0.600000,0.473896
18,inventors__disjunction,0.854680,0.569721,0.554187,0.499457,0.682000,0.779017,NaN,0.573600,0.640000,0.504000,0.500000,0.502008
19,inventors__negated,0.416256,0.181094,NaN,0.649402,0.576000,0.500858,0.544000,0.462400,0.400000,0.396000,0.740000,0.614458
20,sp_en_trans__negated,0.497175,0.403128,NaN,0.821898,0.440000,0.462836,0.536000,0.490400,0.500000,0.420000,0.960000,0.811245
21,sp_en_trans__affirmative,NaN,0.879844,0.274011,0.750800,0.834000,0.675815,0.730000,0.612400,0.860000,0.744000,0.500000,0.534137
22,sp_en_trans__conjunction,0.550847,0.774973,0.500000,0.652328,NaN,0.825043,0.574000,0.590400,0.540000,0.788000,0.460000,0.530120
23,sp_en_trans__disjunction,0.508475,0.643086,0.497175,0.562033,0.874000,0.554031,NaN,0.519200,0.540000,0.584000,0.460000,0.538153
24,animal_class__affirmative+negated,NaN,0.909424,NaN,0.850150,0.622000,0.687250,0.500000,0.630800,0.900000,0.736000,0.760000,0.706827
25,animal_class__affirmative+disjunction,NaN,0.858142,0.865854,0.643024,0.668000,0.679531,NaN,0.610400,0.900000,0.700000,0.540000,0.457831
26,animal_class__negated+conjunction,0.993902,0.858142,NaN,0.704296,NaN,0.765009,0.502000,0.611200,0.880000,0.692000,0.640000,0.522088
27,animal_class__affirmative+negated+conjunction+...,NaN,0.887779,NaN,0.779887,NaN,0.738708,NaN,0.644400,0.880000,0.716000,0.740000,0.578313
28,cities__affirmative+negated,NaN,0.845003,NaN,0.828247,0.584780,0.636000,0.474000,0.596800,0.960000,0.696000,1.000000,0.718876
29,cities__affirmative+disjunction,NaN,0.719330,0.790775,0.543986,0.678238,0.626400,NaN,0.589600,0.920000,0.664000,0.500000,0.489960
30,cities__negated+conjunction,0.981283,0.847995,NaN,0.675643,NaN,0.755200,0.560000,0.614000,0.980000,0.724000,0.980000,0.610442
31,cities__affirmative+negated+conjunction+disjun...,NaN,0.816278,NaN,0.704967,NaN,0.686400,NaN,0.662000,0.980000,0.696000,0.960000,0.626506
32,element_symb__affirmative+negated,NaN,0.909091,NaN,0.902382,0.810000,0.613493,0.544000,0.538400,0.580000,0.772000,0.860000,0.730924
33,element_symb__affirmative+disjunction,NaN,0.899363,0.736559,0.693056,0.778000,0.629503,NaN,0.628800,0.740000,0.768000,0.520000,0.550201
34,element_symb__negated+conjunction,0.500000,0.638376,NaN,0.885273,NaN,0.672956,0.566000,0.579600,0.400000,0.796000,0.780000,0.835341
35,element_symb__affirmative+negated+conjunction+...,NaN,0.921503,NaN,0.904394,NaN,0.668382,NaN,0.643200,0.620000,0.832000,0.760000,0.783133
36,facts__affirmative+negated,NaN,0.909823,NaN,0.920568,0.546000,0.583762,0.482000,0.544800,0.600000,0.776000,0.714286,0.768000
37,facts__affirmative+disjunction,NaN,0.926708,0.607843,0.779739,0.714000,0.882218,NaN,0.553200,0.580000,0.788000,0.510204,0.608000
38,facts__negated+conjunction,0.871658,0.936685,NaN,0.954720,NaN,0.750429,0.712000,0.574800,0.640000,0.804000,0.714286,0.828000
39,facts__affirmative+negated+conjunction+disjunc...,NaN,0.930929,NaN,0.945510,NaN,0.736707,NaN,0.548800,0.660000,0.792000,0.755102,0.780000
40,inventors__affirmative+negated,NaN,0.845346,NaN,0.876494,0.580000,0.569468,0.572000,0.522400,0.820000,0.656000,0.840000,0.742972
41,inventors__affirmative+disjunction,NaN,0.850054,0.593596,0.725462,0.752000,0.803888,NaN,0.540000,0.820000,0.828000,0.640000,0.562249
42,inventors__negated+conjunction,0.435961,0.497646,NaN,0.874683,NaN,0.503716,0.538000,0.487600,0.420000,0.540000,0.840000,0.722892
43,inventors__affirmative+negated+conjunction+dis...,NaN,0.870337,NaN,0.506338,NaN,0.794454,NaN,0.620400,0.700000,0.816000,0.600000,0.502008
44,sp_en_trans__affirmative+negated,NaN,0.910060,NaN,0.853893,0.922000,0.601487,0.532000,0.567200,0.880000,0.788000,0.540000,0.738956
45,sp_en_trans__affirmative+disjunction,NaN,0.854604,0.429379,0.600071,0.796000,0.570898,NaN,0.504400,0.840000,0.656000,0.520000,0.465863
46,sp_en_trans__negated+conjunction,0.500000,0.479559,NaN,0.878066,NaN,0.580046,0.528000,0.498400,0.740000,0.480000,0.920000,0.835341
47,sp_en_trans__affirmative+negated+conjunction+d...,NaN,0.910060,NaN,0.889797,NaN,0.559748,NaN,0.513200,0.980000,0.784000,0.540000,0.767068
48,animal_class+facts+inventors__affirmative+nega...,NaN,0.976424,NaN,0.877210,NaN,0.845476,0.611333,0.526000,0.800000,0.813333,0.765101,0.660000
49,animal_class+facts+inventors__affirmative+nega...,NaN,0.976916,NaN,0.943517,0.753333,0.895116,0.507333,0.510667,0.766667,0.826667,0.778523,0.686667

In [97]:
topic_generalization_summary_df

,scenario,avg_across_topic_penalty,affirm_across_topic_penalty,neg_across_topic_penalty,conj_across_topic_penalty,disj_across_topic_penalty,de_affirm_across_topic_penalty,de_neg_across_topic_penalty
0,animal_class__affirmative,0.068085,NaN,0.205662,-0.052942,-0.070400,0.212000,0.046104
1,animal_class__conjunction,0.123056,0.164399,0.287239,NaN,-0.110400,0.224000,0.050040
2,animal_class__disjunction,-0.007231,-0.028208,-0.023351,0.189604,NaN,-0.164000,-0.010201
3,animal_class__negated,0.033441,-0.017700,NaN,-0.084940,-0.015600,0.064000,0.221446
4,cities__affirmative,0.135048,NaN,0.293143,0.040425,-0.016400,0.340000,0.018072
5,cities__conjunction,0.232092,0.190280,0.417486,NaN,-0.037200,0.276000,0.313896
6,cities__disjunction,0.089213,0.283938,0.042464,-0.054346,NaN,0.092000,0.082008
7,cities__negated,0.096640,0.094598,NaN,-0.043597,-0.005200,0.088000,0.349398
8,element_symb__affirmative,-0.022499,NaN,-0.027340,0.157827,-0.024800,-0.192000,-0.026185
9,element_symb__conjunction,0.012069,0.021662,-0.025663,NaN,0.110400,-0.052000,0.005944
10,element_symb__disjunction,-0.080610,0.023558,-0.217779,0.065099,NaN,-0.032000,-0.241928
11,element_symb__negated,-0.037251,0.106328,NaN,-0.234861,-0.058800,-0.188000,0.189076
12,facts__affirmative,-0.039924,NaN,0.039538,-0.189354,0.068400,-0.180000,0.061796
13,facts__conjunction,0.038124,0.186376,-0.004753,NaN,0.079200,-0.036000,-0.034204
14,facts__disjunction,-0.067338,-0.127444,-0.002203,-0.157246,NaN,-0.080000,0.030204
15,facts__negated,-0.017473,-0.014156,NaN,-0.044296,-0.043200,-0.036000,0.050286
16,inventors__affirmative,-0.005241,NaN,-0.152729,0.011860,0.032800,0.016000,0.065863
17,inventors__conjunction,-0.002488,0.011199,0.110656,NaN,-0.068400,-0.192000,0.126104
18,inventors__disjunction,0.075333,0.284959,0.054730,-0.097017,NaN,0.136000,-0.002008
19,inventors__negated,0.104289,0.235162,NaN,0.075142,0.081600,0.004000,0.125542
20,sp_en_trans__negated,0.069113,0.094047,NaN,-0.022836,0.045600,0.080000,0.148755
21,sp_en_trans__affirmative,-0.023828,NaN,-0.476789,0.158185,0.117600,0.116000,-0.034137
22,sp_en_trans__conjunction,-0.142195,-0.224126,-0.152328,NaN,-0.016400,-0.248000,-0.070120
23,sp_en_trans__disjunction,-0.000331,-0.134611,-0.064858,0.319969,NaN,-0.044000,-0.078153
24,animal_class__affirmative+negated,0.005281,NaN,NaN,-0.065250,-0.130800,0.164000,0.053173
25,animal_class__affirmative+disjunction,0.123367,NaN,0.222830,-0.011531,NaN,0.200000,0.082169
26,animal_class__negated+conjunction,0.083118,0.135761,NaN,NaN,-0.109200,0.188000,0.117912
27,animal_class__affirmative+negated+conjunction+...,0.162843,NaN,NaN,NaN,NaN,0.164000,0.161687
28,cities__affirmative+negated,0.092776,NaN,NaN,-0.051220,-0.122800,0.264000,0.281124
29,cities__affirmative+disjunction,0.141167,NaN,0.246790,0.051838,NaN,0.256000,0.010040
30,cities__negated+conjunction,0.176212,0.133288,NaN,NaN,-0.054000,0.256000,0.369558
31,cities__affirmative+negated+conjunction+disjun...,0.308747,NaN,NaN,NaN,NaN,0.284000,0.333494
32,element_symb__affirmative+negated,0.034796,NaN,NaN,0.196507,0.005600,-0.192000,0.129076
33,element_symb__affirmative+disjunction,0.033450,NaN,0.043503,0.148497,NaN,-0.028000,-0.030201
34,element_symb__negated+conjunction,-0.150829,-0.138376,NaN,NaN,-0.013600,-0.396000,-0.055341
35,element_symb__affirmative+negated+conjunction+...,-0.117566,NaN,NaN,NaN,NaN,-0.212000,-0.023133
36,facts__affirmative+negated,-0.082569,NaN,NaN,-0.037762,-0.062800,-0.176000,-0.053714
37,facts__affirmative+disjunction,-0.161478,NaN,-0.171896,-0.168218,NaN,-0.208000,-0.097796
38,facts__negated+conjunction,-0.051385,-0.065027,NaN,NaN,0.137200,-0.164000,-0.113714
39,facts__affirmative+negated+conjunction+disjunc...,-0.078449,NaN,NaN,NaN,NaN,-0.132000,-0.024898
40,inventors__affirmative+negated,0.080290,NaN,NaN,0.010532,0.049600,0.164000,0.097028
41,inventors__affirmative+disjunction,-0.028501,NaN,-0.131866,-0.051888,NaN,-0.008000,0.077751
42,inventors__negated+conjunction,-0.003544,-0.061685,NaN,NaN,0.050400,-0.120000,0.117108
43,inventors__affirmative+negated+conjunction+dis...,-0.009004,NaN,NaN,NaN,NaN,-0.116000,0.097992
44,sp_en_trans__affirmative+negated,0.044589,NaN,NaN,0.320513,-0.035200,0.092000,-0.198956
45,sp_en_trans__affirmative+disjunction,0.073137,NaN,-0.170693,0.225102,NaN,0.184000,0.054137
46,sp_en_trans__negated+conjunction,0.098675,0.020441,NaN,NaN,0.029600,0.260000,0.084659
47,sp_en_trans__affirmative+negated+conjunction+d...,-0.015534,NaN,NaN,NaN,NaN,0.196000,-0.227068
48,animal_class+facts+inventors__affirmative+nega...,0.059034,NaN,NaN,NaN,0.085333,-0.013333,0.105101
49,animal_class+facts+inventors__affirmative+nega...,-0.028315,NaN,NaN,-0.141783,-0.003333,-0.060000,0.091857

In [98]:
(avg_topic_generalization_penalty_across_all_scenarios := topic_generalization_summary_df.avg_across_topic_penalty.mean().item())

0.028407982234862916

The cross-topic generalization penalty is surprisingly small (<3 percentage-points on average), so we will ignore the "already-seen topic vs fully-unseen topic" distinction for analysis beyond this point.

In passing, it is surprising that the 3-topic affirmative+negated+conjunction scenario had worse cross-topic generalization than the average scenario.

In [99]:
avg_cross_topic_acc_by_source_and_target_data_variants

         source_data_variants    affirm       neg      conj      disj
0                      affirm  0.843616  0.610274  0.719804  0.558467
1                         neg  0.512040  0.805444  0.529898  0.494600
2                        conj  0.712324  0.564139  0.786394  0.558800
3                        disj  0.689239  0.521776  0.663132  0.589800
4                  affirm+neg  0.888125  0.871955  0.615243  0.566733
5                 affirm+disj  0.851367  0.664223  0.698740  0.571067
6                    neg+conj  0.709734  0.828780  0.671226  0.560933
7        affirm+neg+conj+disj  0.889481  0.788482  0.697400  0.605333
8  multitopic_affirm+neg+conj  0.976424  0.877210  0.845476  0.526000

Unsurprisingly, the best generalization to unseen disjunctive datasets was achieved when the directions and probe were trained at least partially on disjunctive data. One interesting thing is that the affirm+neg+conj+disj scenarios generalized better to unseen topics' disjunctive data better than the only-disjunctive scenarios, while the scenario trained on affirmative, negated, and conjunctive data from multiple topics generalized terribly to unseen topics' disjunctive data.

In [37]:
lyr18_baseline_linear_probe_metrics_on_test_dsets: dict[tuple[int,...], dict[int, ConfusionMetrics]] = {
    scenario_id: {
        dset_idx_in_scenario: test_dset_metrics.lyr18_baseline_linear_probe_metrics for dset_idx_in_scenario, test_dset_metrics in test_dsets_metrics.items()
    } 
    for scenario_id, test_dsets_metrics in probes_metrics_on_test_dsets.items()
}

In [38]:
#using more verbose phrasing in just this case to disambiguate from affirmative english texts in 'other' topics (real world scenarios, relative comparison, true false)
is_dset_en_affirm_in_std_topic: dict[int, bool] = (~(dsets_index_df.is_negated | dsets_index_df.is_conj | dsets_index_df.is_disj | dsets_index_df.is_other | dsets_index_df.in_german)).to_dict()
is_dset_en_negated: dict[int, bool] = (dsets_index_df.is_negated & ~dsets_index_df.in_german).to_dict()
is_dset_conj: dict[int, bool] = dsets_index_df.is_conj.to_dict()
is_dset_disj: dict[int, bool] = dsets_index_df.is_disj.to_dict()
is_dset_de_affirm: dict[int, bool] = (~dsets_index_df.is_negated & dsets_index_df.in_german).to_dict()
is_dset_de_negated: dict[int, bool] = (dsets_index_df.is_negated & dsets_index_df.in_german).to_dict()

In [39]:
dset_categ_lookup: dict[int, str] = dsets_index_df["Categ_Folder"].to_dict()

In [40]:
lyr18_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts: list[dict[str, str | float]] = []
lyr18_baseline_linear_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts: list[dict[str, str | float]] = []
lyr18_probes_acc_on_unseen_single_topic_data_groupings_row_dicts: list[dict[str, str|float]] = []
lyr18_baseline_linear_probes_acc_on_unseen_single_topic_data_groupings_row_dicts: list[dict[str, str|float]] = []

lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_row_dicts: list[dict[str, str | float]] = []
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_row_dicts: list[dict[str, str|float]] = []

In [41]:
def get_aggregate_trad_metrics(probe_dsets_metrics: dict[int, ConfusionMetrics], relevance_condition: Callable[[int], bool]) -> TraditionalMetrics:
    relev_dsets_metrics = [metrics for curr_dset_idx, metrics in probe_dsets_metrics.items() if relevance_condition(curr_dset_idx)]
    return ConfusionMetrics.combine(*relev_dsets_metrics).get_traditional_metrics()

In [42]:
for scenario_id in dir_probe_scenarios_specs:
    ttpd_probe_metrics = lyr18_probe_metrics_on_test_dsets[scenario_id]
    baseline_probe_metrics = lyr18_baseline_linear_probe_metrics_on_test_dsets[scenario_id]
    
    ttpd_all_unseen_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: True).accuracy
    baseline_all_unseen_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: True).accuracy
    
    ttpd_all_unseen_en_affirm_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_en_affirm_in_std_topic[idx]).accuracy
    baseline_all_unseen_en_affirm_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_en_affirm_in_std_topic[idx]).accuracy
    
    ttpd_all_unseen_en_neg_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_en_negated[idx]).accuracy
    baseline_all_unseen_en_neg_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_en_negated[idx]).accuracy
    
    ttpd_all_unseen_conj_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_conj[idx]).accuracy
    baseline_all_unseen_conj_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_conj[idx]).accuracy
    
    ttpd_all_unseen_disj_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_disj[idx]).accuracy
    baseline_all_unseen_disj_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_disj[idx]).accuracy
    
    ttpd_all_unseen_de_affirm_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_de_affirm[idx]).accuracy
    baseline_all_unseen_de_affirm_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_de_affirm[idx]).accuracy
    
    ttpd_all_unseen_de_neg_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, lambda idx: is_dset_de_negated[idx]).accuracy
    baseline_all_unseen_de_neg_acc = get_aggregate_trad_metrics(baseline_probe_metrics, lambda idx: is_dset_de_negated[idx]).accuracy

    animal_class_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "animal_class"
    ttpd_all_unseen_animal_class_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, animal_class_filter).accuracy
    baseline_all_unseen_animal_class_acc = get_aggregate_trad_metrics(baseline_probe_metrics, animal_class_filter).accuracy
    
    cities_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "cities"
    ttpd_all_unseen_cities_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, cities_filter).accuracy
    baseline_all_unseen_cities_acc = get_aggregate_trad_metrics(baseline_probe_metrics, cities_filter).accuracy
    
    element_symbol_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "element_symb"
    ttpd_all_unseen_element_symbol_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, element_symbol_filter).accuracy
    baseline_all_unseen_element_symbol_acc = get_aggregate_trad_metrics(baseline_probe_metrics, element_symbol_filter).accuracy
    
    facts_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "facts"
    ttpd_all_unseen_facts_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, facts_filter).accuracy
    baseline_all_unseen_facts_acc = get_aggregate_trad_metrics(baseline_probe_metrics, facts_filter).accuracy
    
    inventors_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "inventors"
    ttpd_all_unseen_inventors_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, inventors_filter).accuracy
    baseline_all_unseen_inventors_acc = get_aggregate_trad_metrics(baseline_probe_metrics, inventors_filter).accuracy
    
    sp_en_trans_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "sp_en_trans"
    ttpd_all_unseen_sp_en_trans_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, sp_en_trans_filter).accuracy
    baseline_all_unseen_sp_en_trans_acc = get_aggregate_trad_metrics(baseline_probe_metrics, sp_en_trans_filter).accuracy
    
    real_world_scenarios_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "real_world_scenarios"
    ttpd_all_unseen_real_world_scenarios_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, real_world_scenarios_filter).accuracy
    baseline_all_unseen_real_world_scenarios_acc = get_aggregate_trad_metrics(baseline_probe_metrics, real_world_scenarios_filter).accuracy
    
    relative_comparison_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "relative_comparison"
    ttpd_all_unseen_relative_comparison_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, relative_comparison_filter).accuracy
    baseline_all_unseen_relative_comparison_acc = get_aggregate_trad_metrics(baseline_probe_metrics, relative_comparison_filter).accuracy
    
    true_false_filter: Callable[[int], bool] = lambda idx: dset_categ_lookup[idx] == "true_false"
    ttpd_all_unseen_true_false_acc = get_aggregate_trad_metrics(ttpd_probe_metrics, true_false_filter).accuracy
    baseline_all_unseen_true_false_acc = get_aggregate_trad_metrics(baseline_probe_metrics, true_false_filter).accuracy
    
    ttpd_multi_topic_acc_row_dict = {
        "scenario": scenario_labels[scenario_id], "all": ttpd_all_unseen_acc, "en_affirm": ttpd_all_unseen_en_affirm_acc, "en_negated": ttpd_all_unseen_en_neg_acc,
        "conj": ttpd_all_unseen_conj_acc, "disj": ttpd_all_unseen_disj_acc, "de_affirm": ttpd_all_unseen_de_affirm_acc, "de_negated": ttpd_all_unseen_de_neg_acc
    }
    lyr18_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts.append(ttpd_multi_topic_acc_row_dict)
    baseline_multi_topic_acc_row_dict = {
        "scenario": scenario_labels[scenario_id], "all": baseline_all_unseen_acc, "en_affirm": baseline_all_unseen_en_affirm_acc, 
        "en_negated": baseline_all_unseen_en_neg_acc, "conj": baseline_all_unseen_conj_acc, "disj": baseline_all_unseen_disj_acc, 
        "de_affirm": baseline_all_unseen_de_affirm_acc, "de_negated": baseline_all_unseen_de_neg_acc
    }
    lyr18_baseline_linear_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts.append(baseline_multi_topic_acc_row_dict)
    lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_row_dicts.append({
        col_nm: (ttpd_multi_topic_acc_row_dict[col_nm] if col_nm == "scenario" else ttpd_multi_topic_acc_row_dict[col_nm] - baseline_multi_topic_acc_row_dict[col_nm]) for col_nm in ttpd_multi_topic_acc_row_dict.keys()
    })
    
    ttpd_single_topic_acc_row_dict = {
        "scenario": scenario_labels[scenario_id], "animal class": ttpd_all_unseen_animal_class_acc, "cities": ttpd_all_unseen_cities_acc,
        "element symbols": ttpd_all_unseen_element_symbol_acc, "facts": ttpd_all_unseen_facts_acc,
        "inventors": ttpd_all_unseen_inventors_acc, "spanish english translation": ttpd_all_unseen_sp_en_trans_acc, 
        "real world scenarios": ttpd_all_unseen_real_world_scenarios_acc, "relative comparison": ttpd_all_unseen_relative_comparison_acc,
        "true false": ttpd_all_unseen_true_false_acc
    }
    lyr18_probes_acc_on_unseen_single_topic_data_groupings_row_dicts.append(ttpd_single_topic_acc_row_dict)
    baseline_single_topic_acc_row_dict = {
        "scenario": scenario_labels[scenario_id],  "animal class": baseline_all_unseen_animal_class_acc, "cities": baseline_all_unseen_cities_acc,
        "element symbols": baseline_all_unseen_element_symbol_acc, "facts": baseline_all_unseen_facts_acc,
        "inventors": baseline_all_unseen_inventors_acc, "spanish english translation": baseline_all_unseen_sp_en_trans_acc, 
        "real world scenarios": baseline_all_unseen_real_world_scenarios_acc, "relative comparison": baseline_all_unseen_relative_comparison_acc,
        "true false": baseline_all_unseen_true_false_acc
    }
    lyr18_baseline_linear_probes_acc_on_unseen_single_topic_data_groupings_row_dicts.append(baseline_single_topic_acc_row_dict)
    lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_row_dicts.append({
        col_nm: (ttpd_single_topic_acc_row_dict[col_nm] if col_nm == "scenario" else ttpd_single_topic_acc_row_dict[col_nm] - baseline_single_topic_acc_row_dict[col_nm]) for col_nm in ttpd_single_topic_acc_row_dict.keys()
    })

In [43]:
lyr18_probes_acc_on_unseen_multi_topic_data_groupings_df = pd.DataFrame(lyr18_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts)
lyr18_baseline_linear_probes_acc_on_unseen_multi_topic_data_groupings_df = pd.DataFrame(lyr18_baseline_linear_probes_acc_on_unseen_multi_topic_data_groupings_row_dicts)
lyr18_probes_acc_on_unseen_single_topic_data_groupings_df = pd.DataFrame(lyr18_probes_acc_on_unseen_single_topic_data_groupings_row_dicts)
lyr18_baseline_linear_probes_acc_on_unseen_single_topic_data_groupings_df = pd.DataFrame(lyr18_baseline_linear_probes_acc_on_unseen_single_topic_data_groupings_row_dicts)

lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_df = pd.DataFrame(lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_row_dicts)
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_df = pd.DataFrame(lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_row_dicts)

In [44]:
lyr18_probes_acc_on_unseen_multi_topic_data_groupings_df

,scenario,all,en_affirm,en_negated,conj,disj,de_affirm,de_negated
0,animal_class__affirmative,0.598928,0.840160,0.640354,0.642321,0.580667,0.723333,0.481605
1,animal_class__conjunction,0.616058,0.838017,0.660562,0.749285,0.594000,0.693333,0.498328
2,animal_class__disjunction,0.646416,0.856015,0.509946,0.716108,0.598400,0.636667,0.548495
3,animal_class__negated,0.622431,0.876539,0.837829,0.634317,0.511000,0.706667,0.675585
4,cities__affirmative,0.573471,0.683423,0.650142,0.593547,0.489667,0.656667,0.484950
5,cities__conjunction,0.679085,0.882223,0.748974,0.782400,0.549000,0.750000,0.578595
6,cities__disjunction,0.615186,0.801389,0.491632,0.674837,0.668800,0.583333,0.511706
7,cities__negated,0.556986,0.641932,0.779174,0.529265,0.488333,0.566667,0.709030
8,element_symb__affirmative,0.701161,0.903388,0.525734,0.821911,0.502667,0.820000,0.541806
9,element_symb__conjunction,0.628308,0.694664,0.524155,0.817896,0.604000,0.783333,0.515050
10,element_symb__disjunction,0.575339,0.622987,0.565204,0.585043,0.609200,0.666667,0.441472
11,element_symb__negated,0.533518,0.292390,0.875210,0.477489,0.497000,0.456667,0.762542
12,facts__affirmative,0.676092,0.924021,0.520051,0.845673,0.539000,0.790000,0.438127
13,facts__conjunction,0.574209,0.622040,0.508368,0.830475,0.508000,0.650000,0.518395
14,facts__disjunction,0.557769,0.753710,0.508052,0.661581,0.569600,0.606667,0.484950
15,facts__negated,0.556267,0.724661,0.869148,0.512756,0.498000,0.570000,0.672241
16,inventors__affirmative,0.672174,0.830858,0.709504,0.745623,0.624667,0.806667,0.545151
17,inventors__conjunction,0.545092,0.596148,0.514367,0.713265,0.503000,0.640000,0.494983
18,inventors__disjunction,0.577730,0.606252,0.506473,0.766883,0.573600,0.526667,0.501672
19,inventors__negated,0.465199,0.211241,0.649402,0.510255,0.476000,0.396667,0.635452
20,ambiguous_lie,0.505988,0.501105,0.511209,0.455978,0.499333,0.520000,0.508361
21,ambiguous_truthful_reply,0.469807,0.428165,0.491632,0.467984,0.511000,0.426667,0.541806
22,honest_reply_despite_incentive_to_lie,0.499688,0.507105,0.493211,0.510255,0.499000,0.513333,0.481605
23,unambiguous_lie,0.534747,0.598990,0.683612,0.513507,0.497000,0.593333,0.575251
24,unambiguous_truthful_reply,0.524016,0.502684,0.502684,0.523512,0.502000,0.486667,0.508361
25,larger_than,0.706914,0.937480,0.528576,0.854927,0.600667,0.843333,0.484950
26,smaller_than,0.645057,0.872750,0.683612,0.753627,0.633000,0.726667,0.528428
27,sp_en_trans__negated,0.493253,0.413641,0.821898,0.459980,0.498000,0.433333,0.836120
28,sp_en_trans__affirmative,0.642989,0.879844,0.697506,0.695598,0.632000,0.763333,0.528428
29,sp_en_trans__conjunction,0.623397,0.749921,0.635302,0.825043,0.587667,0.746667,0.518395
30,sp_en_trans__disjunction,0.565090,0.628039,0.554784,0.594047,0.519200,0.576667,0.525084
31,common_claim_true_false,0.649682,0.898011,0.632775,0.649575,0.504667,0.783333,0.605351
32,counterfact_true_false,0.789570,0.948847,0.662457,0.883942,0.507000,0.826667,0.618729
33,animal_class__affirmative+negated,0.652084,0.909424,0.850150,0.679090,0.609000,0.763333,0.715719
34,animal_class__affirmative+disjunction,0.616356,0.858142,0.654563,0.678089,0.610400,0.733333,0.471572
35,animal_class__negated+conjunction,0.630521,0.865172,0.704296,0.765009,0.593000,0.723333,0.541806
36,animal_class__affirmative+negated+conjunction+...,0.646796,0.887779,0.779887,0.738708,0.644400,0.743333,0.605351
37,cities__affirmative+negated,0.623329,0.845003,0.828247,0.616808,0.576333,0.740000,0.765886
38,cities__affirmative+disjunction,0.587876,0.719330,0.660562,0.645823,0.589600,0.706667,0.491639
39,cities__negated+conjunction,0.675916,0.910957,0.675643,0.755200,0.605000,0.766667,0.672241
40,cities__affirmative+negated+conjunction+disjun...,0.627967,0.816278,0.704967,0.686400,0.662000,0.743333,0.682274
41,element_symb__affirmative+negated,0.661379,0.909091,0.902382,0.638069,0.539333,0.740000,0.752508
42,element_symb__affirmative+disjunction,0.643407,0.899363,0.695611,0.648074,0.628800,0.763333,0.545151
43,element_symb__negated+conjunction,0.647982,0.630249,0.885273,0.672956,0.577333,0.730000,0.826087
44,element_symb__affirmative+negated+conjunction+...,0.706974,0.921503,0.904394,0.668382,0.643200,0.796667,0.779264
45,facts__affirmative+negated,0.625623,0.909823,0.920568,0.579040,0.534333,0.746667,0.759197
46,facts__affirmative+disjunction,0.711958,0.926708,0.749290,0.861181,0.553200,0.753333,0.591973
47,facts__negated+conjunction,0.693473,0.925166,0.954720,0.750429,0.597667,0.776667,0.809365
48,facts__affirmative+negated+conjunction+disjunc...,0.676826,0.930929,0.945510,0.736707,0.548800,0.770000,0.775920
49,inventors__affirmative+negated,0.621356,0.845346,0.876494,0.570785,0.530667,0.683333,0.759197
50,inventors__affirmative+disjunction,0.681886,0.850054,0.708557,0.797399,0.540000,0.826667,0.575251
51,inventors__negated+conjunction,0.542446,0.489738,0.874683,0.503716,0.496000,0.520000,0.742475
52,inventors__affirmative+negated+conjunction+dis...,0.661424,0.870337,0.506338,0.794454,0.620400,0.796667,0.518395
53,sp_en_trans__affirmative+negated,0.674909,0.910060,0.853893,0.641571,0.561333,0.803333,0.705686
54,sp_en_trans__affirmative+disjunction,0.579624,0.854604,0.580991,0.599050,0.504400,0.686667,0.474916
55,sp_en_trans__negated+conjunction,0.570426,0.481844,0.878066,0.580046,0.503333,0.523333,0.849498
56,sp_en_trans__affirmative+negated+conjunction+d...,0.690017,0.910060,0.889797,0.559748,0.513200,0.816667,0.729097
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.564910,0.821282,0.578781,0.523012,0.493667,0.660000,0.511706
58,animal_class+facts+inventors__affirmative+nega...,0.728863,0.976424,0.877210,0.845476,0.568667,0.806667,0.712375
59,animal_class+facts+inventors__affirmative+nega...,0.726494,0.976916,0.943517,0.841921,0.509000,0.796667,0.732441

In [45]:
lyr18_probes_acc_on_unseen_multi_topic_data_groupings_df.describe()

,all,en_affirm,en_negated,conj,disj,de_affirm,de_negated
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,0.618207,0.765337,0.697965,0.669601,0.555470,0.686444,0.606633
std,0.069084,0.181112,0.149788,0.119410,0.053205,0.116672,0.117852
min,0.465199,0.211241,0.491632,0.455978,0.476000,0.396667,0.438127
25%,0.569092,0.629697,0.548232,0.579794,0.504133,0.603333,0.510870
50%,0.624510,0.845174,0.683612,0.670669,0.548900,0.728333,0.561873
75%,0.672858,0.904814,0.851086,0.757652,0.598967,0.771667,0.713211
max,0.789570,0.976916,0.954720,0.883942,0.668800,0.843333,0.849498

In [46]:
lyr18_baseline_linear_probes_acc_on_unseen_multi_topic_data_groupings_df

,scenario,all,en_affirm,en_negated,conj,disj,de_affirm,de_negated
0,animal_class__affirmative,0.628325,0.864469,0.692138,0.674837,0.647667,0.730000,0.478261
1,animal_class__conjunction,0.727648,0.920429,0.735081,0.885363,0.515667,0.760000,0.628763
2,animal_class__disjunction,0.512028,0.525103,0.508052,0.514757,0.646000,0.526667,0.521739
3,animal_class__negated,0.663155,0.799179,0.864469,0.663332,0.504667,0.716667,0.782609
4,cities__affirmative,0.631684,0.763615,0.522577,0.685093,0.521333,0.740000,0.347826
5,cities__conjunction,0.705427,0.916009,0.520366,0.794800,0.577667,0.800000,0.468227
6,cities__disjunction,0.628012,0.805494,0.578781,0.564032,0.729600,0.720000,0.525084
7,cities__negated,0.633931,0.848121,0.828845,0.592796,0.541333,0.786667,0.789298
8,element_symb__affirmative,0.583103,0.796713,0.633723,0.571786,0.502000,0.763333,0.515050
9,element_symb__conjunction,0.680610,0.929586,0.500789,0.842767,0.530667,0.820000,0.461538
10,element_symb__disjunction,0.688209,0.830123,0.715819,0.819910,0.730000,0.706667,0.568562
11,element_symb__negated,0.484982,0.435744,0.828581,0.460230,0.408000,0.366667,0.839465
12,facts__affirmative,0.585750,0.664620,0.581307,0.490245,0.502000,0.743333,0.598662
13,facts__conjunction,0.699663,0.914746,0.518472,0.708405,0.515667,0.760000,0.608696
14,facts__disjunction,0.648584,0.825703,0.531418,0.707854,0.630800,0.670000,0.488294
15,facts__negated,0.546915,0.604989,0.884881,0.514257,0.498000,0.553333,0.685619
16,inventors__affirmative,0.730953,0.931184,0.830123,0.731116,0.653333,0.833333,0.635452
17,inventors__conjunction,0.562347,0.557626,0.508368,0.923957,0.538667,0.650000,0.521739
18,inventors__disjunction,0.521091,0.519103,0.492895,0.578539,0.729200,0.533333,0.478261
19,inventors__negated,0.542572,0.530786,0.907280,0.501501,0.505000,0.570000,0.802676
20,ambiguous_lie,0.499026,0.492895,0.507105,0.489495,0.502000,0.483333,0.518395
21,ambiguous_truthful_reply,0.500597,0.507105,0.492895,0.510505,0.498000,0.516667,0.481605
22,honest_reply_despite_incentive_to_lie,0.500753,0.507105,0.492895,0.510505,0.498000,0.516667,0.481605
23,unambiguous_lie,0.498741,0.492895,0.507105,0.489495,0.502000,0.483333,0.518395
24,unambiguous_truthful_reply,0.500303,0.507105,0.492895,0.510505,0.498000,0.516667,0.481605
25,larger_than,0.639092,0.856331,0.457215,0.616558,0.538667,0.773333,0.461538
26,smaller_than,0.692717,0.906536,0.833281,0.689345,0.627667,0.760000,0.628763
27,sp_en_trans__negated,0.412905,0.127881,0.769996,0.487994,0.476667,0.233333,0.799331
28,sp_en_trans__affirmative,0.702931,0.907216,0.654247,0.765133,0.563333,0.786667,0.468227
29,sp_en_trans__conjunction,0.599285,0.627408,0.511209,0.844768,0.604333,0.803333,0.561873
30,sp_en_trans__disjunction,0.564441,0.544048,0.195769,0.674587,0.638800,0.526667,0.314381
31,common_claim_true_false,0.739791,0.931481,0.796337,0.888444,0.525667,0.836667,0.612040
32,counterfact_true_false,0.710386,0.917272,0.423429,0.793647,0.650333,0.843333,0.434783
33,animal_class__affirmative+negated,0.651068,0.895438,0.808192,0.730615,0.579333,0.756667,0.729097
34,animal_class__affirmative+disjunction,0.650506,0.914752,0.512472,0.788894,0.682400,0.803333,0.458194
35,animal_class__negated+conjunction,0.750502,0.946321,0.888778,0.900515,0.512333,0.800000,0.762542
36,animal_class__affirmative+negated+conjunction+...,0.747384,0.930736,0.795871,0.865066,0.708800,0.796667,0.678930
37,cities__affirmative+negated,0.657081,0.845601,0.839617,0.593297,0.585000,0.776667,0.772575
38,cities__affirmative+disjunction,0.661342,0.749850,0.512157,0.633817,0.726000,0.756667,0.377926
39,cities__negated+conjunction,0.704151,0.893274,0.706164,0.846000,0.577667,0.776667,0.722408
40,cities__affirmative+negated+conjunction+disjun...,0.736364,0.891083,0.770796,0.871200,0.754800,0.833333,0.722408
41,element_symb__affirmative+negated,0.672694,0.784636,0.919826,0.826413,0.523333,0.743333,0.836120
42,element_symb__affirmative+disjunction,0.686703,0.827910,0.692769,0.857429,0.732000,0.793333,0.535117
43,element_symb__negated+conjunction,0.707569,0.904642,0.895673,0.897656,0.549333,0.763333,0.765886
44,element_symb__affirmative+negated+conjunction+...,0.697404,0.739685,0.911439,0.879074,0.718000,0.750000,0.829431
45,facts__affirmative+negated,0.731372,0.955871,0.934766,0.792146,0.532333,0.846667,0.752508
46,facts__affirmative+disjunction,0.669407,0.754797,0.572782,0.861181,0.632800,0.726667,0.615385
47,facts__negated+conjunction,0.706040,0.904010,0.927859,0.715266,0.510333,0.736667,0.775920
48,facts__affirmative+negated+conjunction+disjunc...,0.734150,0.938987,0.932847,0.786735,0.633200,0.783333,0.779264
49,inventors__affirmative+negated,0.706920,0.950742,0.903296,0.717609,0.617000,0.840000,0.765886
50,inventors__affirmative+disjunction,0.716153,0.944223,0.733186,0.644572,0.725600,0.836667,0.595318
51,inventors__negated+conjunction,0.710009,0.888538,0.884824,0.925386,0.520000,0.813333,0.759197
52,inventors__affirmative+negated+conjunction+dis...,0.742345,0.916697,0.907642,0.899085,0.757600,0.826667,0.749164
53,sp_en_trans__affirmative+negated,0.623205,0.599716,0.890508,0.589045,0.552667,0.656667,0.799331
54,sp_en_trans__affirmative+disjunction,0.683557,0.731959,0.319230,0.806403,0.634400,0.736667,0.367893
55,sp_en_trans__negated+conjunction,0.660740,0.606883,0.871667,0.806747,0.588667,0.770000,0.812709
56,sp_en_trans__affirmative+negated+conjunction+d...,0.711913,0.890508,0.688233,0.838765,0.617200,0.790000,0.745819
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.501463,0.518472,0.492895,0.510505,0.498000,0.516667,0.481605
58,animal_class+facts+inventors__affirmative+nega...,0.760918,0.977407,0.976424,0.939952,0.518667,0.836667,0.829431
59,animal_class+facts+inventors__affirmative+nega...,0.768171,0.980354,0.982809,0.854927,0.595667,0.850000,0.822742

In [47]:
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_df

,scenario,all,en_affirm,en_negated,conj,disj,de_affirm,de_negated
0,animal_class__affirmative,-0.029397,-0.024309,-0.051784,-0.032516,-0.067000,-0.006667,0.003344
1,animal_class__conjunction,-0.111591,-0.082412,-0.074518,-0.136078,0.078333,-0.066667,-0.130435
2,animal_class__disjunction,0.134387,0.330913,0.001895,0.201351,-0.047600,0.110000,0.026756
3,animal_class__negated,-0.040724,0.077360,-0.026640,-0.029015,0.006333,-0.010000,-0.107023
4,cities__affirmative,-0.058214,-0.080192,0.127566,-0.091546,-0.031667,-0.083333,0.137124
5,cities__conjunction,-0.026342,-0.033786,0.228608,-0.012400,-0.028667,-0.050000,0.110368
6,cities__disjunction,-0.012825,-0.004105,-0.087149,0.110805,-0.060800,-0.136667,-0.013378
7,cities__negated,-0.076945,-0.206189,-0.049671,-0.063532,-0.053000,-0.220000,-0.080268
8,element_symb__affirmative,0.118058,0.106676,-0.107989,0.250125,0.000667,0.056667,0.026756
9,element_symb__conjunction,-0.052302,-0.234923,0.023366,-0.024871,0.073333,-0.036667,0.053512
10,element_symb__disjunction,-0.112870,-0.207136,-0.150616,-0.234867,-0.120800,-0.040000,-0.127090
11,element_symb__negated,0.048535,-0.143353,0.046629,0.017259,0.089000,0.090000,-0.076923
12,facts__affirmative,0.090342,0.259401,-0.061257,0.355428,0.037000,0.046667,-0.160535
13,facts__conjunction,-0.125454,-0.292706,-0.010104,0.122070,-0.007667,-0.110000,-0.090301
14,facts__disjunction,-0.090815,-0.071992,-0.023366,-0.046273,-0.061200,-0.063333,-0.003344
15,facts__negated,0.009352,0.119672,-0.015733,-0.001501,0.000000,0.016667,-0.013378
16,inventors__affirmative,-0.058779,-0.100326,-0.120619,0.014507,-0.028667,-0.026667,-0.090301
17,inventors__conjunction,-0.017255,0.038522,0.005999,-0.210692,-0.035667,-0.010000,-0.026756
18,inventors__disjunction,0.056639,0.087149,0.013578,0.188344,-0.155600,-0.006667,0.023411
19,inventors__negated,-0.077373,-0.319545,-0.257878,0.008754,-0.029000,-0.173333,-0.167224
20,ambiguous_lie,0.006962,0.008210,0.004105,-0.033517,-0.002667,0.036667,-0.010033
21,ambiguous_truthful_reply,-0.030790,-0.078939,-0.001263,-0.042521,0.013000,-0.090000,0.060201
22,honest_reply_despite_incentive_to_lie,-0.001065,0.000000,0.000316,-0.000250,0.001000,-0.003333,0.000000
23,unambiguous_lie,0.036006,0.106094,0.176508,0.024012,-0.005000,0.110000,0.056856
24,unambiguous_truthful_reply,0.023713,-0.004421,0.009788,0.013007,0.004000,-0.030000,0.026756
25,larger_than,0.067821,0.081149,0.071361,0.238369,0.062000,0.070000,0.023411
26,smaller_than,-0.047660,-0.033786,-0.149668,0.064282,0.005333,-0.033333,-0.100334
27,sp_en_trans__negated,0.080348,0.285759,0.051902,-0.028014,0.021333,0.200000,0.036789
28,sp_en_trans__affirmative,-0.059942,-0.027373,0.043259,-0.069535,0.068667,-0.023333,0.060201
29,sp_en_trans__conjunction,0.024112,0.122513,0.124092,-0.019726,-0.016667,-0.056667,-0.043478
30,sp_en_trans__disjunction,0.000649,0.083991,0.359015,-0.080540,-0.119600,0.050000,0.210702
31,common_claim_true_false,-0.090109,-0.033470,-0.163562,-0.238869,-0.021000,-0.053333,-0.006689
32,counterfact_true_false,0.079184,0.031576,0.239027,0.090295,-0.143333,-0.016667,0.183946
33,animal_class__affirmative+negated,0.001016,0.013986,0.041958,-0.051526,0.029667,0.006667,-0.013378
34,animal_class__affirmative+disjunction,-0.034150,-0.056610,0.142090,-0.110805,-0.072000,-0.070000,0.013378
35,animal_class__negated+conjunction,-0.119981,-0.081149,-0.184482,-0.135506,0.080667,-0.076667,-0.220736
36,animal_class__affirmative+negated+conjunction+...,-0.100587,-0.042957,-0.015984,-0.126358,-0.064400,-0.053333,-0.073579
37,cities__affirmative+negated,-0.033752,-0.000598,-0.011370,0.023512,-0.008667,-0.036667,-0.006689
38,cities__affirmative+disjunction,-0.073465,-0.030521,0.148405,0.012006,-0.136400,-0.050000,0.113712
39,cities__negated+conjunction,-0.028234,0.017682,-0.030521,-0.090800,0.027333,-0.010000,-0.050167
40,cities__affirmative+negated+conjunction+disjun...,-0.108398,-0.074806,-0.065829,-0.184800,-0.092800,-0.090000,-0.040134
41,element_symb__affirmative+negated,-0.011316,0.124455,-0.017444,-0.188344,0.016000,-0.003333,-0.083612
42,element_symb__affirmative+disjunction,-0.043296,0.071453,0.002842,-0.209355,-0.103200,-0.030000,0.010033
43,element_symb__negated+conjunction,-0.059587,-0.274392,-0.010399,-0.224700,0.028000,-0.033333,0.060201
44,element_symb__affirmative+negated+conjunction+...,0.009570,0.181818,-0.007045,-0.210692,-0.074800,0.046667,-0.050167
45,facts__affirmative+negated,-0.105749,-0.046048,-0.014198,-0.213107,0.002000,-0.100000,0.006689
46,facts__affirmative+disjunction,0.042551,0.171911,0.176508,0.000000,-0.079600,0.026667,-0.023411
47,facts__negated+conjunction,-0.012567,0.021156,0.026861,0.035163,0.087333,0.040000,0.033445
48,facts__affirmative+negated+conjunction+disjunc...,-0.057324,-0.008058,0.012663,-0.050029,-0.084400,-0.013333,-0.003344
49,inventors__affirmative+negated,-0.085564,-0.105397,-0.026802,-0.146823,-0.086333,-0.156667,-0.006689
50,inventors__affirmative+disjunction,-0.034267,-0.094169,-0.024629,0.152826,-0.185600,-0.010000,-0.020067
51,inventors__negated+conjunction,-0.167563,-0.398800,-0.010141,-0.421670,-0.024000,-0.293333,-0.016722
52,inventors__affirmative+negated+conjunction+dis...,-0.080921,-0.046360,-0.401304,-0.104631,-0.137200,-0.030000,-0.230769
53,sp_en_trans__affirmative+negated,0.051704,0.310345,-0.036616,0.052526,0.008667,0.146667,-0.093645
54,sp_en_trans__affirmative+disjunction,-0.103933,0.122645,0.261762,-0.207354,-0.130000,-0.050000,0.107023
55,sp_en_trans__negated+conjunction,-0.090314,-0.125039,0.006399,-0.226701,-0.085333,-0.246667,0.036789
56,sp_en_trans__affirmative+negated+conjunction+d...,-0.021897,0.019552,0.201564,-0.279017,-0.104000,0.026667,-0.016722
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.063447,0.302810,0.085886,0.012506,-0.004333,0.143333,0.030100
58,animal_class+facts+inventors__affirmative+nega...,-0.032055,-0.000982,-0.099214,-0.094476,0.050000,-0.030000,-0.117057
59,animal_class+facts+inventors__affirmative+nega...,-0.041677,-0.003438,-0.039293,-0.013007,-0.086667,-0.053333,-0.090301

In [48]:
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_multi_topic_data_groupings_df.describe()

,all,en_affirm,en_negated,conj,disj,de_affirm,de_negated
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,-0.027044,-0.004525,0.004781,-0.044980,-0.030094,-0.026000,-0.015886
std,0.065080,0.148862,0.124110,0.141573,0.066574,0.088112,0.086101
min,-0.167563,-0.398800,-0.401304,-0.421670,-0.185600,-0.293333,-0.230769
25%,-0.077052,-0.079252,-0.041887,-0.135649,-0.080800,-0.058333,-0.077759
50%,-0.032903,-0.004263,-0.008574,-0.033017,-0.022500,-0.030000,-0.008361
75%,0.009406,0.081860,0.044101,0.015195,0.009750,0.019167,0.027592
max,0.134387,0.330913,0.359015,0.355428,0.089000,0.200000,0.210702

In [49]:
lyr18_probes_acc_on_unseen_single_topic_data_groupings_df

,scenario,animal class,cities,element symbols,facts,inventors,spanish english translation,real world scenarios,relative comparison,true false
0,animal_class__affirmative,0.606804,0.792731,0.643342,0.600180,0.540795,0.611726,0.688742,0.621970,0.569232
1,animal_class__conjunction,0.687500,0.845187,0.626359,0.629446,0.565900,0.643805,0.562914,0.659343,0.577745
2,animal_class__disjunction,0.764009,0.736149,0.671196,0.567762,0.581590,0.676438,0.649007,0.780051,0.622041
3,animal_class__negated,0.594146,0.821022,0.622962,0.674471,0.620816,0.687500,0.562914,0.511616,0.601609
4,cities__affirmative,0.633754,0.679188,0.569293,0.579919,0.530335,0.497235,0.589404,0.543939,0.569644
5,cities__conjunction,0.783613,0.910356,0.664402,0.651959,0.584205,0.683075,0.629139,0.842172,0.641676
6,cities__disjunction,0.637955,0.700218,0.730299,0.568663,0.600941,0.653208,0.543046,0.566162,0.606250
7,cities__negated,0.525210,0.587368,0.537364,0.601081,0.617155,0.625553,0.529801,0.500000,0.553084
8,element_symb__affirmative,0.714986,0.722593,0.678849,0.675371,0.601987,0.739491,0.735099,0.758081,0.696957
9,element_symb__conjunction,0.701681,0.657760,0.655350,0.667717,0.581067,0.741704,0.582781,0.883586,0.587466
10,element_symb__disjunction,0.630952,0.583890,0.567901,0.606033,0.563808,0.612832,0.569536,0.617677,0.564453
11,element_symb__negated,0.509804,0.519057,0.384137,0.506529,0.650628,0.590155,0.463576,0.586111,0.529000
12,facts__affirmative,0.721289,0.786837,0.691576,0.604819,0.588912,0.684735,0.761589,0.823485,0.649228
13,facts__conjunction,0.581933,0.604519,0.701087,0.615921,0.552301,0.720686,0.443709,0.502273,0.564810
14,facts__disjunction,0.703081,0.689194,0.578125,0.558977,0.563285,0.547566,0.556291,0.532071,0.535838
15,facts__negated,0.537815,0.700786,0.590353,0.560241,0.587343,0.674226,0.569536,0.500253,0.533778
16,inventors__affirmative,0.658964,0.904126,0.669158,0.607834,0.669987,0.505531,0.609272,0.847980,0.633822
17,inventors__conjunction,0.635854,0.597446,0.594429,0.598829,0.546034,0.517699,0.516556,0.722727,0.511067
18,inventors__disjunction,0.509804,0.669155,0.542120,0.562359,0.686969,0.653208,0.463576,0.500000,0.570934
19,inventors__negated,0.475490,0.413949,0.487092,0.492571,0.521912,0.473451,0.523179,0.500000,0.462624
20,ambiguous_lie,0.478291,0.503340,0.455163,0.484466,0.535042,0.454093,0.511278,0.500000,0.512495
21,ambiguous_truthful_reply,0.485994,0.477210,0.467391,0.510581,0.453452,0.439712,0.523438,0.486616,0.466084
22,honest_reply_despite_incentive_to_lie,0.493697,0.498625,0.512908,0.486718,0.533473,0.500000,0.517241,0.500000,0.498435
23,unambiguous_lie,0.525910,0.654028,0.518342,0.525439,0.546548,0.498341,0.627451,0.518182,0.522382
24,unambiguous_truthful_reply,0.506303,0.501572,0.487092,0.515534,0.470711,0.576881,0.468750,0.671212,0.514170
25,larger_than,0.692577,0.777210,0.778533,0.694732,0.674163,0.740044,0.774834,0.808586,0.689762
26,smaller_than,0.829832,0.846365,0.690217,0.645205,0.602510,0.621128,0.807947,0.789899,0.602708
27,sp_en_trans__negated,0.467787,0.598035,0.522418,0.499325,0.527197,0.506878,0.443709,0.457576,0.479815
28,sp_en_trans__affirmative,0.682073,0.842829,0.708560,0.650608,0.548640,0.651307,0.708609,0.613636,0.617949
29,sp_en_trans__conjunction,0.698179,0.750295,0.756114,0.651508,0.695607,0.542049,0.496689,0.578283,0.600209
30,sp_en_trans__disjunction,0.530812,0.592338,0.550951,0.545700,0.580544,0.644495,0.509934,0.582071,0.559098
31,common_claim_true_false,0.528711,0.728291,0.697011,0.659163,0.592050,0.714049,0.715232,0.500758,0.657677
32,counterfact_true_false,0.746499,0.866994,0.696332,0.689779,0.658473,0.716814,0.827815,0.941162,0.745169
33,animal_class__affirmative+negated,0.585455,0.853635,0.732337,0.717244,0.652197,0.753319,0.695364,0.566919,0.622755
34,animal_class__affirmative+disjunction,0.717277,0.828684,0.672554,0.619541,0.546025,0.592920,0.754967,0.643939,0.583375
35,animal_class__negated+conjunction,0.641361,0.877210,0.631114,0.657362,0.578975,0.684735,0.609272,0.640909,0.593124
36,animal_class__affirmative+negated+conjunction+...,0.810000,0.878978,0.699049,0.701036,0.603556,0.725664,0.668874,0.627273,0.608859
37,cities__affirmative+negated,0.644958,0.577216,0.745245,0.683926,0.664749,0.787058,0.596026,0.561111,0.613088
38,cities__affirmative+disjunction,0.680672,0.733678,0.696332,0.613237,0.540795,0.578540,0.609272,0.607071,0.566678
39,cities__negated+conjunction,0.761204,0.880725,0.766304,0.712292,0.632845,0.716261,0.668874,0.765404,0.645466
40,cities__affirmative+negated+conjunction+disjun...,0.770308,0.970000,0.737092,0.692931,0.626046,0.731195,0.715232,0.650000,0.605289
41,element_symb__affirmative+negated,0.633053,0.827505,0.680909,0.661414,0.654812,0.790929,0.562914,0.592172,0.640523
42,element_symb__affirmative+disjunction,0.691176,0.799018,0.749364,0.644755,0.599372,0.673673,0.748344,0.677778,0.614050
43,element_symb__negated+conjunction,0.667367,0.756189,0.553435,0.624043,0.648536,0.732301,0.662252,0.711616,0.624403
44,element_symb__affirmative+negated+conjunction+...,0.712885,0.861493,0.690000,0.711842,0.675732,0.838496,0.708609,0.703535,0.680370
45,facts__affirmative+negated,0.620448,0.791749,0.720788,0.526843,0.628138,0.764381,0.715232,0.574242,0.599934
46,facts__affirmative+disjunction,0.779412,0.922986,0.663043,0.648276,0.633368,0.700774,0.748344,0.870707,0.671088
47,facts__negated+conjunction,0.743697,0.875835,0.739810,0.786207,0.687238,0.816372,0.847682,0.678788,0.656368
48,facts__affirmative+negated+conjunction+disjunc...,0.725490,0.866994,0.713315,0.707071,0.671025,0.801991,0.821192,0.702778,0.637447
49,inventors__affirmative+negated,0.596639,0.745972,0.627717,0.626745,0.599091,0.794248,0.562914,0.504545,0.609354
50,inventors__affirmative+disjunction,0.707283,0.900982,0.650815,0.612337,0.685885,0.522677,0.629139,0.868687,0.643461
51,inventors__negated+conjunction,0.549720,0.642436,0.548234,0.521387,0.505964,0.589049,0.761589,0.501010,0.531526
52,inventors__affirmative+negated+conjunction+dis...,0.628151,0.739686,0.762228,0.606033,0.650000,0.735619,0.629139,0.887374,0.623002
53,sp_en_trans__affirmative+negated,0.640056,0.816896,0.722147,0.675822,0.642782,0.725455,0.748344,0.571212,0.665596
54,sp_en_trans__affirmative+disjunction,0.588235,0.707662,0.625000,0.552004,0.544979,0.647799,0.688742,0.525000,0.566760
55,sp_en_trans__negated+conjunction,0.525210,0.647544,0.696332,0.533994,0.609310,0.549266,0.536424,0.882828,0.523233
56,sp_en_trans__affirmative+negated+conjunction+d...,0.629552,0.790570,0.721467,0.667267,0.640167,0.760000,0.834437,0.621970,0.687675
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.589636,0.672299,0.526495,0.570014,0.543933,0.559735,0.833333,0.500758,0.558329
58,animal_class+facts+inventors__affirmative+nega...,0.568333,0.897642,0.686141,0.641068,0.710000,0.728429,0.847682,0.854798,0.697232
59,animal_class+facts+inventors__affirmative+nega...,0.725455,0.920629,0.705163,0.639672,0.564545,0.782633,0.500000,0.916162,0.690402

In [50]:
lyr18_probes_acc_on_unseen_single_topic_data_groupings_df.describe()

,animal class,cities,element symbols,facts,inventors,spanish english translation,real world scenarios,relative comparison,true false
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,0.636906,0.739048,0.641814,0.614063,0.598574,0.653819,0.636446,0.649268,0.596777
std,0.094262,0.132850,0.091259,0.068886,0.058142,0.101841,0.115169,0.137284,0.062378
min,0.467787,0.413949,0.384137,0.484466,0.453452,0.439712,0.443709,0.457576,0.462624
25%,0.563680,0.652407,0.568945,0.561830,0.548117,0.578125,0.541391,0.523295,0.558906
50%,0.636905,0.748134,0.670177,0.617731,0.599232,0.673949,0.628295,0.619823,0.602159
75%,0.708683,0.848183,0.706012,0.662877,0.648902,0.731471,0.720199,0.759912,0.640811
max,0.829832,0.970000,0.778533,0.786207,0.710000,0.838496,0.847682,0.941162,0.745169

In [51]:
lyr18_baseline_linear_probes_acc_on_unseen_single_topic_data_groupings_df

,scenario,animal class,cities,element symbols,facts,inventors,spanish english translation,real world scenarios,relative comparison,true false
0,animal_class__affirmative,0.704905,0.834185,0.675272,0.618640,0.559100,0.673119,0.596026,0.614899,0.598588
1,animal_class__conjunction,0.705819,0.892731,0.693614,0.706439,0.627092,0.727323,0.728477,0.903535,0.693964
2,animal_class__disjunction,0.591595,0.527505,0.527174,0.559658,0.548640,0.529314,0.443709,0.500000,0.503131
3,animal_class__negated,0.572785,0.852652,0.680027,0.611887,0.619770,0.626659,0.569536,0.854040,0.625968
4,cities__affirmative,0.636555,0.682248,0.611413,0.578118,0.514121,0.570796,0.741722,0.546970,0.648542
5,cities__conjunction,0.714286,0.710468,0.740489,0.688429,0.610879,0.713496,0.801325,0.938636,0.683007
6,cities__disjunction,0.681373,0.738562,0.694973,0.569113,0.603033,0.571350,0.642384,0.526263,0.628000
7,cities__negated,0.588936,0.682805,0.753397,0.618640,0.674686,0.812500,0.768212,0.504293,0.629511
8,element_symb__affirmative,0.648459,0.652849,0.602644,0.651959,0.506799,0.617257,0.701987,0.571970,0.568930
9,element_symb__conjunction,0.719188,0.778585,0.588477,0.648357,0.622385,0.698009,0.596026,0.594697,0.681716
10,element_symb__disjunction,0.820028,0.883301,0.808642,0.615489,0.593619,0.788717,0.549669,0.720202,0.654062
11,element_symb__negated,0.436975,0.586837,0.315708,0.507879,0.631276,0.510509,0.609272,0.502020,0.465892
12,facts__affirmative,0.615546,0.531631,0.585598,0.557229,0.483264,0.633296,0.476821,0.714646,0.582908
13,facts__conjunction,0.629552,0.670334,0.703125,0.650203,0.608264,0.744469,0.801325,0.790152,0.701022
14,facts__disjunction,0.765406,0.740472,0.684103,0.613016,0.553870,0.591261,0.649007,0.742172,0.629044
15,facts__negated,0.543417,0.633399,0.584918,0.551807,0.582636,0.692478,0.549669,0.502778,0.528890
16,inventors__affirmative,0.703782,0.866601,0.747962,0.701036,0.658699,0.805863,0.536424,0.844444,0.701928
17,inventors__conjunction,0.673669,0.654813,0.704484,0.596128,0.558074,0.625553,0.470199,0.571212,0.533696
18,inventors__disjunction,0.619048,0.555206,0.673234,0.555606,0.529745,0.531527,0.569536,0.500000,0.505465
19,inventors__negated,0.560924,0.655599,0.540082,0.586673,0.540505,0.590155,0.609272,0.527778,0.522519
20,ambiguous_lie,0.506303,0.501572,0.487092,0.515083,0.466004,0.498894,0.368421,0.500000,0.500000
21,ambiguous_truthful_reply,0.493697,0.498428,0.512908,0.484917,0.533996,0.501106,0.476562,0.500000,0.500000
22,honest_reply_despite_incentive_to_lie,0.493697,0.498428,0.512908,0.484917,0.533996,0.501106,0.537931,0.500000,0.500000
23,unambiguous_lie,0.506303,0.501572,0.487092,0.515083,0.466004,0.498894,0.176471,0.500000,0.500000
24,unambiguous_truthful_reply,0.493697,0.498428,0.512908,0.484917,0.533996,0.501106,0.302083,0.500000,0.500000
25,larger_than,0.715686,0.663458,0.548913,0.628546,0.527720,0.552544,0.562914,0.647475,0.646976
26,smaller_than,0.752101,0.862083,0.758832,0.674471,0.612448,0.728429,0.715232,0.757576,0.663975
27,sp_en_trans__negated,0.483894,0.462083,0.458560,0.458802,0.546548,0.329436,0.403974,0.500000,0.385484
28,sp_en_trans__affirmative,0.773109,0.822593,0.648777,0.618640,0.631276,0.634113,0.794702,0.598232,0.708299
29,sp_en_trans__conjunction,0.724090,0.676228,0.722826,0.614138,0.618724,0.532110,0.794702,0.500000,0.589114
30,sp_en_trans__disjunction,0.468487,0.444204,0.663723,0.521387,0.566423,0.566514,0.496689,0.500253,0.590707
31,common_claim_true_false,0.784314,0.925737,0.679348,0.719946,0.640167,0.763274,0.655629,0.812626,0.708359
32,counterfact_true_false,0.728992,0.759332,0.699049,0.590275,0.682008,0.665376,0.615894,0.834848,0.635056
33,animal_class__affirmative+negated,0.680909,0.852259,0.681386,0.716794,0.644351,0.722345,0.761589,0.646465,0.613665
34,animal_class__affirmative+disjunction,0.869110,0.799607,0.595788,0.669968,0.588912,0.764934,0.490066,0.550758,0.635168
35,animal_class__negated+conjunction,0.657068,0.936149,0.755435,0.737956,0.703452,0.806416,0.761589,0.870202,0.713709
36,animal_class__affirmative+negated+conjunction+...,0.860000,0.945383,0.832880,0.751914,0.693515,0.721792,0.576159,0.951263,0.698303
37,cities__affirmative+negated,0.625350,0.542421,0.785326,0.641603,0.687762,0.818584,0.754967,0.507071,0.666969
38,cities__affirmative+disjunction,0.691176,0.661603,0.719429,0.575867,0.586297,0.592367,0.701987,0.530051,0.684489
39,cities__negated+conjunction,0.791317,0.864981,0.760190,0.695633,0.672594,0.781527,0.814570,0.920202,0.663591
40,cities__affirmative+negated+conjunction+disjun...,0.885854,0.960000,0.897418,0.717244,0.772490,0.860619,0.814570,0.643434,0.726259
41,element_symb__affirmative+negated,0.757703,0.816896,0.710000,0.733904,0.643305,0.855642,0.874172,0.923232,0.608722
42,element_symb__affirmative+disjunction,0.848739,0.861297,0.740458,0.684376,0.614540,0.799226,0.549669,0.880808,0.632586
43,element_symb__negated+conjunction,0.800420,0.925147,0.601781,0.713192,0.730649,0.815819,0.562914,0.881061,0.650601
44,element_symb__affirmative+negated+conjunction+...,0.878852,0.858939,0.790000,0.720396,0.707113,0.888827,0.562914,0.903535,0.634179
45,facts__affirmative+negated,0.770308,0.894303,0.715353,0.656961,0.664749,0.814159,0.867550,0.797727,0.701571
46,facts__affirmative+disjunction,0.745798,0.746365,0.749321,0.600862,0.629184,0.741704,0.622517,0.961111,0.621602
47,facts__negated+conjunction,0.636555,0.822790,0.755435,0.703448,0.657427,0.821350,0.741722,0.815909,0.675262
48,facts__affirmative+negated+conjunction+disjunc...,0.754202,0.848723,0.865489,0.767677,0.718619,0.862832,0.821192,0.940404,0.683583
49,inventors__affirmative+negated,0.763305,0.878193,0.677989,0.714543,0.633636,0.817478,0.761589,0.643182,0.684901
50,inventors__affirmative+disjunction,0.653361,0.864833,0.757473,0.665916,0.572565,0.688053,0.649007,0.701263,0.706487
51,inventors__negated+conjunction,0.785714,0.928487,0.724185,0.689329,0.628231,0.800885,0.841060,0.856818,0.658428
52,inventors__affirmative+negated+conjunction+dis...,0.845238,0.945776,0.816576,0.737956,0.850000,0.885509,0.794702,0.735101,0.700308
53,sp_en_trans__affirmative+negated,0.665966,0.655599,0.626359,0.596578,0.689331,0.716364,0.735099,0.500000,0.625144
54,sp_en_trans__affirmative+disjunction,0.567927,0.654028,0.749321,0.564611,0.646967,0.500000,0.668874,0.810101,0.689845
55,sp_en_trans__negated+conjunction,0.766106,0.777407,0.788043,0.637551,0.658996,0.575472,0.735099,0.935859,0.608667
56,sp_en_trans__affirmative+negated+conjunction+d...,0.636555,0.836542,0.853261,0.716344,0.663180,0.960000,0.642384,0.849747,0.678640
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.495798,0.498428,0.513587,0.499325,0.533996,0.501106,0.791667,0.500000,0.500027
58,animal_class+facts+inventors__affirmative+nega...,0.566667,0.921611,0.761549,0.589316,0.583333,0.844027,0.801325,0.949747,0.722552
59,animal_class+facts+inventors__affirmative+nega...,0.729091,0.924361,0.782609,0.703367,0.680909,0.841814,0.708333,0.928283,0.735171

In [52]:
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_df

,scenario,animal class,cities,element symbols,facts,inventors,spanish english translation,real world scenarios,relative comparison,true false
0,animal_class__affirmative,-0.098101,-0.041454,-0.031929,-0.018460,-0.018305,-0.061394,0.092715,0.007071,-0.029357
1,animal_class__conjunction,-0.018319,-0.047544,-0.067255,-0.076992,-0.061192,-0.083518,-0.165563,-0.244192,-0.116219
2,animal_class__disjunction,0.172414,0.208644,0.144022,0.008104,0.032950,0.147124,0.205298,0.280051,0.118910
3,animal_class__negated,0.021361,-0.031631,-0.057065,0.062584,0.001046,0.060841,-0.006623,-0.342424,-0.024359
4,cities__affirmative,-0.002801,-0.003061,-0.042120,0.001801,0.016213,-0.073562,-0.152318,-0.003030,-0.078898
5,cities__conjunction,0.069328,0.199889,-0.076087,-0.036470,-0.026674,-0.030420,-0.172185,-0.096465,-0.041330
6,cities__disjunction,-0.043417,-0.038344,0.035326,-0.000450,-0.002092,0.081858,-0.099338,0.039899,-0.021750
7,cities__negated,-0.063725,-0.095437,-0.216033,-0.017560,-0.057531,-0.186947,-0.238411,-0.004293,-0.076427
8,element_symb__affirmative,0.066527,0.069745,0.076205,0.023413,0.095188,0.122235,0.033113,0.186111,0.128028
9,element_symb__conjunction,-0.017507,-0.120825,0.066872,0.019361,-0.041318,0.043695,-0.013245,0.288889,-0.094249
10,element_symb__disjunction,-0.189076,-0.299411,-0.240741,-0.009455,-0.029812,-0.175885,0.019868,-0.102525,-0.089608
11,element_symb__negated,0.072829,-0.067780,0.068429,-0.001351,0.019351,0.079646,-0.145695,0.084091,0.063108
12,facts__affirmative,0.105742,0.255206,0.105978,0.047590,0.105649,0.051438,0.284768,0.108838,0.066321
13,facts__conjunction,-0.047619,-0.065815,-0.002038,-0.034282,-0.055962,-0.023783,-0.357616,-0.287879,-0.136211
14,facts__disjunction,-0.062325,-0.051277,-0.105978,-0.054038,0.009414,-0.043695,-0.092715,-0.210101,-0.093206
15,facts__negated,-0.005602,0.067387,0.005435,0.008434,0.004707,-0.018252,0.019868,-0.002525,0.004888
16,inventors__affirmative,-0.044818,0.037525,-0.078804,-0.093201,0.011288,-0.300332,0.072848,0.003535,-0.068106
17,inventors__conjunction,-0.037815,-0.057367,-0.110054,0.002701,-0.012040,-0.107854,0.046358,0.151515,-0.022629
18,inventors__disjunction,-0.109244,0.113949,-0.131114,0.006754,0.157224,0.121681,-0.105960,0.000000,0.065469
19,inventors__negated,-0.085434,-0.241650,-0.052989,-0.094102,-0.018592,-0.116704,-0.086093,-0.027778,-0.059895
20,ambiguous_lie,-0.028011,0.001768,-0.031929,-0.030617,0.069038,-0.044801,0.142857,0.000000,0.012495
21,ambiguous_truthful_reply,-0.007703,-0.021218,-0.045516,0.025664,-0.080544,-0.061394,0.046875,-0.013384,-0.033916
22,honest_reply_despite_incentive_to_lie,0.000000,0.000196,0.000000,0.001801,-0.000523,-0.001106,-0.020690,0.000000,-0.001565
23,unambiguous_lie,0.019608,0.152456,0.031250,0.010356,0.080544,-0.000553,0.450980,0.018182,0.022382
24,unambiguous_truthful_reply,0.012605,0.003143,-0.025815,0.030617,-0.063285,0.075774,0.166667,0.171212,0.014170
25,larger_than,-0.023109,0.113752,0.229620,0.066186,0.146444,0.187500,0.211921,0.161111,0.042786
26,smaller_than,0.077731,-0.015717,-0.068614,-0.029266,-0.009937,-0.107301,0.092715,0.032323,-0.061268
27,sp_en_trans__negated,-0.016106,0.135953,0.063859,0.040522,-0.019351,0.177442,0.039735,-0.042424,0.094332
28,sp_en_trans__affirmative,-0.091036,0.020236,0.059783,0.031968,-0.082636,0.017194,-0.086093,0.015404,-0.090350
29,sp_en_trans__conjunction,-0.025910,0.074067,0.033288,0.037371,0.076883,0.009939,-0.298013,0.078283,0.011095
30,sp_en_trans__disjunction,0.062325,0.148134,-0.112772,0.024313,0.014121,0.077982,0.013245,0.081818,-0.031609
31,common_claim_true_false,-0.255602,-0.197446,0.017663,-0.060783,-0.048117,-0.049226,0.059603,-0.311869,-0.050682
32,counterfact_true_false,0.017507,0.107662,-0.002717,0.099505,-0.023536,0.051438,0.211921,0.106313,0.110112
33,animal_class__affirmative+negated,-0.095455,0.001375,0.050951,0.000450,0.007845,0.030973,-0.066225,-0.079545,0.009090
34,animal_class__affirmative+disjunction,-0.151832,0.029077,0.076766,-0.050428,-0.042887,-0.172013,0.264901,0.093182,-0.051793
35,animal_class__negated+conjunction,-0.015707,-0.058939,-0.124321,-0.080594,-0.124477,-0.121681,-0.152318,-0.229293,-0.120585
36,animal_class__affirmative+negated+conjunction+...,-0.050000,-0.066405,-0.133832,-0.050878,-0.089958,0.003872,0.092715,-0.323990,-0.089444
37,cities__affirmative+negated,0.019608,0.034795,-0.040082,0.042323,-0.023013,-0.031527,-0.158940,0.054040,-0.053880
38,cities__affirmative+disjunction,-0.010504,0.072075,-0.023098,0.037371,-0.045502,-0.013827,-0.092715,0.077020,-0.117812
39,cities__negated+conjunction,-0.030112,0.015744,0.006114,0.016659,-0.039749,-0.065265,-0.145695,-0.154798,-0.018125
40,cities__affirmative+negated+conjunction+disjun...,-0.115546,0.010000,-0.160326,-0.024313,-0.146444,-0.129425,-0.099338,0.006566,-0.120970
41,element_symb__affirmative+negated,-0.124650,0.010609,-0.029091,-0.072490,0.011506,-0.064712,-0.311258,-0.331061,0.031801
42,element_symb__affirmative+disjunction,-0.157563,-0.062279,0.008906,-0.039622,-0.015167,-0.125553,0.198675,-0.203030,-0.018537
43,element_symb__negated+conjunction,-0.133053,-0.168959,-0.048346,-0.089149,-0.082113,-0.083518,0.099338,-0.169444,-0.026199
44,element_symb__affirmative+negated+conjunction+...,-0.165966,0.002554,-0.100000,-0.008555,-0.031381,-0.050332,0.145695,-0.200000,0.046191
45,facts__affirmative+negated,-0.149860,-0.102554,0.005435,-0.130118,-0.036611,-0.049779,-0.152318,-0.223485,-0.101637
46,facts__affirmative+disjunction,0.033613,0.176621,-0.086277,0.047414,0.004184,-0.040929,0.125828,-0.090404,0.049486
47,facts__negated+conjunction,0.107143,0.053045,-0.015625,0.082759,0.029812,-0.004978,0.105960,-0.137121,-0.018894
48,facts__affirmative+negated+conjunction+disjunc...,-0.028711,0.018271,-0.152174,-0.060606,-0.047594,-0.060841,0.000000,-0.237626,-0.046136
49,inventors__affirmative+negated,-0.166667,-0.132220,-0.050272,-0.087798,-0.034545,-0.023230,-0.198675,-0.138636,-0.075548
50,inventors__affirmative+disjunction,0.053922,0.036149,-0.106658,-0.053579,0.113320,-0.165376,-0.019868,0.167424,-0.063025
51,inventors__negated+conjunction,-0.235994,-0.286051,-0.175951,-0.167942,-0.122266,-0.211836,-0.079470,-0.355808,-0.126902
52,inventors__affirmative+negated+conjunction+dis...,-0.217087,-0.206090,-0.054348,-0.131923,-0.200000,-0.149889,-0.165563,0.152273,-0.077305
53,sp_en_trans__affirmative+negated,-0.025910,0.161297,0.095788,0.079244,-0.046548,0.009091,0.013245,0.071212,0.040451
54,sp_en_trans__affirmative+disjunction,0.020308,0.053635,-0.124321,-0.012607,-0.101987,0.147799,0.019868,-0.285101,-0.123085
55,sp_en_trans__negated+conjunction,-0.240896,-0.129862,-0.091712,-0.103557,-0.049686,-0.026205,-0.198675,-0.053030,-0.085434
56,sp_en_trans__affirmative+negated+conjunction+d...,-0.007003,-0.045972,-0.131793,-0.049077,-0.023013,-0.200000,0.192053,-0.227778,0.009035
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.093838,0.173870,0.012908,0.070689,0.009937,0.058628,0.041667,0.000758,0.058302
58,animal_class+facts+inventors__affirmative+nega...,0.001667,-0.023969,-0.075408,0.051753,0.126667,-0.115597,0.046358,-0.094949,-0.025320
59,animal_class+facts+inventors__affirmative+nega...,-0.003636,-0.003733,-0.077446,-0.063694,-0.116364,-0.059181,-0.208333,-0.012121,-0.044769

In [53]:
lyr18_ttpd_probes_rel_to_baseline_probes_acc_delta_on_unseen_single_topic_data_groupings_df.describe()

,animal class,cities,element symbols,facts,inventors,spanish english translation,real world scenarios,relative comparison,true false
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,-0.039523,-0.002070,-0.035101,-0.014271,-0.015457,-0.031605,-0.008872,-0.046650,-0.027143
std,0.092275,0.117435,0.087600,0.058013,0.069418,0.100697,0.159499,0.160499,0.066390
min,-0.255602,-0.299411,-0.240741,-0.167942,-0.200000,-0.300332,-0.357616,-0.355808,-0.136211
25%,-0.096116,-0.059774,-0.093784,-0.053694,-0.048509,-0.089463,-0.145695,-0.177083,-0.077704
50%,-0.024510,0.001572,-0.041101,-0.004953,-0.021182,-0.036228,0.006623,-0.003662,-0.030483
75%,0.018032,0.067976,0.014096,0.026902,0.011343,0.034154,0.092715,0.072664,0.012914
max,0.172414,0.255206,0.229620,0.099505,0.157224,0.187500,0.450980,0.288889,0.128028