In [134]:
import json
import os.path
from statistics import mean
from typing import Literal, NamedTuple

import numpy as np
import pandas as pd

from evaluation_utils import MetricsForDatasetProbes, ConfusionMetrics
from phi_3_5_constants import dsets_index_path, four_way_topics_index_path, misc_datasets_index_path, \
    directions_reconstruction_losses_path, separation_by_layer_analysis_path, train_split_classification_metrics_path, \
    validation_split_classification_metrics_path, test_classification_metrics_path

TODO do data analysis on the evaluation results, comparing with the results from direction-learning (validation reconstruction loss with truth/polarity directions relative to reconstruction loss with just mean activation) and with the validation accuracy of a given probe for the datasets it was trained on.

In [3]:
dsets_index_df = pd.read_csv(dsets_index_path, index_col="Idx")
num_dsets = dsets_index_df.shape[0]

In [4]:
# top-level key is the name of a topic that has pos/neg/conj/disj variants, second level key is one of those variant names
with four_way_topics_index_path.open("r") as f:
    dset_idxs_for_4way_topics: dict[str, dict[str, int]] = json.load(f)
with misc_datasets_index_path.open("r") as f:
    idxs_for_other_dsets: dict[str, int] = json.load(f)

In [129]:
for dset_idx, dset_dtls in dsets_index_df.iterrows():
    categ_nm = dset_dtls["Categ_Folder"]    
    if dset_dtls['in_german']:
        assert categ_nm in dset_idxs_for_4way_topics, f"{categ_nm} topic has german variant but wasn't captured in earlier tracking of standard ('4-way') topics"
        if dset_dtls['is_negated']:
            dset_idxs_for_4way_topics[categ_nm]["de_neg"] = dset_idx
        else:
            dset_idxs_for_4way_topics[categ_nm]["de_affirm"] = dset_idx

In [33]:
affirm_german_dset_idxs = dsets_index_df.loc[dsets_index_df.in_german & (~dsets_index_df.is_negated)].index.to_list()
negated_german_dset_idxs = dsets_index_df.loc[dsets_index_df.in_german & dsets_index_df.is_negated].index.to_list()

In [35]:
directions_reconstruction_losses = pd.read_csv(directions_reconstruction_losses_path)

dir_probe_scenarios_strs = directions_reconstruction_losses['scenario_identifier'].to_list()
dir_probe_scenarios_specs = [tuple(map(int, scenario_str.split(' '))) for scenario_str in dir_probe_scenarios_strs]

In [65]:
#'scenarios' describe the different combinations of data that directions/probes were trained on 
other_categs: set[str] = set(dsets_index_df.loc[dsets_index_df.is_other].Categ_Folder.to_list())

scenario_standard_categs: dict[tuple[int,...], list[str]] = {}
scenario_other_dset_names: dict[tuple[int,...], list[str]] = {}
for scenario_id in dir_probe_scenarios_specs:
    scenario_standard_categs[scenario_id] = []
    scenario_other_dset_names[scenario_id] = []
    for dset_idx_in_scenario in scenario_id:
        if not dsets_index_df.loc[dset_idx_in_scenario, "is_other"]:
            curr_standard_categ = dsets_index_df.loc[dset_idx_in_scenario, "Categ_Folder"]
            if curr_standard_categ not in scenario_standard_categs[scenario_id]:
                scenario_standard_categs[scenario_id].append(curr_standard_categ)
        else:
            curr_other_dset_name = os.path.splitext(dsets_index_df.loc[dset_idx_in_scenario, "Dataset_File"])[0]
            assert curr_other_dset_name not in scenario_other_dset_names[scenario_id]
            scenario_other_dset_names[scenario_id].append(curr_other_dset_name)

scenario_data_variants: dict[tuple[int,...], set[Literal["affirm", "neg", "conj", "disj", "other"]]] = {}
for scenario_id in dir_probe_scenarios_specs:
    scenario_data_variants[scenario_id] = set()
    for dset_idx_in_scenario in scenario_id:
        assert not dsets_index_df.at[dset_idx_in_scenario, "in_german"]
        scenario_data_variants[scenario_id].add(
            "other" if dsets_index_df.at[dset_idx_in_scenario, "is_other"] else "neg" if dsets_index_df.at[dset_idx_in_scenario, "is_negated"] else "conj" if dsets_index_df.at[dset_idx_in_scenario, "is_conj"] else "disj" if dsets_index_df.at[dset_idx_in_scenario, "is_disj"] else "affirm")

scenario_labels: dict[tuple[int,...], str] = {}
for scenario_id in dir_probe_scenarios_specs:
    label = "+".join(scenario_standard_categs[scenario_id])
    was_earlier_variant_included=False
    if "affirm" in scenario_data_variants[scenario_id]:
        label += "__affirmative"
        was_earlier_variant_included = True
    if "neg" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "negated"
        was_earlier_variant_included = True
    if "conj" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "conjunction"
        was_earlier_variant_included = True
    if "disj" in scenario_data_variants[scenario_id]:
        label += ("+" if was_earlier_variant_included else "__") + "disjunction"
    # assuming no training scenarios include german
    if scenario_other_dset_names[scenario_id]:
        label += ("_and_" if label else "") + "+".join(scenario_other_dset_names[scenario_id])
    scenario_labels[scenario_id] = label

In [107]:
t_f_sep_by_layer_df = pd.read_csv(separation_by_layer_analysis_path, index_col="Idx")
t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_truthful_reply"], "Separation after 18"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_lie"], "Separation after 18"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_truthful_reply"], "Separation after 25"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["ambiguous_lie"], "Separation after 25"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_truthful_reply"], "Separation after 18"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_lie"], "Separation after 18"]
t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_truthful_reply"], "Separation after 25"] = t_f_sep_by_layer_df.at[idxs_for_other_dsets["unambiguous_lie"], "Separation after 25"]

In [74]:
with train_split_classification_metrics_path.open("r") as f:
    serialized_train_metrics = json.load(f)
with validation_split_classification_metrics_path.open("r") as f:
    serialized_validation_metrics = json.load(f)
train_metrics: dict[tuple[int,...], MetricsForDatasetProbes] = {
    tuple(map(int, scenario_str.split(' '))): MetricsForDatasetProbes.from_dict(metrics_dict) for scenario_str, metrics_dict in serialized_train_metrics.items()
}
validation_metrics: dict[tuple[int,...], MetricsForDatasetProbes] = {
    tuple(map(int, scenario_str.split(' '))): MetricsForDatasetProbes.from_dict(metrics_dict) for scenario_str, metrics_dict in serialized_validation_metrics.items()
}

In [79]:
with test_classification_metrics_path.open("r") as f:
    serialized_probes_metrics_on_test_dsets = json.load(f)
# first level key identifies the scenario (of one or more datasets) which the probe was trained on;
# second level key identifies the previously-unseen dataset which the probe is tested on
probes_metrics_on_test_dsets: dict[tuple[int,...], dict[int, MetricsForDatasetProbes]] = {
    tuple(map(int, scenario_str.split(' '))): {
        int(test_dset_idx): MetricsForDatasetProbes.from_dict(serialized_test_dset_metrics) for test_dset_idx, serialized_test_dset_metrics in serialized_test_dsets_metrics.items()
    } for scenario_str, serialized_test_dsets_metrics in serialized_probes_metrics_on_test_dsets.items()
}

In [82]:
class TruthPolarityDirsEval(NamedTuple):
    rel_loss_reduct_on_train: float
    rel_loss_reduct_on_validation: float
    rel_loss_reduct_on_validation_using_validation_mean: float

lyr18_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}
lyr25_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}
lyrs18_and_25_dirs_evals: dict[tuple[int,...], TruthPolarityDirsEval] = {}

for _, recon_losses_row in directions_reconstruction_losses.iterrows():
    scenario_id = tuple(map(int, recon_losses_row["scenario_identifier"].split(' ')))
    lyr18_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyr18_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyr18_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyr18_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr18_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyr18_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr18_validation_mean_activ_loss_on_validation"]
    )
    lyr25_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyr25_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyr25_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyr25_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr25_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyr25_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyr25_validation_mean_activ_loss_on_validation"]
    )
    lyrs18_and_25_dirs_evals[scenario_id] = TruthPolarityDirsEval(
        rel_loss_reduct_on_train=1-recon_losses_row["lyrs18_and_25_train_mean_activ_and_t_p_dirs_loss_on_train"]/recon_losses_row["lyrs18_and_25_train_mean_activ_loss_on_train"],
        rel_loss_reduct_on_validation=1-recon_losses_row["lyrs18_and_25_train_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyrs18_and_25_train_mean_activ_loss_on_validation"],
        rel_loss_reduct_on_validation_using_validation_mean=1-recon_losses_row["lyrs18_and_25_validation_mean_activ_and_t_p_dirs_loss_on_validation"]/recon_losses_row["lyrs18_and_25_validation_mean_activ_loss_on_validation"]
    )

In [91]:
class ProbeEvalOnData(NamedTuple):
    acc: float
    precision: float
    recall: float
    f1: float
    brier: float
    soft_precision: float
    soft_recall: float
    soft_f1: float

lyr18_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyr25_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyrs18_and_25_probes_train_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

for scenario_id, probes_metrics_on_train in train_metrics.items():
    lyr18_train_metrics = probes_metrics_on_train.lyr18_probe_metrics
    lyr18_train_trad_metrics = lyr18_train_metrics.get_traditional_metrics()
    lyr18_train_soft_metrics = lyr18_train_metrics.get_soft_metrics()
    lyr25_train_metrics = probes_metrics_on_train.lyr25_probe_metrics
    lyr25_train_trad_metrics = lyr25_train_metrics.get_traditional_metrics()
    lyr25_train_soft_metrics = lyr25_train_metrics.get_soft_metrics()
    lyrs18_and_25_train_metrics = probes_metrics_on_train.lyrs18_and_25_probe_metrics
    lyrs18_and_25_train_trad_metrics = lyrs18_and_25_train_metrics.get_traditional_metrics()
    lyrs18_and_25_train_soft_metrics = lyrs18_and_25_train_metrics.get_soft_metrics()
    
    lyr18_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_train_trad_metrics.accuracy, precision=lyr18_train_trad_metrics.precision, recall=lyr18_train_trad_metrics.recall,
        f1=lyr18_train_trad_metrics.f1, brier=lyr18_train_metrics.get_brier_score(), soft_precision=lyr18_train_soft_metrics.soft_precision,
        soft_recall=lyr18_train_soft_metrics.soft_recall, soft_f1=lyr18_train_soft_metrics.soft_f1)
    lyr25_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr25_train_trad_metrics.accuracy, precision=lyr25_train_trad_metrics.precision, recall=lyr25_train_trad_metrics.recall,
        f1=lyr25_train_trad_metrics.f1, brier=lyr25_train_metrics.get_brier_score(), soft_precision=lyr25_train_soft_metrics.soft_precision,
        soft_recall=lyr25_train_soft_metrics.soft_recall, soft_f1=lyr25_train_soft_metrics.soft_f1)
    lyrs18_and_25_probes_train_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyrs18_and_25_train_trad_metrics.accuracy, precision=lyrs18_and_25_train_trad_metrics.precision, recall=lyrs18_and_25_train_trad_metrics.recall,
        f1=lyrs18_and_25_train_trad_metrics.f1, brier=lyrs18_and_25_train_metrics.get_brier_score(), soft_precision=lyrs18_and_25_train_soft_metrics.soft_precision,
        soft_recall=lyrs18_and_25_train_soft_metrics.soft_recall, soft_f1=lyrs18_and_25_train_soft_metrics.soft_f1)

lyr18_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyr25_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}
lyrs18_and_25_probes_validation_set_evals: dict[tuple[int,...], ProbeEvalOnData] = {}

for scenario_id, probes_metrics_on_validation in validation_metrics.items():
    lyr18_validation_metrics = probes_metrics_on_validation.lyr18_probe_metrics
    lyr18_validation_trad_metrics = lyr18_validation_metrics.get_traditional_metrics()
    lyr18_validation_soft_metrics = lyr18_validation_metrics.get_soft_metrics()
    lyr25_validation_metrics = probes_metrics_on_validation.lyr25_probe_metrics
    lyr25_validation_trad_metrics = lyr25_validation_metrics.get_traditional_metrics()
    lyr25_validation_soft_metrics = lyr25_validation_metrics.get_soft_metrics()
    lyrs18_and_25_validation_metrics = probes_metrics_on_validation.lyrs18_and_25_probe_metrics
    lyrs18_and_25_validation_trad_metrics = lyrs18_and_25_validation_metrics.get_traditional_metrics()
    lyrs18_and_25_validation_soft_metrics = lyrs18_and_25_validation_metrics.get_soft_metrics()
    
    lyr18_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr18_validation_trad_metrics.accuracy, precision=lyr18_validation_trad_metrics.precision, recall=lyr18_validation_trad_metrics.recall,
        f1=lyr18_validation_trad_metrics.f1, brier=lyr18_validation_metrics.get_brier_score(), soft_precision=lyr18_validation_soft_metrics.soft_precision,
        soft_recall=lyr18_validation_soft_metrics.soft_recall, soft_f1=lyr18_validation_soft_metrics.soft_f1)
    lyr25_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyr25_validation_trad_metrics.accuracy, precision=lyr25_validation_trad_metrics.precision, recall=lyr25_validation_trad_metrics.recall,
        f1=lyr25_validation_trad_metrics.f1, brier=lyr25_validation_metrics.get_brier_score(), soft_precision=lyr25_validation_soft_metrics.soft_precision,
        soft_recall=lyr25_validation_soft_metrics.soft_recall, soft_f1=lyr25_validation_soft_metrics.soft_f1)
    lyrs18_and_25_probes_validation_set_evals[scenario_id] = ProbeEvalOnData(
        acc=lyrs18_and_25_validation_trad_metrics.accuracy, precision=lyrs18_and_25_validation_trad_metrics.precision, recall=lyrs18_and_25_validation_trad_metrics.recall,
        f1=lyrs18_and_25_validation_trad_metrics.f1, brier=lyrs18_and_25_validation_metrics.get_brier_score(), soft_precision=lyrs18_and_25_validation_soft_metrics.soft_precision,
        soft_recall=lyrs18_and_25_validation_soft_metrics.soft_recall, soft_f1=lyrs18_and_25_validation_soft_metrics.soft_f1)

In [113]:
lyr18_probe_row_dicts: list[dict[str, str|float]] = []
lyr25_probe_row_dicts: list[dict[str, str|float]] = []
lyrs18_and_25_probe_row_dicts: list[dict[str, str|float]] = []

lyr25_rel_to_18_probe_row_dicts: list[dict[str, str|float]] = []
lyrs18_and_25_rel_to_just_18_probe_row_dicts: list[dict[str, str|float]] = []

for scenario_id in dir_probe_scenarios_specs:
    lyr18_t_f_sep = mean([t_f_sep_by_layer_df.at[dset_idx_in_scenario, "Separation after 18"] for dset_idx_in_scenario in scenario_id])
    lyr25_t_f_sep = mean([t_f_sep_by_layer_df.at[dset_idx_in_scenario, "Separation after 25"] for dset_idx_in_scenario in scenario_id])
    lyr18_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": lyr18_t_f_sep, "train_recon_improv": lyr18_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyr18_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyr18_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyr18_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyr18_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyr18_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyr18_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyr18_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyr18_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyr18_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyr18_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyr18_probe_row_dicts.append(lyr18_probe_row_dict)
    lyr25_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": lyr25_t_f_sep, "train_recon_improv": lyr25_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyr25_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyr25_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyr25_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyr25_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyr25_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyr25_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyr25_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyr25_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyr25_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyr25_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyr25_probe_row_dicts.append(lyr25_probe_row_dict)
    lyrs18_and_25_probe_row_dict = {
        "scenario": scenario_labels[scenario_id],
        "tf_sep": (lyr18_t_f_sep + lyr25_t_f_sep) / 2,
        "train_recon_improv": lyrs18_and_25_dirs_evals[scenario_id].rel_loss_reduct_on_train,
        "val_recon_improv": lyrs18_and_25_dirs_evals[scenario_id].rel_loss_reduct_on_validation,
        "val_recon_improv_w_val_mean": lyrs18_and_25_dirs_evals[
            scenario_id].rel_loss_reduct_on_validation_using_validation_mean,
        "val_acc": lyrs18_and_25_probes_validation_set_evals[scenario_id].acc,
        "val_f1": lyrs18_and_25_probes_validation_set_evals[scenario_id].f1,
        "val_brier": lyrs18_and_25_probes_validation_set_evals[scenario_id].brier,
        "val_soft_f1": lyrs18_and_25_probes_validation_set_evals[scenario_id].soft_f1,
        "train_acc": lyrs18_and_25_probes_train_set_evals[scenario_id].acc,
        "train_f1": lyrs18_and_25_probes_train_set_evals[scenario_id].f1,
        "train_brier": lyrs18_and_25_probes_train_set_evals[scenario_id].brier,
        "train_soft_f1": lyrs18_and_25_probes_train_set_evals[scenario_id].soft_f1,
    }
    lyrs18_and_25_probe_row_dicts.append(lyrs18_and_25_probe_row_dict)
    
    lyr25_rel_to_18_probe_row_dicts.append({
        col_nm: (lyr18_probe_row_dict[col_nm] if col_nm == "scenario" else lyr25_probe_row_dict[col_nm]-lyr18_probe_row_dict[col_nm]) for col_nm in lyr18_probe_row_dict.keys()
    })
    lyrs18_and_25_rel_to_just_18_probe_row_dicts.append({
        col_nm: (lyr18_probe_row_dict[col_nm] if col_nm == "scenario" else lyrs18_and_25_probe_row_dict[col_nm]-lyr18_probe_row_dict[col_nm]) for col_nm in lyr18_probe_row_dict.keys()
    })
    

lyr18_eval_except_test_df = pd.DataFrame(lyr18_probe_row_dicts)
lyr25_eval_except_test_df = pd.DataFrame(lyr25_probe_row_dicts)
lyrs18_and_25_eval_except_test_df = pd.DataFrame(lyrs18_and_25_probe_row_dicts)
lyr25_rel_to_18_eval_except_test_df = pd.DataFrame(lyr25_rel_to_18_probe_row_dicts)
lyrs18_and_25_rel_to_18_eval_except_test_df = pd.DataFrame(lyrs18_and_25_rel_to_just_18_probe_row_dicts)

For the "tf_sep" aka "true-false separation" column, and the ambiguous/unambiguous truth/lie (plus "honest reply despite incentive to lie") datasets,  
the value in the "ambiguous lie" and "ambiguous truthful reply" rows represent the separation between ambiguous lies and truths,  
the value in the "unambiguous lie" and "unambiguous truthful reply" rows represent the separation between unambiguous lies and truths,
and the 0.0 values for the "honest reply despite incentive to lie" row should be ignored.

In [130]:
lyr18_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.873458,4.543415e-01,5.163863e-01,3.967561e-01,1.000000,1.000000,2.658150e-27,1.000000,0.992366,0.992908,7.633584e-03,0.992908
1,animal_class__conjunction,0.314961,2.398567e-01,2.314483e-01,2.357424e-01,0.950000,0.950495,3.666341e-02,0.917987,0.940000,0.938776,4.029386e-02,0.916245
2,animal_class__disjunction,0.029296,2.734168e-02,3.243016e-02,3.037365e-02,0.740000,0.697674,1.855914e-01,0.585988,0.715000,0.724638,1.875205e-01,0.631381
3,animal_class__negated,0.579465,3.598452e-01,4.085457e-01,3.995034e-01,1.000000,1.000000,4.515404e-10,0.999997,1.000000,1.000000,2.603914e-03,0.992150
4,cities__affirmative,1.690080,6.311205e-01,6.175942e-01,6.166543e-01,0.980000,0.979021,1.525651e-02,0.974538,0.983278,0.983526,1.215648e-02,0.978224
5,cities__conjunction,0.388754,2.749372e-01,2.993844e-01,2.982197e-01,0.973333,0.975460,2.134011e-02,0.956792,0.971619,0.971380,2.220916e-02,0.948120
6,cities__disjunction,0.058523,5.700467e-02,4.585128e-02,4.644103e-02,0.800000,0.795918,1.366851e-01,0.716985,0.855000,0.852041,1.151316e-01,0.742532
7,cities__negated,0.868476,4.610974e-01,4.793974e-01,4.679124e-01,0.983333,0.985163,9.305317e-03,0.984793,0.990803,0.990525,6.975475e-03,0.983914
8,element_symb__affirmative,0.577514,3.498783e-01,4.370834e-01,4.490662e-01,1.000000,1.000000,7.230042e-04,0.995008,0.972973,0.973333,1.712232e-02,0.973252
9,element_symb__conjunction,0.425471,3.073251e-01,2.748850e-01,2.742458e-01,0.970000,0.968421,2.660718e-02,0.922004,0.955000,0.958904,3.523890e-02,0.931465
10,element_symb__disjunction,0.066850,6.149318e-02,6.555922e-02,6.573485e-02,0.790000,0.810811,1.415020e-01,0.751975,0.785000,0.780612,1.355860e-01,0.737210
11,element_symb__negated,0.365157,2.844515e-01,2.087251e-01,2.134846e-01,1.000000,1.000000,4.215815e-18,1.000000,1.000000,1.000000,4.013480e-24,1.000000
12,facts__affirmative,0.093213,8.781164e-02,7.354002e-02,6.904972e-02,0.867257,0.885496,9.097633e-02,0.828380,0.877232,0.878587,8.542303e-02,0.820865
13,facts__conjunction,0.035627,3.673653e-02,2.145067e-02,2.171824e-02,0.780000,0.750000,1.625660e-01,0.661671,0.805000,0.806931,1.319708e-01,0.729528
14,facts__disjunction,0.017876,1.650338e-02,1.990205e-02,2.031295e-02,0.760000,0.720930,1.694269e-01,0.619886,0.710000,0.672316,1.874816e-01,0.606359
15,facts__negated,0.028115,2.862351e-02,2.065965e-02,2.092022e-02,0.823009,0.818182,1.226884e-01,0.768322,0.906250,0.905830,7.859278e-02,0.825426
16,inventors__affirmative,0.059885,5.634922e-02,5.107413e-02,5.130731e-02,0.890244,0.909091,9.082353e-02,0.819207,0.833333,0.850000,1.211991e-01,0.786914
17,inventors__conjunction,0.024496,2.481788e-02,1.691028e-02,1.747544e-02,0.760000,0.803279,1.511651e-01,0.753881,0.815000,0.838428,1.288302e-01,0.770583
18,inventors__disjunction,0.011326,1.231043e-02,5.683728e-03,5.092700e-03,0.700000,0.750000,1.956442e-01,0.675177,0.755000,0.782222,1.733570e-01,0.680158
19,inventors__negated,0.085275,8.420518e-02,4.965519e-02,4.958424e-02,0.707317,0.675676,2.013686e-01,0.598092,0.790123,0.774834,1.528968e-01,0.670040
20,ambiguous_lie,0.051308,5.361147e-08,3.629734e-07,6.957434e-08,1.000000,NaN,8.495714e-13,NaN,1.000000,NaN,2.493867e-12,NaN
21,ambiguous_truthful_reply,0.051308,-6.544491e-08,9.936519e-08,0.000000e+00,1.000000,1.000000,3.353762e-13,1.000000,1.000000,1.000000,3.347446e-13,1.000000
22,honest_reply_despite_incentive_to_lie,0.000000,-1.319963e-07,2.438925e-07,0.000000e+00,1.000000,1.000000,3.968921e-05,0.996840,1.000000,1.000000,4.799641e-05,0.996528
23,unambiguous_lie,0.107328,1.258997e-07,-2.674763e-07,0.000000e+00,1.000000,NaN,8.479097e-14,NaN,1.000000,NaN,1.244857e-13,NaN
24,unambiguous_truthful_reply,0.107328,6.411020e-08,-2.047305e-07,-7.574867e-08,1.000000,1.000000,1.550275e-13,1.000000,1.000000,1.000000,1.572883e-13,1.000000
25,larger_than,0.456852,3.142809e-01,3.110852e-01,3.111883e-01,0.974747,0.974093,1.802146e-02,0.970103,0.986742,0.986981,9.072807e-03,0.980670
26,smaller_than,0.347493,2.578911e-01,2.581460e-01,2.549792e-01,0.992424,0.992974,6.632766e-03,0.986733,0.993056,0.992917,6.087587e-03,0.983593
27,sp_en_trans__negated,0.679175,4.083760e-01,3.927502e-01,3.957529e-01,1.000000,1.000000,2.809937e-04,0.997326,0.996466,0.996466,2.566750e-03,0.995385
28,sp_en_trans__affirmative,0.763526,4.254077e-01,4.657559e-01,4.151790e-01,1.000000,1.000000,7.500676e-04,0.996962,0.996466,0.996226,4.342519e-03,0.990570
29,sp_en_trans__conjunction,0.360656,2.654025e-01,2.726139e-01,2.707033e-01,0.950000,0.949495,3.932325e-02,0.937158,0.985000,0.986301,1.387389e-02,0.974263
30,sp_en_trans__disjunction,0.055794,5.717739e-02,3.746276e-02,3.632303e-02,0.840000,0.818182,1.094066e-01,0.762604,0.832500,0.813370,1.089947e-01,0.771806
31,common_claim_true_false,0.016943,1.601768e-02,1.895602e-02,1.898451e-02,0.778652,0.783278,1.526537e-01,0.684227,0.747753,0.748881,1.692111e-01,0.665262
32,counterfact_true_false,0.012648,1.257900e-02,1.211249e-02,1.211160e-02,0.713749,0.724812,1.863626e-01,0.627586,0.710649,0.725546,1.848542e-01,0.631091
33,animal_class__affirmative+negated,0.726462,3.255649e-01,3.730479e-01,3.483443e-01,1.000000,1.000000,4.286868e-05,0.999076,0.996183,0.996310,3.639840e-03,0.991221
34,animal_class__affirmative+disjunction,0.451377,3.461717e-02,3.647969e-02,3.132026e-02,0.819549,0.777778,1.383672e-01,0.656835,0.774011,0.778598,1.502398e-01,0.708477
35,animal_class__negated+conjunction,0.447213,1.274588e-01,1.192823e-01,1.191230e-01,0.977444,0.978417,2.119514e-02,0.956721,0.962335,0.961240,2.545919e-02,0.945805
36,animal_class__affirmative+negated+conjunction+...,0.449295,5.486206e-02,5.498721e-02,5.459481e-02,0.748120,0.712446,1.359131e-01,0.718374,0.741055,0.716202,1.394375e-01,0.725668
37,cities__affirmative+negated,1.279278,3.803487e-01,3.786022e-01,3.774681e-01,0.983333,0.983974,1.312652e-02,0.976913,0.984532,0.984434,1.225302e-02,0.974278
38,cities__affirmative+disjunction,0.874302,2.039240e-01,2.019980e-01,2.012607e-01,0.915000,0.910526,6.303320e-02,0.867087,0.911654,0.910019,6.164550e-02,0.874966
39,cities__negated+conjunction,0.628615,1.256688e-01,1.276570e-01,1.258128e-01,0.955000,0.960118,3.602307e-02,0.934004,0.943191,0.943615,4.217404e-02,0.917817
40,cities__affirmative+negated+conjunction+disjun...,0.751458,1.131659e-01,1.183838e-01,1.180848e-01,0.882000,0.888258,7.183841e-02,0.868754,0.874687,0.876238,8.195860e-02,0.848426
41,element_symb__affirmative+negated,0.471336,1.768124e-01,1.959989e-01,1.974226e-01,0.986842,0.987342,7.372640e-03,0.985545,0.976351,0.976589,1.624898e-02,0.970944
42,element_symb__affirmative+disjunction,0.322182,2.541350e-02,3.067232e-02,3.052880e-02,0.840580,0.851351,1.020192e-01,0.815508,0.857664,0.859206,1.045344e-01,0.794673
43,element_symb__negated+conjunction,0.395314,1.584398e-01,1.283977e-01,1.277602e-01,0.884058,0.882353,6.662395e-02,0.872912,0.943431,0.947547,4.693892e-02,0.912988
44,element_symb__affirmative+negated+conjunction+...,0.358748,4.414859e-02,3.996578e-02,4.002296e-02,0.804348,0.812500,1.325034e-01,0.739856,0.814781,0.819876,1.243162e-01,0.756007
45,facts__affirmative+negated,0.060664,5.364384e-02,4.356713e-02,4.226291e-02,0.787611,0.808000,1.363867e-01,0.760959,0.856027,0.858086,1.041089e-01,0.782638
46,facts__affirmative+disjunction,0.055544,2.839450e-02,2.716368e-02,2.710478e-02,0.751174,0.753488,1.562628e-01,0.692145,0.761792,0.738342,1.605732e-01,0.666872
47,facts__negated+conjunction,0.031871,2.251311e-02,1.294852e-02,1.317613e-02,0.657277,0.663594,2.009430e-01,0.580042,0.741745,0.758011,1.718023e-01,0.627535
48,facts__affirmative+negated+conjunction+disjunc...,0.043708,2.225074e-02,1.678023e-02,1.706678e-02,0.715962,0.717949,1.811906e-01,0.647656,0.752358,0.749104,1.616409e-01,0.668000
49,inventors__affirmative+negated,0.072580,4.958832e-02,4.507503e-02,4.572443e-02,0.835366,0.838323,1.267744e-01,0.742785,0.822531,0.821705,1.360787e-01,0.731955
50,inventors__affirmative+disjunction,0.035606,1.016311e-02,8.969028e-03,8.869333e-03,0.791209,0.830357,1.457568e-01,0.734349,0.801105,0.823961,1.537147e-01,0.714175
51,inventors__negated+conjunction,0.054885,4.034714e-02,4.136835e-02,4.150045e-02,0.675824,0.725581,2.141742e-01,0.588953,0.649171,0.699764,2.196804e-01,0.575043
52,inventors__affirmative+negated+conjunction+dis...,0.045245,1.717407e-02,1.567208e-02,1.575162e-02,0.695055,0.743649,2.081301e-01,0.612157,0.643646,0.689904,2.149036e-01,0.590877
53,sp_en_trans__affirmative+negated,0.721350,2.160448e-01,2.094281e-01,2.005184e-01,0.971831,0.975309,1.233248e-02,0.976858,0.987633,0.987203,8.886011e-03,0.979941
54,sp_en_trans__affirmative+disjunction,0.409660,5.649454e-02,5.059661e-02,4.968711e-02,0.824561,0.833333,1.141500e-01,0.791221,0.852123,0.839428,1.009028e-01,0.788322
55,sp_en_trans__negated+conjunction,0.519915,1.346869e-01,1.178831e-01,1.173058e-01,0.970760,0.970414,2.165313e-02,0.951615,0.976574,0.977716,1.934181e-02,0.958060
56,sp_en_trans__affirmative+negated+conjunction+d...,0.464788,7.256485e-02,5.993876e-02,5.999693e-02,0.827485,0.823881,1.343986e-01,0.736022,0.844070,0.840926,1.218017e-01,0.755903
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.088655,8.594724e-02,4.916947e-02,6.062967e-02,0.884615,0.896552,6.625770e-02,0.877693,0.950495,0.960000,3.807531e-02,0.929509
58,animal_class+facts+inventors__affirmative+nega...,0.232722,2.317787e-02,2.236908e-02,2.232274e-02,0.757937,0.769231,1.646366e-01,0.673374,0.761144,0.767638,1.598096e-01,0.673147
59,animal_class+facts+inventors__affirmative+nega...,0.213619,1.702797e-02,1.806127e-02,1.802021e-02,0.813914,0.823023,1.448016e-01,0.710840,0.794072,0.798557,1.531124e-01,0.694812

In [111]:
lyr25_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.588167,3.649412e-01,4.011835e-01,3.074009e-01,1.000000,1.000000,1.122622e-04,0.994123,0.977099,0.978723,1.949597e-02,0.971887
1,animal_class__conjunction,0.333727,2.480434e-01,2.561188e-01,2.589435e-01,0.910000,0.910891,7.857356e-02,0.827397,0.872500,0.870886,9.535470e-02,0.811254
2,animal_class__disjunction,0.030490,2.746382e-02,3.780474e-02,3.551936e-02,0.660000,0.613636,1.953164e-01,0.565382,0.677500,0.678304,2.009036e-01,0.606134
3,animal_class__negated,0.254506,1.976709e-01,2.269427e-01,2.214103e-01,1.000000,1.000000,1.119259e-03,0.993794,0.992366,0.992366,5.854640e-03,0.985401
4,cities__affirmative,1.406146,5.851733e-01,5.821817e-01,5.810651e-01,0.983333,0.982578,1.210321e-02,0.976441,0.986622,0.986842,1.095079e-02,0.978294
5,cities__conjunction,0.284483,2.180753e-01,2.351196e-01,2.340712e-01,0.930000,0.936556,5.618665e-02,0.890656,0.929883,0.931034,5.746764e-02,0.878683
6,cities__disjunction,0.077865,7.738798e-02,4.914201e-02,5.073094e-02,0.630000,0.618557,2.008331e-01,0.594802,0.750000,0.734043,1.788131e-01,0.627824
7,cities__negated,0.428149,2.984820e-01,3.051164e-01,2.961668e-01,0.983333,0.985251,1.685232e-02,0.960339,0.964047,0.963713,2.718204e-02,0.943177
8,element_symb__affirmative,0.385225,2.695421e-01,3.163138e-01,3.262626e-01,0.973684,0.975610,2.514462e-02,0.957768,0.932432,0.935065,4.338877e-02,0.932307
9,element_symb__conjunction,0.280702,2.247273e-01,2.039327e-01,2.055544e-01,0.920000,0.914894,6.248643e-02,0.853163,0.907500,0.915718,6.444300e-02,0.871738
10,element_symb__disjunction,0.101869,9.261090e-02,9.222718e-02,9.210908e-02,0.780000,0.796296,1.672354e-01,0.699138,0.752500,0.746803,1.678957e-01,0.669092
11,element_symb__negated,0.118579,1.107324e-01,8.482091e-02,8.756393e-02,1.000000,1.000000,3.797240e-27,1.000000,1.000000,1.000000,3.840772e-16,1.000000
12,facts__affirmative,0.060569,6.017013e-02,4.325887e-02,4.013136e-02,0.823009,0.848485,1.381940e-01,0.746967,0.796875,0.799117,1.496852e-01,0.730551
13,facts__conjunction,0.023507,2.421945e-02,1.565483e-02,1.487228e-02,0.800000,0.782609,1.533834e-01,0.639849,0.760000,0.765854,1.605174e-01,0.671687
14,facts__disjunction,0.015652,1.430321e-02,1.807144e-02,1.828032e-02,0.710000,0.658824,1.945849e-01,0.575256,0.667500,0.623229,2.094197e-01,0.565770
15,facts__negated,0.011196,1.173250e-02,6.702047e-03,6.779090e-03,0.734513,0.750000,1.686795e-01,0.685704,0.819196,0.823529,1.367482e-01,0.719889
16,inventors__affirmative,0.028233,2.957355e-02,1.377850e-02,1.454122e-02,0.634146,0.666667,2.022772e-01,0.651111,0.709877,0.713415,1.855729e-01,0.657395
17,inventors__conjunction,0.016118,1.717506e-02,7.984143e-03,8.650668e-03,0.680000,0.746032,2.089001e-01,0.665697,0.712500,0.759916,1.931689e-01,0.665246
18,inventors__disjunction,0.006412,6.618306e-03,4.956654e-03,4.401128e-03,0.690000,0.743802,2.116263e-01,0.637765,0.655000,0.693333,2.081077e-01,0.617240
19,inventors__negated,0.032806,3.594561e-02,9.481063e-03,1.112343e-02,0.646341,0.524590,2.398517e-01,0.480861,0.719136,0.648649,1.881696e-01,0.585397
20,ambiguous_lie,0.053311,6.500397e-08,5.883039e-07,-7.470586e-08,1.000000,NaN,1.588286e-08,NaN,1.000000,NaN,3.905317e-08,NaN
21,ambiguous_truthful_reply,0.053311,1.299436e-07,-2.124053e-07,0.000000e+00,1.000000,1.000000,2.667690e-07,0.999822,1.000000,1.000000,2.841563e-05,0.998876
22,honest_reply_despite_incentive_to_lie,0.000000,-8.239608e-08,0.000000e+00,1.181275e-07,1.000000,1.000000,5.276963e-08,0.999885,1.000000,1.000000,5.330752e-08,0.999885
23,unambiguous_lie,0.071157,7.875588e-08,-8.695793e-08,9.851908e-08,1.000000,NaN,2.283684e-13,NaN,1.000000,NaN,1.094321e-13,NaN
24,unambiguous_truthful_reply,0.071157,6.266302e-08,0.000000e+00,8.009028e-08,1.000000,1.000000,6.417081e-07,0.999605,1.000000,1.000000,7.733018e-07,0.999577
25,larger_than,0.274207,2.141040e-01,2.191870e-01,2.189815e-01,0.977273,0.976623,2.094095e-02,0.956649,0.980429,0.980852,1.521689e-02,0.964132
26,smaller_than,0.234721,1.929585e-01,1.784094e-01,1.752719e-01,0.914141,0.921659,5.935723e-02,0.892430,0.931187,0.931056,5.449923e-02,0.889702
27,sp_en_trans__negated,0.507973,3.407284e-01,3.245184e-01,3.271965e-01,1.000000,1.000000,2.551704e-05,0.999315,0.992933,0.992908,7.011923e-03,0.992714
28,sp_en_trans__affirmative,0.766253,4.286215e-01,4.563926e-01,4.038138e-01,1.000000,1.000000,2.119942e-04,0.996048,0.989399,0.988764,9.505885e-03,0.982228
29,sp_en_trans__conjunction,0.333990,2.493014e-01,2.580150e-01,2.558037e-01,0.960000,0.959184,3.259311e-02,0.926846,0.977500,0.979405,2.413610e-02,0.946235
30,sp_en_trans__disjunction,0.046375,4.974986e-02,2.281293e-02,2.155592e-02,0.670000,0.592593,2.014622e-01,0.562962,0.762500,0.735376,1.699354e-01,0.623606
31,common_claim_true_false,0.011256,1.066474e-02,1.269335e-02,1.271016e-02,0.739326,0.746171,1.739735e-01,0.640221,0.714326,0.715206,1.877550e-01,0.623276
32,counterfact_true_false,0.006431,6.421208e-03,6.243058e-03,6.242862e-03,0.644611,0.660794,2.157680e-01,0.571604,0.643698,0.660961,2.145895e-01,0.574644
33,animal_class__affirmative+negated,0.421336,2.310395e-01,2.937793e-01,2.763326e-01,0.984848,0.983051,5.962231e-03,0.983533,0.980916,0.981413,1.699548e-02,0.970850
34,animal_class__affirmative+disjunction,0.309329,3.112807e-02,2.122509e-02,1.699579e-02,0.751880,0.666667,1.711363e-01,0.573124,0.696798,0.679920,1.875420e-01,0.627960
35,animal_class__negated+conjunction,0.294116,1.182459e-01,1.149200e-01,1.151456e-01,0.909774,0.914286,6.251489e-02,0.890396,0.930320,0.930320,5.124449e-02,0.896519
36,animal_class__affirmative+negated+conjunction+...,0.301722,4.912116e-02,5.081535e-02,5.054644e-02,0.714286,0.672414,1.711023e-01,0.646265,0.697740,0.670769,1.804827e-01,0.652716
37,cities__affirmative+negated,0.917148,3.440835e-01,3.494877e-01,3.488409e-01,0.965000,0.967033,2.407706e-02,0.949818,0.959448,0.959901,3.084304e-02,0.938271
38,cities__affirmative+disjunction,0.742006,2.089672e-01,2.068474e-01,2.060909e-01,0.865000,0.854839,8.003118e-02,0.825569,0.890977,0.885677,7.824904e-02,0.838247
39,cities__negated+conjunction,0.356316,9.978609e-02,1.028655e-01,1.011307e-01,0.916667,0.925816,6.424231e-02,0.881733,0.902256,0.904098,7.283267e-02,0.855604
40,cities__affirmative+negated+conjunction+disjun...,0.549161,1.038561e-01,1.095188e-01,1.092212e-01,0.865000,0.874652,9.841463e-02,0.812270,0.845363,0.850497,1.118374e-01,0.787331
41,element_symb__affirmative+negated,0.251902,1.212654e-01,1.339535e-01,1.355060e-01,0.960526,0.962963,2.944011e-02,0.934555,0.942568,0.943522,4.433778e-02,0.921861
42,element_symb__affirmative+disjunction,0.243547,2.222870e-02,2.883926e-02,2.845934e-02,0.768116,0.786667,1.703445e-01,0.679483,0.706204,0.695652,1.926298e-01,0.629886
43,element_symb__negated+conjunction,0.199640,9.875703e-02,7.888846e-02,7.891204e-02,0.855072,0.852941,9.410808e-02,0.816435,0.895985,0.905158,7.600524e-02,0.860301
44,element_symb__affirmative+negated+conjunction+...,0.221594,2.692761e-02,2.134994e-02,2.142082e-02,0.764493,0.776632,1.655494e-01,0.676756,0.759124,0.765542,1.541474e-01,0.699140
45,facts__affirmative+negated,0.035883,3.404237e-02,2.308774e-02,2.182429e-02,0.738938,0.757202,1.743813e-01,0.665713,0.773438,0.772676,1.548038e-01,0.669338
46,facts__affirmative+disjunction,0.038110,2.066776e-02,2.068299e-02,2.064851e-02,0.685446,0.673171,2.045732e-01,0.601206,0.679245,0.646753,2.036816e-01,0.579940
47,facts__negated+conjunction,0.017352,1.202074e-02,8.362271e-03,8.483914e-03,0.732394,0.729858,1.884904e-01,0.610753,0.747642,0.747045,1.755895e-01,0.640074
48,facts__affirmative+negated+conjunction+disjunc...,0.027731,1.380154e-02,1.222099e-02,1.243512e-02,0.687793,0.681055,2.014415e-01,0.596508,0.702241,0.687307,1.936679e-01,0.599816
49,inventors__affirmative+negated,0.030519,2.606403e-02,1.239650e-02,1.383055e-02,0.719512,0.722892,1.825612e-01,0.635039,0.731481,0.715686,1.738044e-01,0.644244
50,inventors__affirmative+disjunction,0.017323,5.965794e-03,2.599023e-03,2.713365e-03,0.637363,0.729508,2.157624e-01,0.620559,0.629834,0.709328,2.101713e-01,0.613763
51,inventors__negated+conjunction,0.024462,2.622788e-02,2.300379e-02,2.344006e-02,0.681319,0.712871,2.274077e-01,0.560698,0.639503,0.669202,2.324116e-01,0.543505
52,inventors__affirmative+negated+conjunction+dis...,0.020892,1.014814e-02,6.477528e-03,6.785889e-03,0.598901,0.640394,2.323836e-01,0.571478,0.590470,0.621570,2.322807e-01,0.555631
53,sp_en_trans__affirmative+negated,0.637113,1.738590e-01,1.621996e-01,1.536014e-01,0.985915,0.987500,1.440061e-02,0.964344,0.977032,0.976661,1.729073e-02,0.958453
54,sp_en_trans__affirmative+disjunction,0.406314,4.894242e-02,3.840607e-02,3.760650e-02,0.847953,0.855556,1.155539e-01,0.774939,0.831625,0.818898,1.129569e-01,0.754381
55,sp_en_trans__negated+conjunction,0.420982,8.498504e-02,6.820703e-02,6.769840e-02,0.959064,0.958580,2.244333e-02,0.952562,0.975110,0.976356,1.858852e-02,0.963736
56,sp_en_trans__affirmative+negated+conjunction+d...,0.413648,5.025428e-02,3.367015e-02,3.370361e-02,0.742690,0.726708,1.607204e-01,0.684792,0.764275,0.753823,1.471486e-01,0.707297
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.065208,6.084656e-02,1.764589e-02,2.460461e-02,0.884615,0.896552,1.179090e-01,0.794957,0.920792,0.937500,6.940235e-02,0.874682
58,animal_class+facts+inventors__affirmative+nega...,0.149870,1.348219e-02,1.450066e-02,1.446919e-02,0.687831,0.709360,1.893677e-01,0.626030,0.695941,0.707801,1.911036e-01,0.618419
59,animal_class+facts+inventors__affirmative+nega...,0.128825,8.884766e-03,9.284597e-03,9.260300e-03,0.645362,0.635253,2.018605e-01,0.602833,0.642746,0.622848,2.061800e-01,0.590742

In [112]:
lyrs18_and_25_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,0.730812,0.376432,4.167493e-01,3.190759e-01,1.000000,1.000000,3.052044e-07,0.999841,0.961832,0.965035,3.847507e-02,0.963497
1,animal_class__conjunction,0.324344,0.247242,2.536601e-01,2.566432e-01,0.940000,0.942308,6.190289e-02,0.882204,0.920000,0.918782,6.104548e-02,0.874841
2,animal_class__disjunction,0.029893,0.027450,3.721342e-02,3.495434e-02,0.700000,0.666667,2.068947e-01,0.544004,0.652500,0.655087,2.162586e-01,0.572727
3,animal_class__negated,0.416986,0.219127,2.507378e-01,2.446228e-01,1.000000,1.000000,1.110816e-04,0.997970,0.984733,0.984848,6.356689e-03,0.985879
4,cities__affirmative,1.548113,0.590800,5.865278e-01,5.854327e-01,0.980000,0.979167,1.550567e-02,0.971748,0.985786,0.986054,1.136296e-02,0.975730
5,cities__conjunction,0.336618,0.224548,2.425223e-01,2.414631e-01,0.946667,0.952096,4.698310e-02,0.915437,0.939900,0.940984,4.372015e-02,0.909188
6,cities__disjunction,0.068194,0.074966,4.874871e-02,5.021835e-02,0.740000,0.723404,1.695326e-01,0.653329,0.750000,0.740933,1.644289e-01,0.664539
7,cities__negated,0.648312,0.315151,3.227825e-01,3.135470e-01,0.986667,0.988166,9.353144e-03,0.981632,0.977425,0.976864,1.805479e-02,0.969704
8,element_symb__affirmative,0.481369,0.279506,3.310533e-01,3.412581e-01,0.973684,0.975610,2.149745e-02,0.959670,0.945946,0.946667,4.482301e-02,0.923595
9,element_symb__conjunction,0.353086,0.236666,2.145218e-01,2.158086e-01,0.950000,0.945055,3.536460e-02,0.916467,0.920000,0.924528,5.824718e-02,0.903099
10,element_symb__disjunction,0.084360,0.088819,8.905924e-02,8.895693e-02,0.770000,0.785047,1.729208e-01,0.673299,0.737500,0.731458,1.696307e-01,0.648543
11,element_symb__negated,0.241868,0.127870,9.768481e-02,1.007462e-01,1.000000,1.000000,6.015600e-22,1.000000,1.000000,1.000000,4.681045e-22,1.000000
12,facts__affirmative,0.076891,0.063410,4.671065e-02,4.342653e-02,0.823009,0.857143,1.227407e-01,0.792671,0.816964,0.831276,1.335936e-01,0.763220
13,facts__conjunction,0.029567,0.025842,1.640895e-02,1.576277e-02,0.740000,0.734694,1.698372e-01,0.638078,0.785000,0.792271,1.497253e-01,0.696666
14,facts__disjunction,0.016764,0.014617,1.832306e-02,1.855864e-02,0.720000,0.658537,1.892057e-01,0.588009,0.687500,0.631268,2.042954e-01,0.579062
15,facts__negated,0.019656,0.013732,8.300493e-03,8.401126e-03,0.778761,0.778761,1.474961e-01,0.733012,0.848214,0.849558,1.148978e-01,0.771091
16,inventors__affirmative,0.044059,0.032038,1.724613e-02,1.796282e-02,0.695122,0.736842,1.849598e-01,0.672276,0.709877,0.723529,1.795893e-01,0.670081
17,inventors__conjunction,0.020307,0.018100,9.087952e-03,9.740391e-03,0.650000,0.728682,2.109221e-01,0.674813,0.722500,0.770186,1.852268e-01,0.678226
18,inventors__disjunction,0.008869,0.007250,5.037946e-03,4.478343e-03,0.740000,0.783333,2.057765e-01,0.646674,0.672500,0.713348,2.040318e-01,0.624026
19,inventors__negated,0.059040,0.040392,1.316852e-02,1.465443e-02,0.682927,0.580645,2.136919e-01,0.486206,0.657407,0.535565,2.045224e-01,0.508222
20,ambiguous_lie,0.052309,0.000000,-3.878537e-07,6.746208e-08,1.000000,NaN,4.799146e-06,NaN,1.000000,NaN,4.791958e-06,NaN
21,ambiguous_truthful_reply,0.052309,0.000000,9.594764e-08,1.294894e-07,1.000000,1.000000,2.920355e-07,0.999730,1.000000,1.000000,2.944976e-07,0.999729
22,honest_reply_despite_incentive_to_lie,0.000000,0.000000,-8.140490e-08,1.066376e-07,1.000000,1.000000,1.995116e-08,0.999949,0.750000,0.857143,1.721413e-01,0.830975
23,unambiguous_lie,0.089243,0.000000,-3.078042e-07,0.000000e+00,1.000000,NaN,1.165081e-07,NaN,1.000000,NaN,1.131996e-07,NaN
24,unambiguous_truthful_reply,0.089243,0.000000,6.545556e-08,0.000000e+00,1.000000,1.000000,1.399643e-07,0.999822,1.000000,1.000000,1.743213e-07,0.999803
25,larger_than,0.365530,0.227083,2.309441e-01,2.307898e-01,0.977273,0.976623,1.594311e-02,0.968347,0.986111,0.986369,1.129832e-02,0.972093
26,smaller_than,0.291107,0.201326,1.889082e-01,1.857684e-01,0.959596,0.963470,3.205002e-02,0.947351,0.972222,0.972117,2.120793e-02,0.955777
27,sp_en_trans__negated,0.593574,0.352762,3.367341e-01,3.394803e-01,1.000000,1.000000,4.470868e-07,0.999919,0.992933,0.992908,7.053234e-03,0.992911
28,sp_en_trans__affirmative,0.764889,0.428075,4.579815e-01,4.057482e-01,1.000000,1.000000,2.851689e-04,0.996669,0.985866,0.985075,1.009177e-02,0.983985
29,sp_en_trans__conjunction,0.347323,0.252539,2.609013e-01,2.587486e-01,0.950000,0.949495,3.402635e-02,0.931924,0.970000,0.972477,2.192988e-02,0.955300
30,sp_en_trans__disjunction,0.051085,0.050818,2.492399e-02,2.368459e-02,0.710000,0.681319,1.821256e-01,0.621718,0.757500,0.741333,1.551074e-01,0.665670
31,common_claim_true_false,0.014099,0.011225,1.334179e-02,1.335970e-02,0.744944,0.753529,1.699330e-01,0.654473,0.717697,0.721066,1.852578e-01,0.636837
32,counterfact_true_false,0.009540,0.007145,6.934422e-03,6.933936e-03,0.667292,0.675317,2.072760e-01,0.587451,0.662587,0.672014,2.068945e-01,0.589995
33,animal_class__affirmative+negated,0.573899,0.243376,3.042069e-01,2.857524e-01,1.000000,1.000000,3.133584e-03,0.988753,0.980916,0.981413,1.574483e-02,0.974075
34,animal_class__affirmative+disjunction,0.380353,0.031573,2.324250e-02,1.888703e-02,0.676692,0.505747,1.926741e-01,0.524513,0.651601,0.570766,1.987403e-01,0.598819
35,animal_class__negated+conjunction,0.370665,0.119292,1.154142e-01,1.155958e-01,0.917293,0.920863,5.333429e-02,0.905404,0.949153,0.948571,4.352059e-02,0.911111
36,animal_class__affirmative+negated+conjunction+...,0.375509,0.049828,5.133375e-02,5.104955e-02,0.725564,0.681223,1.620530e-01,0.655633,0.714689,0.684046,1.720400e-01,0.660827
37,cities__affirmative+negated,1.098213,0.348623,3.530811e-01,3.523741e-01,0.970000,0.971698,2.066109e-02,0.956820,0.963629,0.964035,2.722344e-02,0.945454
38,cities__affirmative+disjunction,0.808154,0.208314,2.062135e-01,2.054593e-01,0.855000,0.837079,8.380892e-02,0.818234,0.879073,0.870903,7.811862e-02,0.832908
39,cities__negated+conjunction,0.492465,0.102916,1.058432e-01,1.040960e-01,0.926667,0.934132,5.158062e-02,0.908767,0.923559,0.923527,5.636848e-02,0.890584
40,cities__affirmative+negated+conjunction+disjun...,0.650309,0.105041,1.106453e-01,1.103473e-01,0.868000,0.877323,9.394707e-02,0.826441,0.846617,0.851959,1.078128e-01,0.801503
41,element_symb__affirmative+negated,0.361619,0.128200,1.417082e-01,1.432608e-01,0.973684,0.975000,2.275712e-02,0.947321,0.952703,0.953642,3.867174e-02,0.933443
42,element_symb__affirmative+disjunction,0.282865,0.022589,2.904992e-02,2.869749e-02,0.731884,0.737589,1.754695e-01,0.677462,0.770073,0.766667,1.595474e-01,0.690026
43,element_symb__negated+conjunction,0.297477,0.106490,8.543135e-02,8.536934e-02,0.891304,0.890511,8.520577e-02,0.826318,0.912409,0.920792,6.855940e-02,0.868037
44,element_symb__affirmative+negated+conjunction+...,0.290171,0.028869,2.349190e-02,2.356160e-02,0.746377,0.748201,1.673578e-01,0.670860,0.746350,0.741155,1.563716e-01,0.693414
45,facts__affirmative+negated,0.048273,0.036374,2.546617e-02,2.419861e-02,0.756637,0.773663,1.643930e-01,0.687500,0.799107,0.800000,1.423821e-01,0.694882
46,facts__affirmative+disjunction,0.046827,0.021649,2.148968e-02,2.145191e-02,0.690141,0.670000,1.979725e-01,0.615941,0.686321,0.644385,1.968561e-01,0.594548
47,facts__negated+conjunction,0.024611,0.013329,8.919930e-03,9.054577e-03,0.751174,0.738916,1.802084e-01,0.625262,0.774764,0.777648,1.630896e-01,0.660446
48,facts__affirmative+negated+conjunction+disjunc...,0.035719,0.014869,1.278493e-02,1.300787e-02,0.713615,0.708134,1.942635e-01,0.613148,0.724646,0.715764,1.847098e-01,0.618890
49,inventors__affirmative+negated,0.051550,0.028507,1.579594e-02,1.715225e-02,0.756098,0.756098,1.696329e-01,0.658822,0.759259,0.742574,1.653746e-01,0.663596
50,inventors__affirmative+disjunction,0.026464,0.006453,3.337304e-03,3.427257e-03,0.670330,0.736842,2.036548e-01,0.646778,0.686464,0.744657,1.940455e-01,0.645763
51,inventors__negated+conjunction,0.039674,0.027966,2.529709e-02,2.569605e-02,0.692308,0.730769,2.264795e-01,0.561406,0.647790,0.682441,2.306867e-01,0.545176
52,inventors__affirmative+negated+conjunction+dis...,0.033069,0.011005,7.604439e-03,7.885243e-03,0.601648,0.641975,2.297930e-01,0.574963,0.595304,0.627700,2.300500e-01,0.558939
53,sp_en_trans__affirmative+negated,0.679232,0.180261,1.693949e-01,1.607487e-01,0.985915,0.987500,1.212580e-02,0.970163,0.980565,0.980180,1.448799e-02,0.965830
54,sp_en_trans__affirmative+disjunction,0.407987,0.050064,4.018475e-02,3.936839e-02,0.766082,0.770115,1.459206e-01,0.725143,0.821376,0.802589,1.230051e-01,0.726880
55,sp_en_trans__negated+conjunction,0.470449,0.091876,7.510325e-02,7.457987e-02,0.964912,0.964286,2.183839e-02,0.954751,0.973646,0.974930,1.930233e-02,0.965014
56,sp_en_trans__affirmative+negated+conjunction+d...,0.439218,0.053440,3.738981e-02,3.742623e-02,0.763158,0.752294,1.577648e-01,0.690828,0.774524,0.765601,1.436550e-01,0.713985
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,0.076932,0.063350,2.100165e-02,2.843561e-02,0.884615,0.896552,9.622575e-02,0.831937,0.910891,0.930233,5.626152e-02,0.899947
58,animal_class+facts+inventors__affirmative+nega...,0.191296,0.014626,1.542448e-02,1.539118e-02,0.710317,0.730627,1.811397e-01,0.643400,0.713573,0.726927,1.828188e-01,0.636351
59,animal_class+facts+inventors__affirmative+nega...,0.171222,0.009766,1.022900e-02,1.020268e-02,0.670814,0.666284,1.937727e-01,0.617268,0.672245,0.657477,1.990079e-01,0.604611

In [117]:
# lyr25_rel_to_18_eval_except_test_df

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
0,animal_class__affirmative,-0.285291,-8.940033e-02,-1.152028e-01,-8.935520e-02,0.000000,0.000000,1.122622e-04,-5.877334e-03,-0.015267,-0.014184,1.186239e-02,-2.102091e-02
1,animal_class__conjunction,0.018766,8.186791e-03,2.467052e-02,2.320108e-02,-0.040000,-0.039604,4.191015e-02,-9.059038e-02,-0.067500,-0.067889,5.506084e-02,-1.049908e-01
2,animal_class__disjunction,0.001194,1.221397e-04,5.374587e-03,5.145711e-03,-0.080000,-0.084038,9.725056e-03,-2.060548e-02,-0.037500,-0.046333,1.338310e-02,-2.524695e-02
3,animal_class__negated,-0.324960,-1.621743e-01,-1.816030e-01,-1.780930e-01,0.000000,0.000000,1.119259e-03,-6.202751e-03,-0.007634,-0.007634,3.250726e-03,-6.748494e-03
4,cities__affirmative,-0.283934,-4.594716e-02,-3.541251e-02,-3.558917e-02,0.003333,0.003557,-3.153302e-03,1.903453e-03,0.003344,0.003317,-1.205682e-03,6.981271e-05
5,cities__conjunction,-0.104271,-5.686192e-02,-6.426473e-02,-6.414848e-02,-0.043333,-0.038904,3.484654e-02,-6.613570e-02,-0.041736,-0.040346,3.525848e-02,-6.943691e-02
6,cities__disjunction,0.019342,2.038331e-02,3.290739e-03,4.289911e-03,-0.170000,-0.177362,6.414803e-02,-1.221834e-01,-0.105000,-0.117998,6.368145e-02,-1.147083e-01
7,cities__negated,-0.440327,-1.626154e-01,-1.742810e-01,-1.717456e-01,0.000000,0.000088,7.547002e-03,-2.445338e-02,-0.026756,-0.026812,2.020656e-02,-4.073712e-02
8,element_symb__affirmative,-0.192289,-8.033626e-02,-1.207695e-01,-1.228036e-01,-0.026316,-0.024390,2.442161e-02,-3.724030e-02,-0.040541,-0.038268,2.626644e-02,-4.094550e-02
9,element_symb__conjunction,-0.144769,-8.259782e-02,-7.095234e-02,-6.869145e-02,-0.050000,-0.053527,3.587925e-02,-6.884092e-02,-0.047500,-0.043187,2.920409e-02,-5.972705e-02
10,element_symb__disjunction,0.035019,3.111772e-02,2.666797e-02,2.637423e-02,-0.010000,-0.014515,2.573338e-02,-5.283666e-02,-0.032500,-0.033809,3.230978e-02,-6.811783e-02
11,element_symb__negated,-0.246579,-1.737191e-01,-1.239042e-01,-1.259207e-01,0.000000,0.000000,-4.215815e-18,3.428472e-10,0.000000,0.000000,3.840772e-16,-1.610772e-09
12,facts__affirmative,-0.032644,-2.764151e-02,-3.028115e-02,-2.891836e-02,-0.044248,-0.037011,4.721766e-02,-8.141320e-02,-0.080357,-0.079470,6.426213e-02,-9.031422e-02
13,facts__conjunction,-0.012120,-1.251708e-02,-5.795836e-03,-6.845959e-03,0.020000,0.032609,-9.182606e-03,-2.182147e-02,-0.045000,-0.041077,2.854658e-02,-5.784152e-02
14,facts__disjunction,-0.002224,-2.200166e-03,-1.830604e-03,-2.032631e-03,-0.050000,-0.062107,2.515804e-02,-4.463084e-02,-0.042500,-0.049087,2.193806e-02,-4.058863e-02
15,facts__negated,-0.016919,-1.689101e-02,-1.395760e-02,-1.414113e-02,-0.088496,-0.068182,4.599107e-02,-8.261796e-02,-0.087054,-0.082300,5.815540e-02,-1.055369e-01
16,inventors__affirmative,-0.031652,-2.677567e-02,-3.729563e-02,-3.676609e-02,-0.256098,-0.242424,1.114537e-01,-1.680956e-01,-0.123457,-0.136585,6.437372e-02,-1.295196e-01
17,inventors__conjunction,-0.008378,-7.642822e-03,-8.926139e-03,-8.824772e-03,-0.080000,-0.057247,5.773502e-02,-8.818345e-02,-0.102500,-0.078511,6.433873e-02,-1.053372e-01
18,inventors__disjunction,-0.004914,-5.692122e-03,-7.270738e-04,-6.915717e-04,-0.010000,-0.006198,1.598202e-02,-3.741122e-02,-0.100000,-0.088889,3.475063e-02,-6.291811e-02
19,inventors__negated,-0.052469,-4.825957e-02,-4.017413e-02,-3.846081e-02,-0.060976,-0.151086,3.848308e-02,-1.172305e-01,-0.070988,-0.126186,3.527279e-02,-8.464342e-02
20,ambiguous_lie,0.002003,1.139251e-08,2.253305e-07,-1.442802e-07,0.000000,NaN,1.588201e-08,NaN,0.000000,NaN,3.905067e-08,NaN
21,ambiguous_truthful_reply,0.002003,1.953885e-07,-3.117704e-07,0.000000e+00,0.000000,0.000000,2.667686e-07,-1.775223e-04,0.000000,0.000000,2.841563e-05,-1.123596e-03
22,honest_reply_despite_incentive_to_lie,0.000000,4.960024e-08,-2.438925e-07,1.181275e-07,0.000000,0.000000,-3.963644e-05,3.045218e-03,0.000000,0.000000,-4.794310e-05,3.357074e-03
23,unambiguous_lie,-0.036171,-4.714378e-08,1.805184e-07,9.851908e-08,0.000000,NaN,1.435774e-13,NaN,0.000000,NaN,-1.505355e-14,NaN
24,unambiguous_truthful_reply,-0.036171,-1.447186e-09,2.047305e-07,1.558389e-07,0.000000,0.000000,6.417079e-07,-3.953026e-04,0.000000,0.000000,7.733017e-07,-4.224293e-04
25,larger_than,-0.182645,-1.001769e-01,-9.189823e-02,-9.220679e-02,0.002525,0.002530,2.919496e-03,-1.345347e-02,-0.006313,-0.006128,6.144088e-03,-1.653707e-02
26,smaller_than,-0.112772,-6.493255e-02,-7.973664e-02,-7.970734e-02,-0.078283,-0.071315,5.272446e-02,-9.430324e-02,-0.061869,-0.061861,4.841164e-02,-9.389029e-02
27,sp_en_trans__negated,-0.171201,-6.764759e-02,-6.823174e-02,-6.855640e-02,0.000000,0.000000,-2.554767e-04,1.988614e-03,-0.003534,-0.003559,4.445173e-03,-2.670271e-03
28,sp_en_trans__affirmative,0.002726,3.213741e-03,-9.363293e-03,-1.136516e-02,0.000000,0.000000,-5.380734e-04,-9.138989e-04,-0.007067,-0.007462,5.163366e-03,-8.341761e-03
29,sp_en_trans__conjunction,-0.026666,-1.610111e-02,-1.459896e-02,-1.489955e-02,0.010000,0.009689,-6.730139e-03,-1.031140e-02,-0.007500,-0.006896,1.026222e-02,-2.802816e-02
30,sp_en_trans__disjunction,-0.009419,-7.427532e-03,-1.464984e-02,-1.476711e-02,-0.170000,-0.225589,9.205567e-02,-1.996417e-01,-0.070000,-0.077994,6.094065e-02,-1.481998e-01
31,common_claim_true_false,-0.005687,-5.352946e-03,-6.262669e-03,-6.274353e-03,-0.039326,-0.037108,2.131980e-02,-4.400563e-02,-0.033427,-0.033676,1.854387e-02,-4.198661e-02
32,counterfact_true_false,-0.006217,-6.157789e-03,-5.869429e-03,-5.868734e-03,-0.069138,-0.064018,2.940543e-02,-5.598207e-02,-0.066951,-0.064585,2.973538e-02,-5.644645e-02
33,animal_class__affirmative+negated,-0.305125,-9.452534e-02,-7.926855e-02,-7.201174e-02,-0.015152,-0.016949,5.919362e-03,-1.554330e-02,-0.015267,-0.014897,1.335564e-02,-2.037106e-02
34,animal_class__affirmative+disjunction,-0.142048,-3.489100e-03,-1.525459e-02,-1.432448e-02,-0.067669,-0.111111,3.276911e-02,-8.371128e-02,-0.077213,-0.098677,3.730218e-02,-8.051745e-02
35,animal_class__negated+conjunction,-0.153097,-9.212968e-03,-4.362312e-03,-3.977434e-03,-0.067669,-0.064132,4.131974e-02,-6.632473e-02,-0.032015,-0.030920,2.578530e-02,-4.928524e-02
36,animal_class__affirmative+negated+conjunction+...,-0.147573,-5.740895e-03,-4.171867e-03,-4.048374e-03,-0.033835,-0.040033,3.518926e-02,-7.210920e-02,-0.043315,-0.045433,4.104519e-02,-7.295157e-02
37,cities__affirmative+negated,-0.362130,-3.626523e-02,-2.911445e-02,-2.862717e-02,-0.018333,-0.016941,1.095054e-02,-2.709486e-02,-0.025084,-0.024533,1.859003e-02,-3.600733e-02
38,cities__affirmative+disjunction,-0.132296,5.043154e-03,4.849459e-03,4.830208e-03,-0.050000,-0.055688,1.699797e-02,-4.151712e-02,-0.020677,-0.024342,1.660354e-02,-3.671870e-02
39,cities__negated+conjunction,-0.272299,-2.588267e-02,-2.479152e-02,-2.468215e-02,-0.038333,-0.034302,2.821924e-02,-5.227100e-02,-0.040936,-0.039517,3.065864e-02,-6.221301e-02
40,cities__affirmative+negated+conjunction+disjun...,-0.202297,-9.309800e-03,-8.865090e-03,-8.863596e-03,-0.017000,-0.013606,2.657623e-02,-5.648370e-02,-0.029323,-0.025741,2.987883e-02,-6.109515e-02
41,element_symb__affirmative+negated,-0.219434,-5.554701e-02,-6.204539e-02,-6.191659e-02,-0.026316,-0.024379,2.206747e-02,-5.098942e-02,-0.033784,-0.033067,2.808880e-02,-4.908365e-02
42,element_symb__affirmative+disjunction,-0.078635,-3.184797e-03,-1.833056e-03,-2.069459e-03,-0.072464,-0.064685,6.832531e-02,-1.360247e-01,-0.151460,-0.163554,8.809534e-02,-1.647872e-01
43,element_symb__negated+conjunction,-0.195674,-5.968279e-02,-4.950923e-02,-4.884815e-02,-0.028986,-0.029412,2.748413e-02,-5.647699e-02,-0.047445,-0.042388,2.906632e-02,-5.268776e-02
44,element_symb__affirmative+negated+conjunction+...,-0.137154,-1.722098e-02,-1.861584e-02,-1.860214e-02,-0.039855,-0.035868,3.304603e-02,-6.309974e-02,-0.055657,-0.054334,2.983125e-02,-5.686779e-02
45,facts__affirmative+negated,-0.024782,-1.960147e-02,-2.047939e-02,-2.043862e-02,-0.048673,-0.050798,3.799465e-02,-9.524645e-02,-0.082589,-0.085409,5.069488e-02,-1.132996e-01
46,facts__affirmative+disjunction,-0.017434,-7.726742e-03,-6.480693e-03,-6.456268e-03,-0.065728,-0.080318,4.831044e-02,-9.093928e-02,-0.082547,-0.091589,4.310838e-02,-8.693221e-02
47,facts__negated+conjunction,-0.014520,-1.049237e-02,-4.586252e-03,-4.692217e-03,0.075117,0.066263,-1.245259e-02,3.071068e-02,0.005896,-0.010966,3.787239e-03,1.253911e-02
48,facts__affirmative+negated+conjunction+disjunc...,-0.015977,-8.449198e-03,-4.559236e-03,-4.631655e-03,-0.028169,-0.036894,2.025090e-02,-5.114826e-02,-0.050118,-0.061797,3.202703e-02,-6.818398e-02
49,inventors__affirmative+negated,-0.042061,-2.352429e-02,-3.267854e-02,-3.189388e-02,-0.115854,-0.115432,5.578684e-02,-1.077464e-01,-0.091049,-0.106019,3.772570e-02,-8.771101e-02
50,inventors__affirmative+disjunction,-0.018283,-4.197317e-03,-6.370005e-03,-6.155968e-03,-0.153846,-0.100849,7.000567e-02,-1.137900e-01,-0.171271,-0.114633,5.645657e-02,-1.004127e-01
51,inventors__negated+conjunction,-0.030423,-1.411927e-02,-1.836455e-02,-1.806040e-02,0.005495,-0.012710,1.323354e-02,-2.825433e-02,-0.009669,-0.030562,1.273127e-02,-3.153749e-02
52,inventors__affirmative+negated+conjunction+dis...,-0.024353,-7.025929e-03,-9.194550e-03,-8.965730e-03,-0.096154,-0.103255,2.425343e-02,-4.067870e-02,-0.053177,-0.068334,1.737706e-02,-3.524581e-02
53,sp_en_trans__affirmative+negated,-0.084237,-4.218578e-02,-4.722846e-02,-4.691704e-02,0.014085,0.012191,2.068136e-03,-1.251396e-02,-0.010601,-0.010542,8.404721e-03,-2.148797e-02
54,sp_en_trans__affirmative+disjunction,-0.003346,-7.552117e-03,-1.219054e-02,-1.208060e-02,0.023392,0.022222,1.403987e-03,-1.628196e-02,-0.020498,-0.020530,1.205411e-02,-3.394068e-02
55,sp_en_trans__negated+conjunction,-0.098934,-4.970191e-02,-4.967604e-02,-4.960743e-02,-0.011696,-0.011834,7.901972e-04,9.475684e-04,-0.001464,-0.001360,-7.532952e-04,5.676038e-03
56,sp_en_trans__affirmative+negated+conjunction+d...,-0.051140,-2.231057e-02,-2.626861e-02,-2.629332e-02,-0.084795,-0.097173,2.632180e-02,-5.123019e-02,-0.079795,-0.087103,2.534690e-02,-4.860622e-02
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,-0.023446,-2.510068e-02,-3.152359e-02,-3.602506e-02,0.000000,0.000000,5.165135e-02,-8.273593e-02,-0.029703,-0.022500,3.132704e-02,-5.482685e-02
58,animal_class+facts+inventors__affirmative+nega...,-0.082852,-9.695680e-03,-7.868419e-03,-7.853551e-03,-0.070106,-0.059871,2.473115e-02,-4.734337e-02,-0.065203,-0.059837,3.129399e-02,-5.472773e-02
59,animal_class+facts+inventors__affirmative+nega...,-0.084794,-8.143202e-03,-8.776671e-03,-8.759915e-03,-0.168552,-0.187770,5.705893e-02,-1.080072e-01,-0.151326,-0.175709,5.306757e-02,-1.040704e-01

In [122]:
numeric_cols_in_25_rel_to_18_df = lyr25_rel_to_18_eval_except_test_df.columns[1:]
noteworthy_rows_mask_25_rel_to_18_df = (lyr25_rel_to_18_eval_except_test_df[numeric_cols_in_25_rel_to_18_df] > 0.05).any(axis=1)
lyr25_rel_to_18_eval_except_test_df[noteworthy_rows_mask_25_rel_to_18_df]

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
1,animal_class__conjunction,0.018766,0.008187,0.024671,0.023201,-0.040000,-0.039604,0.041910,-0.090590,-0.067500,-0.067889,0.055061,-0.104991
6,cities__disjunction,0.019342,0.020383,0.003291,0.004290,-0.170000,-0.177362,0.064148,-0.122183,-0.105000,-0.117998,0.063681,-0.114708
12,facts__affirmative,-0.032644,-0.027642,-0.030281,-0.028918,-0.044248,-0.037011,0.047218,-0.081413,-0.080357,-0.079470,0.064262,-0.090314
15,facts__negated,-0.016919,-0.016891,-0.013958,-0.014141,-0.088496,-0.068182,0.045991,-0.082618,-0.087054,-0.082300,0.058155,-0.105537
16,inventors__affirmative,-0.031652,-0.026776,-0.037296,-0.036766,-0.256098,-0.242424,0.111454,-0.168096,-0.123457,-0.136585,0.064374,-0.129520
17,inventors__conjunction,-0.008378,-0.007643,-0.008926,-0.008825,-0.080000,-0.057247,0.057735,-0.088183,-0.102500,-0.078511,0.064339,-0.105337
26,smaller_than,-0.112772,-0.064933,-0.079737,-0.079707,-0.078283,-0.071315,0.052724,-0.094303,-0.061869,-0.061861,0.048412,-0.093890
30,sp_en_trans__disjunction,-0.009419,-0.007428,-0.014650,-0.014767,-0.170000,-0.225589,0.092056,-0.199642,-0.070000,-0.077994,0.060941,-0.148200
42,element_symb__affirmative+disjunction,-0.078635,-0.003185,-0.001833,-0.002069,-0.072464,-0.064685,0.068325,-0.136025,-0.151460,-0.163554,0.088095,-0.164787
45,facts__affirmative+negated,-0.024782,-0.019601,-0.020479,-0.020439,-0.048673,-0.050798,0.037995,-0.095246,-0.082589,-0.085409,0.050695,-0.113300
47,facts__negated+conjunction,-0.014520,-0.010492,-0.004586,-0.004692,0.075117,0.066263,-0.012453,0.030711,0.005896,-0.010966,0.003787,0.012539
49,inventors__affirmative+negated,-0.042061,-0.023524,-0.032679,-0.031894,-0.115854,-0.115432,0.055787,-0.107746,-0.091049,-0.106019,0.037726,-0.087711
50,inventors__affirmative+disjunction,-0.018283,-0.004197,-0.006370,-0.006156,-0.153846,-0.100849,0.070006,-0.113790,-0.171271,-0.114633,0.056457,-0.100413
57,ambiguous_truthful_reply+unambiguous_lie+unamb...,-0.023446,-0.025101,-0.031524,-0.036025,0.000000,0.000000,0.051651,-0.082736,-0.029703,-0.022500,0.031327,-0.054827
59,animal_class+facts+inventors__affirmative+nega...,-0.084794,-0.008143,-0.008777,-0.008760,-0.168552,-0.187770,0.057059,-0.108007,-0.151326,-0.175709,0.053068,-0.104070

In [123]:
# lyrs18_and_25_rel_to_18_eval_except_test_df

In [124]:
numeric_cols_in_18_and_25_rel_to_just_18_df = lyrs18_and_25_rel_to_18_eval_except_test_df.columns[1:]
noteworthy_rows_mask_18_and_25_rel_to_just_18_df = (lyrs18_and_25_rel_to_18_eval_except_test_df[numeric_cols_in_18_and_25_rel_to_just_18_df] > 0.05).any(axis=1)
lyrs18_and_25_rel_to_18_eval_except_test_df[noteworthy_rows_mask_18_and_25_rel_to_just_18_df]

,scenario,tf_sep,train_recon_improv,val_recon_improv,val_recon_improv_w_val_mean,val_acc,val_f1,val_brier,val_soft_f1,train_acc,train_f1,train_brier,train_soft_f1
16,inventors__affirmative,-0.015826,-2.431159e-02,-3.382800e-02,-3.334448e-02,-0.195122,-0.172249,0.094136,-0.146931,-0.123457,-0.126471,0.058390,-0.116833
17,inventors__conjunction,-0.004189,-6.718014e-03,-7.822330e-03,-7.735049e-03,-0.110000,-0.074597,0.059757,-0.079067,-0.092500,-0.068242,0.056397,-0.092357
19,inventors__negated,-0.026234,-4.381326e-02,-3.648667e-02,-3.492981e-02,-0.024390,-0.095031,0.012323,-0.111886,-0.132716,-0.239270,0.051626,-0.161818
22,honest_reply_despite_incentive_to_lie,0.000000,1.319963e-07,-3.252974e-07,1.066376e-07,0.000000,0.000000,-0.000040,0.003109,-0.250000,-0.142857,0.172093,-0.165552
30,sp_en_trans__disjunction,-0.004710,-6.358973e-03,-1.253878e-02,-1.263844e-02,-0.130000,-0.136863,0.072719,-0.140886,-0.075000,-0.072037,0.046113,-0.106136
34,animal_class__affirmative+disjunction,-0.071024,-3.044414e-03,-1.323719e-02,-1.243323e-02,-0.142857,-0.272031,0.054307,-0.132322,-0.122411,-0.207832,0.048500,-0.109658
42,element_symb__affirmative+disjunction,-0.039317,-2.824167e-03,-1.622398e-03,-1.831317e-03,-0.108696,-0.113763,0.073450,-0.138046,-0.087591,-0.092539,0.055013,-0.104647
47,facts__negated+conjunction,-0.007260,-9.184187e-03,-4.028593e-03,-4.121554e-03,0.093897,0.075322,-0.020735,0.045220,0.033019,0.019637,-0.008713,0.032911
50,inventors__affirmative+disjunction,-0.009142,-3.710394e-03,-5.631723e-03,-5.442076e-03,-0.120879,-0.093515,0.057898,-0.087571,-0.114641,-0.079304,0.040331,-0.068412

With only 1 scenario out of 60 showing a 5+ percentage-point-improvement in validation accuracy for layer 25 relative to layer 18 (and the same for the combination of both layers 18 and 25 relative to just layer 18), it seems likely that that one case is probably just a result of noise/randomness.
Going forward, the layer25 and layers18&25 directions/probes will be largely ignored

In [127]:
lyr18_probe_metrics_on_test_dsets: dict[tuple[int,...], dict[int, ConfusionMetrics]] = {
    scenario_id: {
        dset_idx_in_scenario: test_dset_metrics.lyr18_probe_metrics for dset_idx_in_scenario, test_dset_metrics in test_dsets_metrics.items()
    } 
    for scenario_id, test_dsets_metrics in probes_metrics_on_test_dsets.items()
}

In [137]:
# Just using accuracy because there are going to be _so_ many columns in this analysis's dataframe and examination of validation accuracy vs f1 vs soft-f1 for layer 18 probes showed that they were generally very similar for the standard topics' datasets (because those datasets were specifically constructed to be balanced between true and false statements) 
class GeneralizationAccuracyWithinVsAcrossTopics(NamedTuple):
    affirm_within_topics: float
    affirm_across_topics: float
    neg_within_topics: float
    neg_across_topics: float
    conj_within_topics: float
    conj_across_topics: float
    disj_within_topics: float
    disj_across_topics: float
    de_affirm_within_topics: float
    de_affirm_across_topics: float
    de_neg_within_topics: float
    de_neg_across_topics: float

class TopicGeneralizationSummary(NamedTuple):
    avg_across_topic_penalty: float
    affirm_across_topic_penalty: float
    neg_across_topic_penalty: float
    conj_across_topic_penalty: float
    disj_across_topic_penalty: float
    de_affirm_across_topic_penalty: float
    de_neg_across_topic_penalty: float

lyr18_probe_generalization_within_vs_across_topics: dict[tuple[int,...], GeneralizationAccuracyWithinVsAcrossTopics] = {}
lyr18_probe_topic_generalization_summary: dict[tuple[int,...], TopicGeneralizationSummary] = {}

for scenario_id, test_dsets_metrics in lyr18_probe_metrics_on_test_dsets.items():
    curr_standard_categs = scenario_standard_categs[scenario_id]
    curr_data_variants = scenario_data_variants[scenario_id]
    if not curr_standard_categs:
        continue
    unseen_standard_categs = list(set(dset_idxs_for_4way_topics.keys()) - set(curr_standard_categs))
    metrics_on_test_dsets = lyr18_probe_metrics_on_test_dsets[scenario_id]
    
    affirm_within_topics_acc = np.nan
    affirm_across_topics_acc = np.nan
    if "affirm" not in curr_data_variants:
        same_topics_affirm_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["affirm"]] for topic_nm in curr_standard_categs
        ])
        affirm_within_topics_acc = same_topics_affirm_test_metrics.get_traditional_metrics().accuracy
        across_topics_affirm_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["affirm"]] for topic_nm in unseen_standard_categs
        ])
        affirm_across_topics_acc = across_topics_affirm_test_metrics.get_traditional_metrics().accuracy
    neg_within_topics_acc = np.nan
    neg_across_topics_acc = np.nan
    if "neg" not in curr_data_variants:
        same_topics_neg_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["neg"]] for topic_nm in curr_standard_categs
        ])
        neg_within_topics_acc = same_topics_neg_test_metrics.get_traditional_metrics().accuracy
        across_topics_neg_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["neg"]] for topic_nm in unseen_standard_categs
        ])
        neg_across_topics_acc = across_topics_neg_test_metrics.get_traditional_metrics().accuracy
    conj_within_topics_acc = np.nan
    conj_across_topics_acc = np.nan
    if "conj" not in curr_data_variants:
        same_topics_conj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["conj"]] for topic_nm in curr_standard_categs
        ])
        conj_within_topics_acc = same_topics_conj_test_metrics.get_traditional_metrics().accuracy
        across_topics_conj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["conj"]] for topic_nm in unseen_standard_categs
        ])
        conj_across_topics_acc = across_topics_conj_test_metrics.get_traditional_metrics().accuracy
    disj_within_topics_acc = np.nan
    disj_across_topics_acc = np.nan
    if "disj" not in curr_data_variants:
        same_topics_disj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["disj"]] for topic_nm in curr_standard_categs
        ])
        disj_within_topics_acc = same_topics_disj_test_metrics.get_traditional_metrics().accuracy
        across_topics_disj_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["disj"]] for topic_nm in unseen_standard_categs
        ])
        disj_across_topics_acc = across_topics_disj_test_metrics.get_traditional_metrics().accuracy
    de_affirm_within_topics_acc = np.nan
    de_affirm_across_topics_acc = np.nan
    if "de_affirm" not in curr_data_variants:
        same_topics_de_affirm_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_affirm"]] for topic_nm in curr_standard_categs
        ])
        de_affirm_within_topics_acc = same_topics_de_affirm_test_metrics.get_traditional_metrics().accuracy
        across_topics_de_affirm_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_affirm"]] for topic_nm in unseen_standard_categs
        ])
        de_affirm_across_topics_acc = across_topics_de_affirm_test_metrics.get_traditional_metrics().accuracy
    de_neg_within_topics_acc = np.nan
    de_neg_across_topics_acc = np.nan
    if "de_neg" not in curr_data_variants:
        same_topics_de_neg_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_neg"]] for topic_nm in curr_standard_categs
        ])
        de_neg_within_topics_acc = same_topics_de_neg_test_metrics.get_traditional_metrics().accuracy
        across_topics_de_neg_test_metrics = ConfusionMetrics.combine(*[
            metrics_on_test_dsets[dset_idxs_for_4way_topics[topic_nm]["de_neg"]] for topic_nm in unseen_standard_categs
        ])
        de_neg_across_topics_acc = across_topics_de_neg_test_metrics.get_traditional_metrics().accuracy
    
    lyr18_probe_generalization_within_vs_across_topics[scenario_id] = GeneralizationAccuracyWithinVsAcrossTopics(
        affirm_within_topics=affirm_within_topics_acc, affirm_across_topics=affirm_across_topics_acc, neg_within_topics=neg_within_topics_acc,
        neg_across_topics=neg_across_topics_acc, conj_within_topics=conj_within_topics_acc, conj_across_topics=conj_across_topics_acc,
        disj_within_topics=disj_within_topics_acc, disj_across_topics=disj_across_topics_acc, de_affirm_within_topics=de_affirm_within_topics_acc,
        de_affirm_across_topics=de_affirm_across_topics_acc, de_neg_within_topics=de_neg_within_topics_acc, de_neg_across_topics=de_neg_across_topics_acc
    )
    
    affirm_across_topic_acc_penalty = affirm_within_topics_acc-affirm_across_topics_acc
    neg_across_topic_acc_penalty = neg_within_topics_acc-neg_across_topics_acc
    conj_across_topic_acc_penalty = conj_within_topics_acc-conj_across_topics_acc
    disj_across_topic_acc_penalty = disj_within_topics_acc-disj_across_topics_acc
    de_affirm_across_topic_acc_penalty = de_affirm_within_topics_acc-de_affirm_across_topics_acc
    de_neg_across_topic_acc_penalty = de_neg_within_topics_acc-de_neg_across_topics_acc
    avg_across_topic_acc_penalty = float(np.nanmean([affirm_across_topic_acc_penalty, neg_across_topic_acc_penalty, conj_across_topic_acc_penalty, disj_across_topic_acc_penalty, de_affirm_across_topic_acc_penalty, de_neg_across_topic_acc_penalty]))
    
    lyr18_probe_topic_generalization_summary[scenario_id] = TopicGeneralizationSummary(
        avg_across_topic_penalty=avg_across_topic_acc_penalty, affirm_across_topic_penalty=avg_across_topic_acc_penalty, 
        neg_across_topic_penalty=neg_across_topic_acc_penalty, conj_across_topic_penalty=conj_across_topic_acc_penalty,
        disj_across_topic_penalty=disj_across_topic_acc_penalty, de_affirm_across_topic_penalty=de_affirm_across_topic_acc_penalty,
        de_neg_across_topic_penalty=de_neg_across_topic_acc_penalty
    )
    
    
generalization_within_vs_across_topics_df = pd.DataFrame([
    { "scenario": scenario_labels[scenario_id], **generalization_info._asdict()  } for scenario_id, generalization_info in lyr18_probe_generalization_within_vs_across_topics.items()
])
topic_generalization_summary_df = pd.DataFrame([
    { "scenario": scenario_labels[scenario_id], **generalization_summary._asdict()  } for scenario_id, generalization_summary in lyr18_probe_topic_generalization_summary.items()
])

In [138]:
generalization_within_vs_across_topics_df

,scenario,affirm_within_topics,affirm_across_topics,neg_within_topics,neg_across_topics,conj_within_topics,conj_across_topics,disj_within_topics,disj_across_topics,de_affirm_within_topics,de_affirm_across_topics,de_neg_within_topics,de_neg_across_topics
0,animal_class__affirmative,NaN,NaN,0.621951,0.539794,0.738000,0.643225,0.502000,0.459200,0.86,0.564000,0.420000,0.502008
1,animal_class__conjunction,0.524390,0.774892,0.487805,0.511822,NaN,NaN,0.502000,0.560800,0.52,0.636000,0.540000,0.518072
2,animal_class__disjunction,0.810976,0.856144,0.487805,0.507493,0.882000,0.694111,NaN,NaN,0.50,0.664000,0.540000,0.550201
3,animal_class__negated,0.975610,0.920746,NaN,NaN,0.752000,0.778731,0.524000,0.547200,0.92,0.776000,0.900000,0.759036
4,cities__affirmative,NaN,NaN,0.856283,0.528426,0.658879,0.608800,0.576000,0.508000,0.94,0.628000,0.600000,0.481928
5,cities__conjunction,0.929813,0.918612,0.500000,0.532615,NaN,NaN,0.518000,0.507600,0.96,0.792000,0.500000,0.485944
6,cities__disjunction,0.952540,0.667265,0.514037,0.470975,0.640854,0.695600,NaN,NaN,0.66,0.568000,0.580000,0.497992
7,cities__negated,0.844251,0.750449,NaN,NaN,0.576101,0.639600,0.484000,0.535200,0.92,0.648000,1.000000,0.726908
8,element_symb__affirmative,NaN,NaN,0.500000,0.508554,0.480000,0.490852,0.482000,0.506000,0.72,0.572000,0.520000,0.518072
9,element_symb__conjunction,0.505376,0.557866,0.500000,0.509896,NaN,NaN,0.484000,0.508800,0.48,0.540000,0.520000,0.522088
10,element_symb__disjunction,0.623656,0.564240,0.349462,0.554512,0.638000,0.576043,NaN,NaN,0.68,0.648000,0.240000,0.473896
11,element_symb__negated,0.392473,0.288158,NaN,NaN,0.278000,0.506861,0.446000,0.508400,0.30,0.484000,0.920000,0.726908
12,facts__affirmative,NaN,NaN,0.532977,0.509210,0.722000,0.742710,0.546000,0.494800,0.68,0.848000,0.530612,0.524000
13,facts__conjunction,0.557932,0.498465,0.502674,0.509210,NaN,NaN,0.550000,0.494800,0.52,0.544000,0.489796,0.524000
14,facts__disjunction,0.655971,0.800077,0.506239,0.514198,0.528000,0.697541,NaN,NaN,0.54,0.636000,0.510204,0.480000
15,facts__negated,0.711230,0.728703,NaN,NaN,0.474000,0.518296,0.462000,0.505200,0.54,0.576000,0.714286,0.660000
16,inventors__affirmative,NaN,NaN,0.556650,0.802608,0.712000,0.702115,0.584000,0.530800,0.86,0.796000,0.700000,0.698795
17,inventors__conjunction,0.633005,0.614270,0.623153,0.500905,NaN,NaN,0.454000,0.514800,0.50,0.680000,0.600000,0.461847
18,inventors__disjunction,0.842365,0.647954,0.509852,0.500181,0.646000,0.784162,NaN,NaN,0.62,0.504000,0.600000,0.510040
19,inventors__negated,0.610837,0.895328,NaN,NaN,0.584000,0.715838,0.456000,0.527600,0.44,0.744000,0.760000,0.690763
20,sp_en_trans__negated,0.497175,0.382865,NaN,NaN,0.436000,0.461407,0.530000,0.488800,0.48,0.420000,0.960000,0.815261
21,sp_en_trans__affirmative,NaN,NaN,0.500000,0.765375,0.824000,0.717553,0.586000,0.556400,0.86,0.772000,0.440000,0.654618
22,sp_en_trans__conjunction,0.502825,0.610380,0.500000,0.533950,NaN,NaN,0.538000,0.553600,0.54,0.720000,0.460000,0.510040
23,sp_en_trans__disjunction,0.508475,0.647707,0.497175,0.564522,0.880000,0.555746,NaN,NaN,0.54,0.580000,0.460000,0.530120
24,animal_class__affirmative+negated,NaN,NaN,NaN,NaN,0.742000,0.760149,0.516000,0.611600,0.90,0.760000,0.900000,0.718876
25,animal_class__affirmative+disjunction,NaN,NaN,0.890244,0.507493,0.670000,0.720412,NaN,NaN,0.88,0.756000,0.680000,0.510040
26,animal_class__negated+conjunction,0.975610,0.921079,NaN,NaN,NaN,NaN,0.502000,0.508800,0.90,0.784000,0.920000,0.734940
27,animal_class__affirmative+negated+conjunction+...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.88,0.716000,0.740000,0.578313
28,cities__affirmative+negated,NaN,NaN,NaN,NaN,0.667557,0.677200,0.668000,0.574000,0.98,0.736000,1.000000,0.775100
29,cities__affirmative+disjunction,NaN,NaN,0.861631,0.539797,0.633511,0.644400,NaN,NaN,0.94,0.664000,0.660000,0.485944
30,cities__negated+conjunction,0.940508,0.841412,NaN,NaN,NaN,NaN,0.520000,0.512000,0.98,0.780000,0.960000,0.630522
31,cities__affirmative+negated+conjunction+disjun...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.98,0.748000,1.000000,0.742972
32,element_symb__affirmative+negated,NaN,NaN,NaN,NaN,0.916000,0.761578,0.482000,0.559600,0.60,0.820000,0.800000,0.783133
33,element_symb__affirmative+disjunction,NaN,NaN,0.731183,0.687689,0.778000,0.632361,NaN,NaN,0.80,0.752000,0.520000,0.546185
34,element_symb__negated+conjunction,0.500000,0.504193,NaN,NaN,NaN,NaN,0.482000,0.550800,0.48,0.652000,0.680000,0.811245
35,element_symb__affirmative+negated+conjunction+...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62,0.836000,0.760000,0.779116
36,facts__affirmative+negated,NaN,NaN,NaN,NaN,0.550000,0.576901,0.474000,0.554400,0.64,0.764000,0.755102,0.816000
37,facts__affirmative+disjunction,NaN,NaN,0.600713,0.773599,0.728000,0.881361,NaN,NaN,0.58,0.776000,0.551020,0.620000
38,facts__negated+conjunction,0.873440,0.937836,NaN,NaN,NaN,NaN,0.712000,0.573600,0.64,0.804000,0.714286,0.832000
39,facts__affirmative+negated+conjunction+disjunc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.66,0.808000,0.734694,0.856000
40,inventors__affirmative+negated,NaN,NaN,NaN,NaN,0.580000,0.550886,0.570000,0.511600,0.78,0.612000,0.840000,0.718876
41,inventors__affirmative+disjunction,NaN,NaN,0.625616,0.804781,0.692000,0.822470,NaN,NaN,0.86,0.828000,0.580000,0.662651
42,inventors__negated+conjunction,0.435961,0.494748,NaN,NaN,NaN,NaN,0.532000,0.498000,0.40,0.540000,0.840000,0.726908
43,inventors__affirmative+negated+conjunction+dis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.80,0.820000,0.600000,0.506024
44,sp_en_trans__affirmative+negated,NaN,NaN,NaN,NaN,0.964000,0.739851,0.528000,0.535200,0.96,0.796000,0.540000,0.775100
45,sp_en_trans__affirmative+disjunction,NaN,NaN,0.415254,0.618201,0.814000,0.584906,NaN,NaN,0.84,0.648000,0.520000,0.465863
46,sp_en_trans__negated+conjunction,0.500000,0.492001,NaN,NaN,NaN,NaN,0.534000,0.564400,0.56,0.476000,0.980000,0.791165
47,sp_en_trans__affirmative+negated+conjunction+d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96,0.784000,0.540000,0.759036
48,animal_class+facts+inventors__affirmative+nega...,NaN,NaN,NaN,NaN,NaN,NaN,0.559333,0.512667,0.80,0.833333,0.657718,0.586667
49,animal_class+facts+inventors__affirmative+nega...,NaN,NaN,NaN,NaN,0.772000,0.915132,0.505333,0.510000,0.76,0.840000,0.724832,0.673333

In [139]:
topic_generalization_summary_df

,scenario,avg_across_topic_penalty,affirm_across_topic_penalty,neg_across_topic_penalty,conj_across_topic_penalty,disj_across_topic_penalty,de_affirm_across_topic_penalty,de_neg_across_topic_penalty
0,animal_class__affirmative,0.086745,0.086745,0.082158,0.094775,0.042800,0.296000,-0.082008
1,animal_class__conjunction,-0.085478,-0.085478,-0.024017,NaN,-0.058800,-0.116000,0.021928
2,animal_class__disjunction,-0.010234,-0.010234,-0.019688,0.187889,NaN,-0.164000,-0.010201
3,animal_class__negated,0.057979,0.057979,NaN,-0.026731,-0.023200,0.144000,0.140964
4,cities__affirmative,0.175202,0.175202,0.327857,0.050079,0.068000,0.312000,0.118072
5,cities__conjunction,0.034208,0.034208,-0.032615,NaN,0.010400,0.168000,0.014056
6,cities__disjunction,0.089520,0.089520,0.043062,-0.054746,NaN,0.092000,0.082008
7,cities__negated,0.104839,0.104839,NaN,-0.063499,-0.051200,0.272000,0.273092
8,element_symb__affirmative,0.021304,0.021304,-0.008554,-0.010852,-0.024000,0.148000,0.001928
9,element_symb__conjunction,-0.029855,-0.029855,-0.009896,NaN,-0.024800,-0.060000,-0.002088
10,element_symb__disjunction,-0.057115,-0.057115,-0.205050,0.061957,NaN,0.032000,-0.233896
11,element_symb__negated,-0.035571,-0.035571,NaN,-0.228861,-0.062400,-0.184000,0.193092
12,facts__affirmative,-0.021426,-0.021426,0.023767,-0.020710,0.051200,-0.168000,0.006612
13,facts__conjunction,0.009985,0.009985,-0.006536,NaN,0.055200,-0.024000,-0.034204
14,facts__disjunction,-0.077480,-0.077480,-0.007959,-0.169541,NaN,-0.096000,0.030204
15,facts__negated,-0.017337,-0.017337,NaN,-0.044296,-0.043200,-0.036000,0.054286
16,inventors__affirmative,-0.023534,-0.023534,-0.245958,0.009885,0.053200,0.064000,0.001205
17,inventors__conjunction,0.007667,0.007667,0.122247,NaN,-0.060800,-0.180000,0.138153
18,inventors__disjunction,0.054376,0.054376,0.009671,-0.138162,NaN,0.116000,0.089960
19,inventors__negated,-0.144538,-0.144538,NaN,-0.131838,-0.071600,-0.304000,0.069237
20,sp_en_trans__negated,0.066968,0.066968,NaN,-0.025407,0.041200,0.060000,0.144739
21,sp_en_trans__affirmative,-0.051189,-0.051189,-0.265375,0.106447,0.029600,0.088000,-0.214618
22,sp_en_trans__conjunction,-0.077429,-0.077429,-0.033950,NaN,-0.015600,-0.180000,-0.050040
23,sp_en_trans__disjunction,0.001511,0.001511,-0.067347,0.324254,NaN,-0.040000,-0.070120
24,animal_class__affirmative+negated,0.051844,0.051844,NaN,-0.018149,-0.095600,0.140000,0.181124
25,animal_class__affirmative+disjunction,0.156575,0.156575,0.382751,-0.050412,NaN,0.124000,0.169960
26,animal_class__negated+conjunction,0.087198,0.087198,NaN,NaN,-0.006800,0.116000,0.185060
27,animal_class__affirmative+negated+conjunction+...,0.162843,0.162843,NaN,NaN,NaN,0.164000,0.161687
28,cities__affirmative+negated,0.138314,0.138314,NaN,-0.009643,0.094000,0.244000,0.224900
29,cities__affirmative+disjunction,0.190251,0.190251,0.321834,-0.010889,NaN,0.276000,0.174056
30,cities__negated+conjunction,0.159143,0.159143,NaN,NaN,0.008000,0.200000,0.329478
31,cities__affirmative+negated+conjunction+disjun...,0.244514,0.244514,NaN,NaN,NaN,0.232000,0.257028
32,element_symb__affirmative+negated,-0.031578,-0.031578,NaN,0.154422,-0.077600,-0.220000,0.016867
33,element_symb__affirmative+disjunction,0.052737,0.052737,0.043494,0.145639,NaN,0.048000,-0.026185
34,element_symb__negated+conjunction,-0.094060,-0.094060,NaN,NaN,-0.068800,-0.172000,-0.131245
35,element_symb__affirmative+negated+conjunction+...,-0.117558,-0.117558,NaN,NaN,NaN,-0.216000,-0.019116
36,facts__affirmative+negated,-0.073050,-0.073050,NaN,-0.026901,-0.080400,-0.124000,-0.060898
37,facts__affirmative+disjunction,-0.147807,-0.147807,-0.172886,-0.153361,NaN,-0.196000,-0.068980
38,facts__negated+conjunction,-0.051927,-0.051927,NaN,NaN,0.138400,-0.164000,-0.117714
39,facts__affirmative+negated+conjunction+disjunc...,-0.134653,-0.134653,NaN,NaN,NaN,-0.148000,-0.121306
40,inventors__affirmative+negated,0.094160,0.094160,NaN,0.029114,0.058400,0.168000,0.121124
41,inventors__affirmative+disjunction,-0.090071,-0.090071,-0.179165,-0.130470,NaN,0.032000,-0.082651
42,inventors__negated+conjunction,-0.012924,-0.012924,NaN,NaN,0.034000,-0.140000,0.113092
43,inventors__affirmative+negated+conjunction+dis...,0.036988,0.036988,NaN,NaN,NaN,-0.020000,0.093976
44,sp_en_trans__affirmative+negated,0.036462,0.036462,NaN,0.224149,-0.007200,0.164000,-0.235100
45,sp_en_trans__affirmative+disjunction,0.068071,0.068071,-0.202947,0.229094,NaN,0.192000,0.054137
46,sp_en_trans__negated+conjunction,0.062608,0.062608,NaN,NaN,-0.030400,0.084000,0.188835
47,sp_en_trans__affirmative+negated+conjunction+d...,-0.021518,-0.021518,NaN,NaN,NaN,0.176000,-0.219036
48,animal_class+facts+inventors__affirmative+nega...,0.028128,0.028128,NaN,NaN,0.046667,-0.033333,0.071051
49,animal_class+facts+inventors__affirmative+nega...,-0.044075,-0.044075,NaN,-0.143132,-0.004667,-0.080000,0.051499

In [141]:
(avg_topic_generalization_penalty_across_all_scenarios := topic_generalization_summary_df.avg_across_topic_penalty.mean().item())

0.016594720436278312

The cross-topic generalization penalty is surprisingly small (<2 percentage-points on average), so we will ignore the "already-seen topic vs fully-unseen topic" distinction for analysis beyond this point.

In passing, it is surprising that the 3-topic affirmative+negated+conjunction scenario had worse cross-topic generalization than the average scenario.

TODO check how large a performance difference there was between positive vs negated german data  
 Highlight the result, then collapse the "positive german vs negated german" dimension of comparison for subsequent analysis

TODO present finalized tables of results (acc, f1, brier, soft-f1)  
    - perf on all unseen data  
    - perf on unseen real-world-scenarios data  
    - perf on unseen relative-comparison data   
    - perf on unseen true-false data  
    - perf on all german datasets  
    - perf on all unseen non-german affirmative data within standard topics  
    - perf on unseen negative polarity data  
    - perf on unseen conjunction data  
    - perf on unseen disjunction data  
    - perf on all data of animal-class (only if the probe had never seen any from animal-class)
    - perf on all data of cities (only if the probe had never seen any from cities)
    - perf on all data of element-symbol (only if the probe had never seen any from element-symbol)
    - perf on all data of facts (only if the probe had never seen any from facts)
    - perf on all data of inventors (only if the probe had never seen any from inventors)
    - perf on all data of real-world-scenarios (only if the probe had never seen any from real-world-scenarios)
    - perf on all data of relative-comparison (only if the probe had never seen any from relative-comparison)
    - perf on all data of spanish-english-translation (only if the probe had never seen any from spanish-english-translation)
    - perf on all data of true-false (only if the probe had never seen any from true-false)

TODO double check whether there are any scenario/test-dataset combinations where layer25 or layers18&25 probes generalize better than layer18 probes